/* ============================================================
   수학아 놀자 (math) - 고등 공식 22개: 미적분·경우의 수·벡터·통계 (formula-hi-b.js)
   formula-data.js 가 합쳐서 window.MathFormulaData 로 만듭니다.
   ============================================================ */
window.MathFormulaHiB = [
  {
    id: "hi_limit",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "🎯",
    unit: "극한",
    title: "극한이란?",
    formula: "x가 a에 다가가면 f(x)는 L에 다가가요",
    latex: "\\lim_{x \\to a} f(x) = L",
    shortDescription: "입력값이 어떤 수에 다가갈 때 출력값이 다가가는 곳을 찾는 개념이에요.",
    easyExplanation: "극한은 정확히 찌르는 것이 아니라 점점 다가가서 어디에 모이는지 보는 거예요. 그래프 위의 점이 어느 높이에 가까워지는지 관찰하시면 돼요. 다가가기만 해도 값을 짐작할 수 있어서 미분의 출발점이 돼요.",
    funExplanation: "과녁에 화살을 점점 더 가깝게 맞히는 모습이라고 생각하세요. 바로 명중하지 않아도 모이는 곳을 알 수 있어요. 수학에서는 다가가는 과정 자체가 중요해요.",
    memoryTip: "극한은 다가가기, 어디에 모이는지 보세요.",
    useWhen: "함수값이 바로 안 보일 때 다가가는 값으로 판단하고 싶을 때 써요.",
    commonMistakes: ["다가가는 값과 실제 함수값이 항상 같지는 않아요.", "왼쪽과 오른쪽에서 다가가는 값을 둘 다 확인하세요."],
    example: { question: "x가 2에 다가갈 때 x + 3은 어디에 다가가나요?", steps: ["x 자리에 다가가는 수 2를 넣어 보세요.", "2 + 3을 계산하면 5가 돼요.", "그래서 극한값은 5라고 말해요."], answer: "5" },
    quickCheck: { question: "x가 3에 다가갈 때 2x는 어디에 다가가나요?", answer: "6" },
    relatedFormulaIds: ["hi_derivative", "hi_def_integral"]
  },
  {
    id: "hi_derivative",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "📉",
    unit: "미분",
    title: "미분계수와 도함수",
    formula: "f′(a) = 순간 변화율 = 순간 기울기",
    latex: "f^{\\prime}(a) = \\lim_{h \\to 0} \\frac{f(a+h)-f(a)}{h}",
    shortDescription: "어느 한순간의 변화율, 즉 그래프의 순간 기울기를 구하는 방법이에요.",
    easyExplanation: "미분은 어느 순간의 변화율을 재는 도구예요. 그래프에서는 그 점에서의 순간 기울기와 같아요. 평균 기울기의 간격을 점점 좁히면 순간 기울기가 나와요.",
    funExplanation: "자동차 속도계가 바로 지금 속도를 보여주는 것과 같아요. 전체 평균이 아니라 바로 이 순간의 빠르기를 재는 거예요. 미분계수는 그 순간의 속도라고 외우세요.",
    memoryTip: "미분은 순간 변화율, 그래프에서는 순간 기울기예요.",
    useWhen: "순간의 속도나 순간의 기울기가 궁금할 때 써요.",
    commonMistakes: ["평균 변화율과 순간 변화율을 섞지 마세요.", "h를 0에 다가보내야지 바로 0을 넣으면 안 돼요."],
    example: { question: "f(x) = x²일 때 x = 3에서의 미분계수를 구하세요.", steps: ["미분계수 식에 f(x) = x²을 넣어 보세요.", "(9 + 6h + h² - 9) ÷ h = 6 + h가 돼요.", "h가 0에 다가가면 답은 6이 돼요."], answer: "6" },
    quickCheck: { question: "f(x) = 2x일 때 x = 5에서의 미분계수는?", answer: "2" },
    relatedFormulaIds: ["hi_limit", "hi_power_rule", "hi_tangent"]
  },
  {
    id: "hi_power_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "⚡",
    unit: "미분",
    title: "거듭제곱의 미분",
    formula: "(xⁿ)′ = n × xⁿ⁻¹",
    latex: "\\frac{d}{dx} x^n = n x^{n-1}",
    shortDescription: "제곱이나 세제곱 같은 거듭제곱은 앞의 수를 내리고 하나를 빼서 미분해요.",
    easyExplanation: "거듭제곱의 미분은 규칙이 아주 간단해요. 앞에 있던 지수를 앞으로 내리고 지수에서 하나를 빼주시면 돼요. 이 규칙 하나로 다항식을 아주 빠르게 미분할 수 있어요.",
    funExplanation: "지수가 앞으로 점프해서 내려온다고 상상하세요. 원래 있던 자리에서는 하나가 사라지는 거예요. 번개처럼 빠른 공식이라서 계산이 쉬워져요.",
    memoryTip: "지수는 앞으로, 차수는 하나 빼기.",
    useWhen: "x의 거듭제곱으로 된 식을 순간 변화율로 바꿀 때 써요.",
    commonMistakes: ["지수에서 하나 빼는 것을 잊지 마세요.", "상수항의 미분은 0이 돼요."],
    example: { question: "f(x) = x³을 미분하세요.", steps: ["지수가 3이므로 앞에 3을 곱하세요.", "지수에서 하나를 빼서 x²으로 만드세요.", "그래서 도함수는 3x²이 돼요."], answer: "3x²" },
    quickCheck: { question: "f(x) = x⁵를 미분하면?", answer: "5x⁴" },
    relatedFormulaIds: ["hi_derivative", "hi_indef_integral"]
  },
  {
    id: "hi_product_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "✖️",
    unit: "미분",
    title: "곱과 몫의 미분",
    formula: "(fg)′ = 앞미분×뒤 + 앞×뒤미분",
    latex: "(fg)^{\\prime} = f^{\\prime}g + fg^{\\prime}",
    shortDescription: "두 식이 곱해진 경우와 나누어진 경우를 미분하는 약속이에요.",
    easyExplanation: "곱해진 식은 각각 따로 미분해서 더하듯이 계산해요. 앞을 미분한 것과 뒤를 그대로 둔 것, 앞을 그대로 두고 뒤를 미분한 것을 더하시면 돼요. 몫의 미분도 분자와 분모를 같은 방식으로 다루며 분모를 제곱해요.",
    funExplanation: "두 친구가 번갈아 일하는 모습이라고 생각하세요. 한 명이 일할 때 다른 한 명은 쉬는 거예요. 두 가지 경우를 더하면 전체 일이 완성돼요.",
    memoryTip: "곱미분은 앞미분뒤 더하기 앞뒤미분으로 외우세요.",
    useWhen: "두 함수가 곱해지거나 나누어진 식의 순간 변화율을 구할 때 써요.",
    commonMistakes: ["곱을 각각 미분해서 곱하면 안 돼요.", "몫의 미분에서는 분모를 제곱하는 것을 잊지 마세요."],
    example: { question: "f(x) = x² × x³을 곱의 미분으로 계산하세요.", steps: ["앞 x²을 미분하면 2x가 되고 뒤 x³을 그대로 두세요.", "앞 x²은 그대로 두고 뒤를 미분하면 3x²이 돼요.", "2x × x³ + x² × 3x² = 5x⁴이 돼요."], answer: "5x⁴" },
    quickCheck: { question: "f(x) = x × x²를 곱의 미분으로 계산하면?", answer: "3x²" },
    relatedFormulaIds: ["hi_power_rule", "hi_chain_rule"]
  },
  {
    id: "hi_chain_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "🔗",
    unit: "미분",
    title: "합성함수의 미분",
    formula: "겉미분 × 속미분으로 계산해요",
    latex: "\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx}",
    shortDescription: "겹쳐진 함수는 겉을 미분하고 속을 미분해서 곱해요.",
    easyExplanation: "함수 안에 함수가 들어 있으면 바깥쪽부터 차례로 벗기듯이 미분해요. 먼저 겉모습을 미분하고 그다음 속모습을 미분해서 곱하시면 돼요. 양파 껍질을 하나씩 벗긴다고 생각하면 쉬워요.",
    funExplanation: "선물 상자 속 상자를 여는 모습과 같아요. 겉상자를 열고 속상자를 열어야 선물이 나와요. 두 미분을 곱해야 진짜 답이 완성돼요.",
    memoryTip: "겹친 미분은 겉미분 곱하기 속미분이에요.",
    useWhen: "제곱 안에 식이 들어 있는 것처럼 겹쳐진 함수를 미분할 때 써요.",
    commonMistakes: ["속을 미분하지 않고 겉만 미분하고 끝내지 마세요.", "겉과 속을 구분할 때 어디까지가 속인지 먼저 표시하세요."],
    example: { question: "y = (x + 2)²을 미분하세요.", steps: ["겉모습을 미분하면 2(x + 2)가 돼요.", "속모습 x + 2를 미분하면 1이 돼요.", "두 결과를 곱하면 2x + 4가 돼요."], answer: "2x + 4" },
    quickCheck: { question: "y = (3x + 1)²을 미분하면?", answer: "18x + 6" },
    relatedFormulaIds: ["hi_power_rule", "hi_product_rule"]
  },
  {
    id: "hi_tangent",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "📏",
    unit: "미분",
    title: "접선의 방정식",
    formula: "y - y1 = 순간 기울기 × (x - a)",
    latex: "y - f(a) = f^{\\prime}(a)(x-a)",
    shortDescription: "그래프에 살짝 닿는 직선의 식을 미분계수로 구해요.",
    easyExplanation: "접선은 그래프 위의 한 점에 살짝 닿는 직선이에요. 이때 직선의 기울기는 그 점에서의 순간 기울기와 같아요. 점을 하나 알고 기울기를 알면 직선의 식을 바로 쓸 수 있어요.",
    funExplanation: "미끄럼틀에 길게 댄 자를 떠올려 보세요. 닿는 점에서 자의 기울기가 바로 미분계수예요. 그 기울기로 쭉 뻗은 직선이 접선이에요.",
    memoryTip: "접선 기울기는 미분계수, 점과 기울기로 식을 세우세요.",
    useWhen: "그래프 위의 한 점에서의 접하는 직선이 필요할 때 써요.",
    commonMistakes: ["접하는 점의 좌표를 식에 바르게 넣으세요.", "기울기는 원래 함수가 아니라 미분한 값으로 구하세요."],
    example: { question: "y = x² 위의 점 (1, 1)에서의 접선을 구하세요.", steps: ["y를 미분하면 2x가 되므로 기울기는 2예요.", "점 (1, 1)과 기울기 2를 직선 식에 넣으세요.", "정리하면 y = 2x - 1이 돼요."], answer: "y = 2x - 1" },
    quickCheck: { question: "y = x² 위의 점 (2, 4)에서의 접선의 기울기는?", answer: "4" },
    relatedFormulaIds: ["hi_derivative", "hi_extrema"]
  },
  {
    id: "hi_extrema",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    emoji: "⛰️",
    unit: "미분",
    title: "증가·감소와 극대·극소",
    formula: "순간 기울기 부호가 바뀌는 곳이 꼭대기와 밑바닥이에요",
    latex: "f^{\\prime}(x) = 0",
    shortDescription: "그래프가 올라갔다 내려가는 꼭대기와 밑바닥을 미분으로 찾아요.",
    easyExplanation: "순간 기울기가 양수이면 그래프는 올라가고 음수이면 내려가요. 올라가다가 내려가면 그곳이 산꼭대기처럼 가장 높은 극대예요. 내려가다가 올라가면 골짜기처럼 가장 낮은 극소가 돼요.",
    funExplanation: "등산 지도를 떠올려 보세요. 오르막이 내리막으로 바뀌는 곳이 정상이에요. 미분 부호표는 등산 코스 안내판과 같아요.",
    memoryTip: "오르막 내리막이 바뀌는 곳이 극대와 극소예요.",
    useWhen: "그래프의 가장 높은 곳과 가장 낮은 곳을 찾을 때 써요.",
    commonMistakes: ["순간 기울기가 0이라고 해서 모두 극값은 아니에요.", "부호가 바뀌는지 표를 그려서 꼭 확인하세요."],
    example: { question: "y = x²의 극값을 구하세요.", steps: ["미분하면 2x이므로 2x = 0에서 x = 0을 얻으세요.", "0보다 작으면 기울기가 음수이고 크면 양수예요.", "내려가다 올라가므로 x = 0에서 극소 0이 돼요."], answer: "x = 0에서 극소 0" },
    quickCheck: { question: "y = -x²의 그래프는 x = 0에서 극대인가요 극소인가요?", answer: "극대" },
    relatedFormulaIds: ["hi_derivative", "hi_def_integral"]
  },
  {
    id: "hi_indef_integral",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "calculus",
    emoji: "🔄",
    unit: "적분",
    title: "부정적분",
    formula: "미분의 거꾸로 + C를 붙여요",
    latex: "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C",
    shortDescription: "미분하기 전의 원래 함수를 되찾고 적분 상수를 붙이는 계산이에요.",
    easyExplanation: "부정적분은 미분을 거꾸로 되돌리는 계산이에요. 조각들을 모아서 전체 모습을 되찾는다고 생각하시면 돼요. 미분하면 사라지는 상수가 있어서 마지막에 + C를 꼭 붙여요.",
    funExplanation: "영상을 되감기하는 것과 같아요. 미분으로 앞으로 갔다면 적분으로 뒤로 돌아오는 거예요. + C는 되감기할 때 생기는 작은 덤이라고 외우세요.",
    memoryTip: "적분은 미분의 거꾸로, + C를 잊지 마세요.",
    useWhen: "순간 변화율 식에서 원래의 전체 식을 되찾을 때 써요.",
    commonMistakes: ["마지막에 + C를 빼먹지 마세요.", "지수를 하나 올리고 그 수로 나누는 순서를 지키세요."],
    example: { question: "2x를 부정적분하세요.", steps: ["2x의 지수는 1이므로 지수를 하나 올려 x² 모양을 만드세요.", "올린 지수 2로 나누면 x²이 돼요.", "상수를 생각해서 + C를 붙이면 x² + C가 돼요."], answer: "x² + C" },
    quickCheck: { question: "3x²을 부정적분하면?", answer: "x³ + C" },
    relatedFormulaIds: ["hi_power_rule", "hi_def_integral"]
  },
  {
    id: "hi_def_integral",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "calculus",
    emoji: "🧱",
    unit: "적분",
    title: "정적분과 넓이",
    formula: "작은 조각을 모아 전체 넓이를 구해요",
    latex: "\\int_{a}^{b} f(x) dx",
    shortDescription: "그래프 아래의 작은 조각들을 모두 모아 넓이를 구하는 계산이에요.",
    easyExplanation: "정적분은 그래프 아래 부분을 잘게 나누어 모으는 계산이에요. 작은 조각을 모아서 전체 넓이를 구한다고 생각하시면 돼요. 원래 함수를 찾은 뒤 끝값과 시작값을 빼서 계산해요.",
    funExplanation: "레고 벽돌을 차곡차곡 쌓는 모습과 같아요. 얇은 벽돌 하나하나를 모으면 커다란 넓이가 완성돼요. 적분 기호는 벽돌을 모아 담는 상자예요.",
    memoryTip: "정적분은 조각 모아 넓이, 끝값에서 시작값을 빼세요.",
    useWhen: "그래프와 가로축 사이의 넓이를 구하고 싶을 때 써요.",
    commonMistakes: ["위끝값과 아래끝값의 순서를 바꾸지 마세요.", "넓이가 음수로 나오면 구간을 나누어 양수로 고치세요."],
    example: { question: "0부터 2까지 y = x의 넓이를 구하세요.", steps: ["y = x의 원래 함수는 x²의 절반이에요.", "끝값 2를 넣으면 2가 되고 시작값 0을 넣으면 0이 돼요.", "2 - 0 = 2이므로 넓이는 2가 돼요."], answer: "2" },
    quickCheck: { question: "0부터 1까지 y = x의 넓이는?", answer: "2분의 1" },
    relatedFormulaIds: ["hi_indef_integral", "hi_extrema"]
  },
  {
    id: "hi_permutation",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "combinatorics",
    emoji: "🏃",
    unit: "경우의 수",
    title: "순열",
    formula: "nPr = n×(n−1)×…×(n−r+1)",
    latex: "{}_n P_r = \\frac{n!}{(n-r)!}",
    shortDescription: "n개 중에서 r개를 순서 있게 뽑는 경우의 수예요.",
    easyExplanation: "순열은 순서가 중요할 때 쓰는 줄 세우기예요. 5명 중 1등과 2등을 뽑으면 5 × 4 = 20가지가 나와요. 누가 먼저냐에 따라 다른 경우로 세기 때문에 곱하면서 내려가요.",
    funExplanation: "줄 세우기라고 생각하면 쉬워요. 누가 회장이냐에 따라 다른 경우예요. 자리가 바뀌면 완전히 새로운 경우로 쳐주세요.",
    memoryTip: "순열은 줄 세우기, 순서가 중요하면 순열이에요.",
    useWhen: "순위와 자리 배치처럼 순서가 중요한 경우를 셀 때 써요.",
    commonMistakes: ["순서가 결과에 영향을 주는지 먼저 확인하세요.", "n은 전체 개수이고 r은 뽑는 개수예요."],
    example: { question: "5명 중 회장, 부회장, 총무를 뽑는 경우는?", steps: ["순서가 중요하므로 순열을 쓰세요.", "5 × 4 × 3으로 차례로 곱하세요.", "계산하면 60가지가 나와요."], answer: "60" },
    quickCheck: { question: "4명 중 1등과 2등을 뽑는 경우는?", answer: "12" },
    relatedFormulaIds: ["hi_combination", "hi_binomial_thm"]
  },
  {
    id: "hi_combination",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "combinatorics",
    emoji: "👥",
    unit: "경우의 수",
    title: "조합",
    formula: "nCr = n! ÷ (r! × (n−r)!)",
    latex: "{}_n C_r = \\frac{n!}{r!(n-r)!}",
    shortDescription: "n개 중에서 r개를 순서 없이 뽑는 경우의 수예요.",
    easyExplanation: "조합은 순서가 무관할 때 쓰는 팀 짜기예요. 누구와 같은 팀이냐만 중요하고 순서는 따지지 않아요. 순열에서 순서가 바뀐 중복을 나누어 없애면 조합이 돼요.",
    funExplanation: "친구들과 팀을 짜는 모습을 떠올려 보세요. 먼저 뽑히든 나중에 뽑히든 같은 팀이면 같은 경우예요. 순서 따지지 말고 사이좋게 묶어주세요.",
    memoryTip: "조합은 팀 짜기, 순서가 무관하면 조합이에요.",
    useWhen: "대표 선발이나 팀 나누기처럼 순서가 무관한 뽑기를 셀 때 써요.",
    commonMistakes: ["순서가 무관한지 먼저 판단하세요.", "순열을 구한 뒤 r의 차례곱으로 나누는 것을 잊지 마세요."],
    example: { question: "5명 중 청소 당번 2명을 뽑는 경우는?", steps: ["순서가 무관하므로 조합을 쓰세요.", "5 × 4 ÷ 2로 계산하세요.", "답은 10가지가 나와요."], answer: "10" },
    quickCheck: { question: "4명 중 2명을 뽑는 경우는?", answer: "6" },
    relatedFormulaIds: ["hi_permutation", "hi_binomial_thm"]
  },
  {
    id: "hi_binomial_thm",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "combinatorics",
    emoji: "🧮",
    unit: "경우의 수",
    title: "이항정리",
    formula: "(a+b)ⁿ을 조합으로 펼쳐요",
    latex: "(a+b)^n = \\sum_{k=0}^{n} {}_n C_k a^{n-k} b^k",
    shortDescription: "괄호의 거듭제곱을 조합을 이용해 한 항씩 펼치는 방법이에요.",
    easyExplanation: "이항정리는 (a+b)ⁿ을 펼칠 때 쓰는 약속이에요. 각 항의 계수는 몇 개를 고르는지 세는 조합으로 정해져요. 지수가 줄어들고 늘어나는 모양을 따라가면 전체 전개를 완성할 수 있어요.",
    funExplanation: "접었다 펼치는 종이학 같아요. 거듭제곱으로 접힌 식을 조합이라는 손으로 펼치는 거예요. 계수가 파스칼 삼각형 모양으로 나타나는 것이 재미있어요.",
    memoryTip: "괄호 제곱 펼치기는 조합 계수로 외우세요.",
    useWhen: "거듭제곱으로 된 괄호를 펼쳐서 특정 항을 찾을 때 써요.",
    commonMistakes: ["a의 지수와 b의 지수의 합이 n이 되어야 해요.", "계수에 조합을 곱하는 것을 잊지 마세요."],
    example: { question: "(a+b)²을 펼쳐 보세요.", steps: ["n = 2이므로 조합 2C0, 2C1, 2C2를 쓰세요.", "a² + 2ab + b² 모양으로 펼치세요.", "계수는 1, 2, 1이 돼요."], answer: "a² + 2ab + b²" },
    quickCheck: { question: "(a+b)³에서 a²b의 계수는?", answer: "3" },
    relatedFormulaIds: ["hi_permutation", "hi_combination"]
  },
  {
    id: "hi_stars_bars",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    emoji: "🍬",
    unit: "경우의 수",
    title: "중복조합·나누어주기",
    formula: "nHr = n+r−1Cr로 세요",
    latex: "{}_n H_r = {}_{n+r-1} C_r",
    shortDescription: "같은 종류를 여러 번 골라도 되는 뽑기와 나누어주기를 세는 방법이에요.",
    easyExplanation: "중복조합은 같은 맛 사탕을 여러 개 골라도 될 때 써요. 칸막이를 세워서 어느 종류를 몇 개 고를지 표시하면 조합 문제로 바뀌어요. 나누어주기 문제도 막대와 칸막이 그림으로 바꾸면 쉽게 풀려요.",
    funExplanation: "사탕 가게에서 종류별로 담는 모습을 떠올려 보세요. 같은 맛을 몇 개씩 담아도 괜찮아요. 칸막이로 가게 진열장을 나눈다고 상상하면 공식이 외워져요.",
    memoryTip: "겹쳐 뽑기는 칸막이 세우기, 하나씩 먼저 주고 시작하세요.",
    useWhen: "같은 것을 중복해서 고르거나 물건을 상자에 나누어 담을 때 써요.",
    commonMistakes: ["중복이 되는지 조건을 먼저 확인하세요.", "0개를 받는 경우를 허용하는지 살펴보세요."],
    example: { question: "딸기, 포도, 사과 사탕에서 4개를 중복해서 고르면?", steps: ["종류가 3가지이고 4개를 고르므로 중복조합을 쓰세요.", "3H4 = 6C4로 바꾸어 계산하세요.", "계산하면 15가지가 나와요."], answer: "15" },
    quickCheck: { question: "2종류에서 3개를 중복해서 고르면?", answer: "4" },
    relatedFormulaIds: ["hi_combination", "hi_permutation"]
  },
  {
    id: "hi_binom_prob",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "statistics",
    emoji: "🎲",
    unit: "확률",
    title: "독립시행의 확률",
    formula: "nCk × pᵏ × qⁿ⁻ᵏ로 계산해요",
    latex: "P(X=k) = {}_n C_k p^k q^{n-k}",
    shortDescription: "같은 실험을 여러 번 되풀이할 때 원하는 횟수만큼 성공할 확률이에요.",
    easyExplanation: "독립시행은 동전 던지기처럼 앞의 결과가 뒤에 영향을 주지 않는 실험이에요. 성공할 자리 k개를 고르고 성공 확률과 실패 확률을 곱해서 계산해요. 조합으로 자리를 고르는 것이 핵심이에요.",
    funExplanation: "주사위를 여러 번 던지는 게임이라고 생각하세요. 몇 번 성공할지는 운과 경우의 수가 함께 정해요. 자리를 고르고 확률을 곱하면 답이 나와요.",
    memoryTip: "되풀이 확률은 자리 고르기 곱하기 성공 곱하기 실패예요.",
    useWhen: "같은 실험을 여러 번 되풀이해서 성공 횟수의 확률을 구할 때 써요.",
    commonMistakes: ["성공과 실패의 확률의 합이 1인지 확인하세요.", "독립이 아닐 때는 이 식을 쓰면 안 돼요."],
    example: { question: "동전을 3번 던져 앞면이 2번 나올 확률은?", steps: ["자리 고르기 3C2 = 3을 구하세요.", "앞면 확률의 제곱과 뒷면 확률을 곱하세요.", "3 × 8분의 1 = 8분의 3이 돼요."], answer: "8분의 3" },
    quickCheck: { question: "동전을 2번 던져 앞면이 1번 나올 확률은?", answer: "2분의 1" },
    relatedFormulaIds: ["hi_combination", "hi_binom_dist"]
  },
  {
    id: "hi_vector_add",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    emoji: "➡️",
    unit: "벡터",
    title: "벡터의 합과 실수배",
    formula: "화살표 이어붙이기와 늘이기 줄이기예요",
    latex: "\\vec{a} + \\vec{b} = (a_1+b_1, a_2+b_2)",
    shortDescription: "크기와 방향을 가진 화살표를 이어붙이고 늘리는 계산이에요.",
    easyExplanation: "벡터는 크기와 방향을 함께 가진 화살표예요. 덧셈은 화살표의 꼬리와 머리를 이어붙여서 구해요. 실수배는 화살표를 늘리거나 줄이고 방향을 뒤집을 수 있어요.",
    funExplanation: "친구 손을 잡고 이어가는 기차놀이라고 생각하세요. 화살표들을 꼬리에 꼬리를 물고 이으면 도착점이 합이 돼요. 몇 배를 하면 기차가 길어지거나 짧아져요.",
    memoryTip: "벡터 덧셈은 화살표 이어붙이기, 실수배는 늘이기예요.",
    useWhen: "힘과 이동처럼 방향이 있는 양을 합칠 때 써요.",
    commonMistakes: ["방향을 무시하고 크기만 더하지 마세요.", "뺄셈은 반대 방향 화살표를 더하는 것과 같아요."],
    example: { question: "벡터 (1, 2)와 (3, 1)을 더하세요.", steps: ["x좌표끼리 더하면 1 + 3 = 4가 돼요.", "y좌표끼리 더하면 2 + 1 = 3이 돼요.", "그래서 합은 (4, 3)이 돼요."], answer: "(4, 3)" },
    quickCheck: { question: "벡터 (2, 1)의 3배는?", answer: "(6, 3)" },
    relatedFormulaIds: ["hi_inner_product", "hi_position_vector"]
  },
  {
    id: "hi_inner_product",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    emoji: "🎯",
    unit: "벡터",
    title: "벡터의 내적",
    formula: "크기곱 × cos로 계산해요",
    latex: "\\vec{a} \\cdot \\vec{b} = |\\vec{a}||\\vec{b}| \\cos \\theta",
    shortDescription: "두 화살표가 같은 방향을 얼마나 향하는지 숫자로 나타내는 계산이에요.",
    easyExplanation: "내적은 두 벡터가 서로를 얼마나 밀어주는지 재는 값이에요. 각 벡터는 크기와 방향을 가진 화살표라고 생각하시면 돼요. 사이각이 작을수록 값이 커지고 직각이면 0이 돼요.",
    funExplanation: "두 친구가 같은 방향을 보는지 확인하는 것과 같아요. 나란히 보면 점수가 높고 엇갈리면 점수가 낮아져요. 직각으로 서 있으면 점수가 0점이 돼요.",
    memoryTip: "내적은 크기곱 코사인, 직각이면 0이에요.",
    useWhen: "두 방향이 이루는 각이나 수직인지 알고 싶을 때 써요.",
    commonMistakes: ["내적의 답은 벡터가 아니라 숫자예요.", "각도는 두 화살표의 시작점을 모아서 재세요."],
    example: { question: "(1, 0)과 (0, 1)의 내적을 구하세요.", steps: ["x좌표끼리 곱하면 1 × 0 = 0이 돼요.", "y좌표끼리 곱하면 0 × 1 = 0이 돼요.", "두 값을 더하면 0이 돼요."], answer: "0" },
    quickCheck: { question: "(1, 2)와 (3, 1)의 내적은?", answer: "5" },
    relatedFormulaIds: ["hi_vector_add", "hi_position_vector"]
  },
  {
    id: "hi_position_vector",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    emoji: "📍",
    unit: "벡터",
    title: "위치벡터와 내분점",
    formula: "나누는 점 = (n×앞 + m×뒤) ÷ (m+n)",
    latex: "\\vec{p} = \\frac{n \\vec{a} + m \\vec{b}}{m+n}",
    shortDescription: "기준점에서 잰 화살표로 나누는 점의 위치를 찾는 방법이에요.",
    easyExplanation: "위치벡터는 기준점에서 목표까지 그은 화살표예요. 선분을 m 대 n으로 나누는 점은 양쪽 끝점에 가중치를 주어 구해요. 가까운 쪽의 끝점에 더 큰 가중치가 간다고 기억하세요.",
    funExplanation: "지도 위에 핀을 꽂는 모습과 같아요. 기준점에서 얼마나 떨어졌는지 화살표로 표시하는 거예요. 나누는 점은 줄다리기에서 더 센 쪽으로 끌려간 위치예요.",
    memoryTip: "내분점은 반대쪽 가중치를 곱해서 나누세요.",
    useWhen: "선분을 일정한 비율로 나누는 점의 좌표가 필요할 때 써요.",
    commonMistakes: ["m과 n의 순서를 바꾸지 마세요.", "외분점에서는 가운데 부호가 빼기가 돼요."],
    example: { question: "A(0, 0)과 B(6, 0)을 1 대 2로 나누는 내분점은?", steps: ["가중치를 반대로 곱하면 (2 × 0 + 1 × 6)이 돼요.", "합 3으로 나누면 x좌표는 2가 돼요.", "y좌표는 0이므로 점은 (2, 0)이 돼요."], answer: "(2, 0)" },
    quickCheck: { question: "A(0, 0)과 B(4, 0)의 중점은?", answer: "(2, 0)" },
    relatedFormulaIds: ["hi_vector_add", "hi_inner_product"]
  },
  {
    id: "hi_normal_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    emoji: "🔔",
    unit: "통계",
    title: "정규분포",
    formula: "종 모양으로 가운데에 모여요",
    latex: "X \\sim N(m, \\sigma^2)",
    shortDescription: "키와 점수처럼 가운데에 많이 모이는 종 모양 분포예요.",
    easyExplanation: "정규분포는 평균을 중심으로 좌우가 같은 종 모양을 그려요. 가운데에 자료가 많이 모이고 멀어질수록 적어져요. 표준화를 해서 표로 확률을 구할 수 있어요.",
    funExplanation: "종을 엎어 놓은 모습이라고 생각하세요. 가운데가 볼록하고 양쪽이 낮게 퍼져 있어요. 대부분의 친구들이 평균 근처에 모여 있는 모습과 같아요.",
    memoryTip: "정규분포는 종 모양, 표준화로 표를 보세요.",
    useWhen: "키나 점수처럼 평균 근처에 모이는 자료를 다룰 때 써요.",
    commonMistakes: ["표준편차와 분산을 섞지 마세요.", "표준화할 때 평균을 빼고 표준편차로 나누세요."],
    example: { question: "평균 60점, 표준편차 10점일 때 70점의 표준점수는?", steps: ["점수에서 평균을 빼면 70 - 60 = 10이 돼요.", "표준편차 10으로 나누면 1이 돼요.", "그래서 표준점수는 1이 돼요."], answer: "1" },
    quickCheck: { question: "평균 50, 표준편차 5일 때 60의 표준점수는?", answer: "2" },
    relatedFormulaIds: ["hi_binom_dist", "hi_estimation"]
  },
  {
    id: "hi_binom_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    emoji: "🎲",
    unit: "통계",
    title: "이항분포",
    formula: "성공 횟수가 어떻게 흩어지는지 봐요",
    latex: "X \\sim B(n, p)",
    shortDescription: "같은 실험을 여러 번 할 때 성공 횟수가 퍼지는 모양이에요.",
    easyExplanation: "이항분포는 성공과 실패만 있는 실험을 여러 번 되풀이한 결과예요. 성공 횟수가 몇 번 정도에서 많이 나오는지 보여줘요. 평균은 전체 횟수에 성공 확률을 곱해서 구해요.",
    funExplanation: "동전 던지기 대회를 떠올려 보세요. 열 번 던지면 앞면이 다섯 번 근처에서 자주 나와요. 그런 흩어짐을 정리한 표가 이항분포예요.",
    memoryTip: "이항분포 평균은 횟수 곱하기 성공 확률이에요.",
    useWhen: "성공 횟수의 평균과 흩어짐을 구하고 싶을 때 써요.",
    commonMistakes: ["매번 성공 확률이 같은지 먼저 확인하세요.", "평균과 분산 식을 서로 바꾸지 마세요."],
    example: { question: "동전을 10번 던질 때 앞면 횟수의 평균은?", steps: ["전체 횟수 10을 확인하세요.", "앞면 확률은 2분의 1이에요.", "10 × 2분의 1 = 5이므로 평균은 5예요."], answer: "5" },
    quickCheck: { question: "주사위로 12번 던져 1이 나올 횟수의 평균은?", answer: "2" },
    relatedFormulaIds: ["hi_binom_prob", "hi_normal_dist"]
  },
  {
    id: "hi_estimation",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    emoji: "🔍",
    unit: "통계",
    title: "표본과 추정",
    formula: "일부를 보고 전체를 짐작해요",
    latex: "\\bar{x} - 1.96 \\frac{\\sigma}{\\sqrt{n}} \\le m \\le \\bar{x} + 1.96 \\frac{\\sigma}{\\sqrt{n}}",
    shortDescription: "일부 자료로 전체 평균이 있을 범위를 짐작하는 방법이에요.",
    easyExplanation: "표본은 전체 중에서 뽑은 일부를 말해요. 일부의 평균으로 전체의 평균이 어디쯤 있을지 범위로 짐작할 수 있어요. 뽑은 개수가 많을수록 범위가 좁아져서 더 정확해져요.",
    funExplanation: "국 한 숟가락으로 간을 보는 것과 같아요. 한 숟가락 맛으로 냄비 전체의 맛을 짐작하는 거예요. 많이 떠서 맛볼수록 짐작이 정확해져요.",
    memoryTip: "표본은 일부 맛보기, 개수가 많을수록 정확해요.",
    useWhen: "전체를 다 조사하기 어려워서 일부로 전체를 짐작할 때 써요.",
    commonMistakes: ["표본은 골고루 뽑아야 해요.", "신뢰도가 높아지면 구간이 넓어져요."],
    example: { question: "30명을 뽑아 평균 키가 170cm일 때 전체 평균을 어떻게 말하나요?", steps: ["뽑은 30명의 평균 170cm를 기준점으로 삼으세요.", "자료가 흩어진 정도로 오차 범위를 계산하세요.", "전체 평균은 170cm 근처 범위에 있다고 말해요."], answer: "170cm 근처" },
    quickCheck: { question: "표본의 크기가 커지면 추정 구간은 어떻게 되나요?", answer: "좁아져요" },
    relatedFormulaIds: ["hi_normal_dist", "hi_binom_dist"]
  },
  {
    id: "hi_exp_func",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "function",
    emoji: "📈",
    unit: "함수",
    title: "지수함수와 로그함수",
    formula: "y = aˣ와 y = log x는 거꾸로 관계예요",
    latex: "y = a^x, y = \\log_a x",
    shortDescription: "빠르게 커지는 함수와 그 거꾸로 관계인 함수를 함께 배워요.",
    easyExplanation: "지수함수는 지수 자리에 x가 있어서 아주 빠르게 커지거나 작아져요. 로그함수는 지수함수의 거꾸로 관계라서 그래프가 직선 y = x에 대칭이에요. 하나를 알면 다른 하나도 자연스럽게 이해할 수 있어요.",
    funExplanation: "올라가는 엘리베이터와 내려오는 엘리베이터 같아요. 서로 반대 방향이지만 같은 건물을 오가요. 그래프를 접으면 정확히 겹쳐지는 모습이 재미있어요.",
    memoryTip: "지수와 로그는 거꾸로 짝꿍, 그래프는 대칭이에요.",
    useWhen: "빠르게 불어나는 양이나 그 반대 계산이 필요할 때 써요.",
    commonMistakes: ["밑의 범위를 먼저 확인하세요.", "진수는 항상 양수여야 해요."],
    example: { question: "2³ = 8을 로그로 바꾸면?", steps: ["밑인 2를 로그의 밑으로 쓰세요.", "결과인 8을 진수 자리에 쓰세요.", "지수는 3이므로 log₂8 = 3이 돼요."], answer: "3" },
    quickCheck: { question: "10² = 100을 로그로 바꾸면?", answer: "2" },
    relatedFormulaIds: ["hi_amgm"]
  },
  {
    id: "hi_amgm",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    emoji: "⚖️",
    unit: "부등식",
    title: "산술·기하평균",
    formula: "(a+b) ÷ 2 ≥ √ab로 비교해요",
    latex: "\\frac{a+b}{2} \\ge \\sqrt{ab}",
    shortDescription: "두 수의 평균을 비교해서 가장 작아지는 때를 찾는 부등식이에요.",
    easyExplanation: "산술평균은 두 수를 더해서 반으로 나눈 값이에요. 기하평균은 두 수를 곱해서 제곱근을 씌운 값이에요. 산술평균이 항상 기하평균보다 크거나 같고 두 수가 같을 때 같아져요.",
    funExplanation: "저울의 양쪽을 비교한다고 생각하세요. 왼쪽 접시가 항상 오른쪽보다 무겁거나 같아요. 양쪽 무게가 같아지는 순간이 가장 균형 잡힌 때예요.",
    memoryTip: "더해서 반이 곱해서 루트보다 크거나 같아요.",
    useWhen: "합이 정해졌을 때 곱의 가장 큰 값을 찾을 때 써요.",
    commonMistakes: ["두 수가 양수일 때만 쓸 수 있어요.", "같아지는 때가 언제인지 꼭 함께 답하세요."],
    example: { question: "합이 10인 두 양수의 곱의 가장 큰 값은?", steps: ["두 수를 a와 b라고 하고 a + b = 10으로 두세요.", "곱 ab는 5의 제곱보다 작거나 같아요.", "두 수가 모두 5일 때 가장 커서 25가 돼요."], answer: "25" },
    quickCheck: { question: "합이 8인 두 양수의 곱의 가장 큰 값은?", answer: "16" },
    relatedFormulaIds: ["hi_exp_func"]
  }
];
