/* ============================================================
   수학아 놀자 (math) - 중등 공식 35개 (formula-mi.js)
   formula-data.js 가 합쳐서 window.MathFormulaData 로 만듭니다.
   ============================================================ */
window.MathFormulaMi = [
  {
    id: "mi_signed_add",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "➕",
    unit: "정수",
    title: "부호가 있는 수의 덧셈",
    formula: "부호가 같으면 더하고 부호 유지, 부호가 다르면 빼고 큰 수 부호 따르기",
    latex: "(+5) + (-8) = -3",
    shortDescription: "플러스와 마이너스가 섞인 덧셈을 승자 정하듯이 계산하는 방법이에요.",
    easyExplanation: "부호가 같으면 두 수를 더하고 그 부호를 그대로 붙이면 돼요. 부호가 다르면 큰 수에서 작은 수를 빼고 큰 수의 부호를 붙이면 돼요.",
    funExplanation: "줄다리기에서 오른쪽 팀이 5명이고 왼쪽 팀이 8명이면 왼쪽이 3명만큼 이겨요. 그래서 (+5)와 (−8)의 대결은 −3의 승리로 끝나요.",
    memoryTip: "같으면 더하고 붙이고, 다르면 빼고 큰 쪽으로.",
    useWhen: "플러스와 마이너스가 섞인 덧셈을 계산해야 할 때 써요.",
    commonMistakes: ["부호가 다른데도 그냥 더하는 실수가 많아요.", "답에 작은 수의 부호를 붙이는 실수가 많아요."],
    example: { question: "(+7) + (−4)의 값은?", steps: ["두 수의 부호가 다른지 확인해요.", "7 − 4 = 3으로 빼서 계산해요.", "큰 수 7이 플러스이므로 답은 3이에요."], answer: "3" },
    quickCheck: { question: "(−6) + (+2)의 값은?", answer: "−4" },
    relatedFormulaIds: ["mi_signed_mul"]
  },
  {
    id: "mi_signed_mul",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "✖️",
    unit: "정수",
    title: "부호가 있는 수의 곱셈",
    formula: "같은 부호끼리는 플러스, 다른 부호끼리는 마이너스",
    latex: "(+2) \\times (-3) = -6",
    shortDescription: "곱셈에서 부호를 먼저 정하고 숫자만 곱하는 규칙이에요.",
    easyExplanation: "먼저 부호 짝을 살펴보고 같으면 플러스, 다르면 마이너스로 정해요. 그 다음에는 숫자끼리만 곱해서 답을 완성하면 돼요.",
    funExplanation: "자판기에서 같은 색 버튼 두 개를 누르면 선물 상자가 열리고 다른 색이면 빈 상자가 나와요. 부호 곱셈도 짝이 같으면 플러스가 나와요.",
    memoryTip: "부호짝 맞추기, 같으면 플러스 다르면 마이너스.",
    useWhen: "음수가 들어간 곱셈이나 나눗셈의 부호를 정해야 할 때 써요.",
    commonMistakes: ["숫자는 맞히고 부호를 반대로 적는 실수가 많아요.", "마이너스 세 개를 곱할 때 부호를 헷갈려요."],
    example: { question: "(−4) × (+3)의 값은?", steps: ["부호가 다르므로 답의 부호는 마이너스예요.", "숫자끼리 4 × 3 = 12로 계산해요.", "부호를 붙이면 답은 −12예요."], answer: "−12" },
    quickCheck: { question: "(−5) × (−2)의 값은?", answer: "10" },
    relatedFormulaIds: ["mi_signed_add"]
  },
  {
    id: "mi_expression",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "🔤",
    unit: "문자와 식",
    title: "문자를 사용한 식",
    formula: "수 × 문자에서 곱하기 기호를 생략하고 수를 앞에 쓰기",
    latex: "3 \\times x = 3x",
    shortDescription: "딱딱한 곱하기 기호를 줄이고 문자로 수를 간단히 나타내는 방법이에요.",
    easyExplanation: "수와 문자의 곱에서는 곱하기 기호를 생략하고 수를 앞에 써요. 1과 −1은 숫자 1을 생략하고 부호와 문자만 남기면 돼요.",
    funExplanation: "자판기에서 긴 문장을 줄임 버튼으로 바꾸면 3 × x가 3x로 짧아져요. 기호를 덜어낼수록 식이 가벼워져서 읽기 편해져요.",
    memoryTip: "곱하기는 숨기고 수는 앞에, 1은 슬쩍 빼기.",
    useWhen: "말로 된 수량 관계를 문자를 써서 짧은 식으로 바꿀 때 써요.",
    commonMistakes: ["x × 3처럼 문자를 앞에 쓰는 실수가 많아요.", "x ÷ 3을 3분의 x 모양으로 바꾸지 않고 그대로 둬요."],
    example: { question: "한 개에 500원인 빵 x개의 가격을 식으로 나타내면?", steps: ["가격은 500 × x로 시작해요.", "곱하기 기호를 생략하면 500x가 돼요.", "단위를 붙이면 500x원이 답이에요."], answer: "500x원" },
    quickCheck: { question: "y를 4로 나눈 식을 간단히 나타내면?", answer: "4분의 y" },
    relatedFormulaIds: ["mi_like_terms", "mi_linear_eq"]
  },
  {
    id: "mi_like_terms",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "🧹",
    unit: "문자와 식",
    title: "동류항 정리",
    formula: "문자와 차수가 같은 항끼리 모아서 계수만 더하고 빼기",
    latex: "3x + 5x = 8x",
    shortDescription: "같은 종류의 문자끼리 모아주는 청소 같은 정리 방법이에요.",
    easyExplanation: "동류항은 문자와 차수가 똑같은 항을 말해요. 그런 항끼리 모은 뒤에는 숫자 부분인 계수만 더하거나 빼면 돼요.",
    funExplanation: "저울 위에 사과 상자 3개와 사과 상자 5개가 따로 있으면 합쳐서 8개로 정리해요. 사과와 귤처럼 종류가 다르면 합칠 수 없어요.",
    memoryTip: "같은 문자끼리 청소, 숫자는 더하고 문자는 두기.",
    useWhen: "길게 흩어진 식을 짧고 간단하게 정리하고 싶을 때 써요.",
    commonMistakes: ["3x와 5y처럼 다른 문자를 더해서 8xy로 만드는 실수가 많아요.", "3과 x처럼 상수와 문자를 합치는 실수가 많아요."],
    example: { question: "5x + 2 + 3x − 2를 간단히 하면?", steps: ["5x와 3x가 동류항이므로 모아서 8x가 돼요.", "+2와 −2는 합쳐서 0이 돼요.", "남은 식을 정리하면 답은 8x예요."], answer: "8x" },
    quickCheck: { question: "7a − 2a + 4의 답은?", answer: "5a + 4" },
    relatedFormulaIds: ["mi_expression", "mi_factor_common"]
  },
  {
    id: "mi_linear_eq",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "⚖️",
    unit: "방정식",
    title: "일차방정식 풀기",
    formula: "이항: 더하기는 빼기로, 곱하기는 나누기로 넘기기",
    latex: "ax + b = 0 \\Rightarrow x = -\\frac{b}{a}",
    shortDescription: "모르는 수 x를 저울처럼 양쪽을 똑같이 조작해서 찾아내는 방법이에요.",
    easyExplanation: "방정식은 양쪽이 같은 저울이에요. x만 남기려면 양쪽에서 똑같이 더하거나 빼고, 곱하거나 나누면 돼요.",
    funExplanation: "저울의 한쪽에 선물 상자(x)와 3kg 추가 있고, 다른 쪽에 8kg이 있어요. 양쪽에서 3kg씩 덜어내면 x = 5가 돼요.",
    memoryTip: "이항은 반대로, 더하기는 빼기로 곱하기는 나누기로.",
    useWhen: "모르는 수가 들어간 식에서 그 값을 구해야 할 때 써요.",
    commonMistakes: ["이항할 때 부호를 안 바꾸는 실수가 가장 많아요.", "양변에 0을 곱하거나 나누면 안 돼요."],
    example: { question: "2x + 3 = 11일 때 x의 값은?", steps: ["+3을 넘기면 −3이 돼요.", "2x = 8로 정리돼요.", "양변을 2로 나누면 x = 4예요."], answer: "4" },
    quickCheck: { question: "3x − 5 = 10일 때 x의 값은?", answer: "5" },
    relatedFormulaIds: ["mi_transpose", "mi_expression"]
  },
  {
    id: "mi_eq_bracket",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    emoji: "📦",
    unit: "방정식",
    title: "괄호가 있는 방정식",
    formula: "분배법칙으로 괄호를 먼저 풀고 이항해서 풀기",
    latex: "2(x + 3) = 10 \\Rightarrow x + 3 = 5",
    shortDescription: "선물 상자 같은 괄호를 먼저 풀어서 평평한 식으로 만드는 방법이에요.",
    easyExplanation: "괄호 앞의 수를 괄호 안의 모든 항에 곱해서 괄호를 풀어줘요. 괄호가 사라지면 동류항을 정리하고 이항해서 x를 구하면 돼요.",
    funExplanation: "자판기에서 묶음 상자 2개가 각각 (x + 3) 구슬을 담고 있으면 상자를 열어야 세기 쉬워요. 상자를 열면 2x + 6 = 10이 돼요.",
    memoryTip: "괄호 앞 수 모두에게 곱하기, 하나도 빼먹지 않기.",
    useWhen: "괄호가 들어간 방정식을 풀어야 할 때 가장 먼저 써요.",
    commonMistakes: ["괄호 앞의 수를 첫 항에만 곱하고 둘째 항에 빼먹어요.", "마이너스 분배에서 부호를 반대로 바꿔요."],
    example: { question: "3(x − 2) = 9일 때 x의 값은?", steps: ["괄호를 풀면 3x − 6 = 9가 돼요.", "−6을 넘기면 3x = 15가 돼요.", "양변을 3으로 나누면 x = 5예요."], answer: "5" },
    quickCheck: { question: "2(x + 4) = 14일 때 x의 값은?", answer: "3" },
    relatedFormulaIds: ["mi_linear_eq", "mi_like_terms"]
  },
  {
    id: "mi_transpose",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    emoji: "🔀",
    unit: "식의 변형",
    title: "등식의 변형",
    formula: "이항으로 원하는 문자를 한쪽에 남기고 정리하기",
    latex: "ax + by + c = 0 \\Rightarrow y = -\\frac{a}{b}x - \\frac{c}{b}",
    shortDescription: "등식에서 보고 싶은 문자를 주인공으로 이사시키는 방법이에요.",
    easyExplanation: "구하려는 문자를 왼쪽에 남기고 나머지 항은 모두 오른쪽으로 넘겨요. 마지막에 그 문자의 앞 숫자로 양변을 나누면 변형이 끝나요.",
    funExplanation: "저울 위에 여러 인형이 섞여 있을 때 보고 싶은 인형만 한쪽 접시에 남겨요. 나머지를 반대쪽으로 옮기면 인형의 무게가 보여요.",
    memoryTip: "주인공 남기고 나머지는 이사, 앞 숫자로 나누기.",
    useWhen: "공식에서 특정 문자에 대해 정리해서 써야 할 때 활용돼요.",
    commonMistakes: ["이항하면서 부호를 바꾸지 않는 실수가 많아요.", "나누기를 마지막에 하지 않고 중간에 섞어서 틀려요."],
    example: { question: "2x + y = 10을 y에 대해 풀면?", steps: ["y를 왼쪽에 남기고 2x를 오른쪽으로 넘겨요.", "y = 10 − 2x 모양이 돼요.", "순서를 예쁘게 쓰면 y = −2x + 10이에요."], answer: "y = −2x + 10" },
    quickCheck: { question: "x + 3y = 9를 x에 대해 풀면?", answer: "x = −3y + 9" },
    relatedFormulaIds: ["mi_linear_eq", "mi_system_sub"]
  },
  {
    id: "mi_inequality",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    emoji: "⚠️",
    unit: "부등식",
    title: "일차부등식",
    formula: "음수를 곱하거나 나누면 부등호 방향이 반대로 바뀌기",
    latex: "x > a \\Rightarrow -x < -a",
    shortDescription: "크고 작음을 따지는 식으로 음수가 나오면 방향을 돌려주는 방법이에요.",
    easyExplanation: "부등식은 방정식처럼 이항하고 정리하면 돼요. 다만 양변에 음수를 곱하거나 나누는 순간에는 부등호 방향을 꼭 반대로 바꿔줘요.",
    funExplanation: "줄다리기에서 양 팀이 뒷걸음질로 방향을 바꾸면 승패 화살표도 반대로 돌아가요. 음수를 곱하는 것도 화살표를 뒤집는 일이에요.",
    memoryTip: "음수 만나면 화살표 뒤집기, 잊으면 답도 뒤집히기.",
    useWhen: "값의 범위를 구하거나 조건을 만족하는 수를 찾을 때 써요.",
    commonMistakes: ["음수로 나누고도 부등호를 그대로 두는 실수가 많아요.", "이항과 방향 바꾸기를 헷갈려서 양수에서도 뒤집어요."],
    example: { question: "−2x < 8의 해는?", steps: ["x의 앞 숫자가 −2이므로 양변을 −2로 나눠요.", "음수로 나누므로 <가 >로 바뀌어요.", "정리하면 x > −4가 답이에요."], answer: "x > −4" },
    quickCheck: { question: "−3x ≥ 9의 해는?", answer: "x ≤ −3" },
    relatedFormulaIds: ["mi_linear_eq"]
  },
  {
    id: "mi_system_add",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    emoji: "➕",
    unit: "연립방정식",
    title: "연립방정식 가감법",
    formula: "두 식을 더하거나 빼서 한 문자를 소거하고 풀기",
    latex: "\\begin{cases} x + y = 5 \\\\ x - y = 1 \\end{cases}",
    shortDescription: "두 식을 합치거나 빼서 문자 하나를 사라지게 하는 소거 방법이에요.",
    easyExplanation: "두 식에서 같은 문자의 앞 숫자를 똑같게 맞춘 뒤에 더하거나 빼요. 그러면 문자 하나가 사라지고 일차방정식 하나만 남아서 쉽게 풀려요.",
    funExplanation: "줄다리기 양 팀에 같은 몸무게 선수가 한 명씩 있으면 서로 힘이 상쇄돼요. 두 식을 빼면 그 선수가 사라지듯 문자가 사라져요.",
    memoryTip: "앞 숫자 맞추고 더하기 빼기, 하나 지우고 풀기.",
    useWhen: "미지수가 두 개인 두 식을 함께 만족하는 값을 구할 때 써요.",
    commonMistakes: ["앞 숫자를 맞추지 않고 바로 더해서 소거가 안 돼요.", "빼기에서 아래 식의 부호를 안 바꿔서 틀려요."],
    example: { question: "x + y = 7, x − y = 3의 해는?", steps: ["두 식을 더하면 y가 사라지고 2x = 10이 돼요.", "x = 5를 구해서 첫 식에 대입해요.", "5 + y = 7이므로 y = 2예요."], answer: "x = 5, y = 2" },
    quickCheck: { question: "x + y = 10, x − y = 2의 해는?", answer: "x = 6, y = 4" },
    relatedFormulaIds: ["mi_system_sub", "mi_transpose"]
  },
  {
    id: "mi_system_sub",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    emoji: "🔁",
    unit: "연립방정식",
    title: "연립방정식 대입법",
    formula: "한 식을 한 문자에 대해 풀어 다른 식에 대신 넣기",
    latex: "y = 2x, x + y = 9 \\Rightarrow x + 2x = 9",
    shortDescription: "식 하나를 다른 식에 끼워 넣어서 문자 하나로 만드는 방법이에요.",
    easyExplanation: "한 식을 x 또는 y에 대해 간단히 정리한 뒤에 다른 식에 대신 넣어줘요. 그러면 미지수가 하나인 식이 되므로 차례로 값을 구할 수 있어요.",
    funExplanation: "자판기에서 딸기맛 버튼이 사실 초코 2개와 같다는 안내가 있으면 딸기 대신 초코 2개를 넣어요. 문자를 바꾸어 넣는 것도 같은 원리예요.",
    memoryTip: "하나 풀어서 다른 식에 쏙, 대입하고 차례로 풀기.",
    useWhen: "한 식이 이미 x 또는 y에 대해 정리되어 있을 때 특히 편해요.",
    commonMistakes: ["대입할 때 괄호를 생략해서 곱셈이 틀어져요.", "x를 구하고 y를 구하지 않고 끝내요."],
    example: { question: "y = x + 1, x + y = 9의 해는?", steps: ["y 자리에 x + 1을 대신 넣어요.", "x + x + 1 = 9이므로 2x = 8이에요.", "x = 4이므로 y = 5예요."], answer: "x = 4, y = 5" },
    quickCheck: { question: "y = 2x, x + y = 12의 해는?", answer: "x = 4, y = 8" },
    relatedFormulaIds: ["mi_system_add", "mi_function"]
  },
  {
    id: "mi_factor_common",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    emoji: "📦",
    unit: "인수분해",
    title: "공통인수로 묶기",
    formula: "모든 항에 공통으로 들어간 문자나 수를 앞으로 묶어내기",
    latex: "ab + ac = a(b + c)",
    shortDescription: "식 속에 숨어 있는 공통 부분을 앞으로 꺼내서 묶는 방법이에요.",
    easyExplanation: "모든 항에 공통으로 들어간 수나 문자를 찾아서 괄호 앞으로 꺼내요. 괄호 안에는 공통 부분을 덜어낸 나머지만 남기면 돼요.",
    funExplanation: "자판기 묶음 상자에 모든 주머니에 사과가 하나씩 들어 있으면 사과를 먼저 꺼내요. 남은 간식만 상자 안에 도로 담으면 묶음이 완성돼요.",
    memoryTip: "공통 찾아 앞으로 빼기, 나머지는 괄호에 담기.",
    useWhen: "식을 곱셈 모양으로 바꾸거나 이차방정식을 쉽게 풀고 싶을 때 써요.",
    commonMistakes: ["공통 부분을 덜어내지 않고 원래대로 적는 실수가 많아요.", "가장 큰 공통 부분이 아닌 작은 부분만 묶어서 마무리가 안 돼요."],
    example: { question: "6x + 9를 인수분해하면?", steps: ["6과 9의 공통인 3을 찾아요.", "3을 앞으로 꺼내면 3(2x + 3) 모양이 돼요.", "전개해서 확인하면 6x + 9로 맞아요."], answer: "3(2x + 3)" },
    quickCheck: { question: "4xy + 8x를 인수분해하면?", answer: "4x(y + 2)" },
    relatedFormulaIds: ["mi_like_terms", "mi_quadratic_formula"]
  },
  {
    id: "mi_quadratic_formula",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    emoji: "🎯",
    unit: "이차방정식",
    title: "이차방정식 근의 공식",
    formula: "x는 2a분의 −b ± √D, D는 b² − 4ac",
    latex: "x = \\frac{-b \\pm \\sqrt{D}}{2a}, D = b^{2} - 4ac",
    shortDescription: "어떤 이차방정식도 공식에 숫자만 넣으면 해를 구하는 만능 열쇠예요.",
    easyExplanation: "ax² + bx + c = 0 모양에서 a와 b와 c를 찾아 공식에 그대로 넣어줘요. D가 0보다 크면 두 개, 0이면 하나, 작으면 해가 없어요.",
    funExplanation: "자판기에 동전 모양(a, b, c) 세 개를 넣고 근의 공식 버튼을 누르면 해가 나와요. 재료만 정확히 넣으면 음료가 나오듯 답이 나와요.",
    memoryTip: "마이너스 b 플마 루트 D, 분모는 2a로 나누기.",
    useWhen: "인수분해가 잘 안 되는 이차방정식의 해를 구할 때 써요.",
    commonMistakes: ["−b의 부호를 반대로 넣는 실수가 많아요.", "분모 2a에 괄호 없이 계산해서 나누기가 틀려요."],
    example: { question: "x² − 5x + 6 = 0의 해는?", steps: ["a = 1, b = −5, c = 6을 확인해요.", "D = 25 − 24 = 1이므로 √D = 1이에요.", "x = (5 ± 1) ÷ 2이므로 x = 3 또는 x = 2예요."], answer: "x = 2 또는 x = 3" },
    quickCheck: { question: "x² − 4x + 4 = 0의 해는?", answer: "x = 2" },
    relatedFormulaIds: ["mi_factor_common", "mi_quadratic_func"]
  },
  {
    id: "mi_function",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    emoji: "🎰",
    unit: "함수",
    title: "함수란?",
    formula: "하나의 입력 x에 하나의 출력 y가 정해지는 규칙",
    latex: "y = 2x + 1",
    shortDescription: "넣는 값이 하나면 나오는 값도 하나로 정해지는 약속이에요.",
    easyExplanation: "함수는 x를 하나 넣으면 y가 하나로 딱 정해지는 규칙이에요. 같은 x를 넣었는데 y가 두 개로 나오면 함수가 아니에요.",
    funExplanation: "자판기에 500원을 넣으면 항상 같은 맛 음료가 나와야 믿을 수 있어요. 돈을 넣을 때마다 다른 음료가 나오면 고장 난 자판기예요.",
    memoryTip: "하나 넣으면 하나 나오기, 두 개 나오면 탈락하기.",
    useWhen: "두 수량 사이의 관계가 규칙적인지 판단하고 싶을 때 써요.",
    commonMistakes: ["x² + y² 모양처럼 y가 두 개인 관계도 함수라고 착각해요.", "표에서 x가 같은데 y가 다른 줄을 못 찾아내요."],
    example: { question: "y = 3x에서 x = 2일 때 y의 값은?", steps: ["식에 x = 2를 대신 넣어요.", "3 × 2 = 6으로 계산해요.", "따라서 y = 6이에요."], answer: "6" },
    quickCheck: { question: "y = 2x + 1에서 x = 3일 때 y의 값은?", answer: "7" },
    relatedFormulaIds: ["mi_linear_func", "mi_direct_inverse"]
  },
  {
    id: "mi_linear_func",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    emoji: "📈",
    unit: "일차함수",
    title: "일차함수 y=ax+b",
    formula: "a는 기울기, b는 y절편, 그래프는 직선",
    latex: "y = ax + b",
    shortDescription: "기울기와 시작점으로 그려지는 곧은 직선 그래프예요.",
    easyExplanation: "a는 직선이 얼마나 가파른지를 보여주는 기울기예요. b는 x가 0일 때의 높이로 그래프가 y축과 만나는 점이에요.",
    funExplanation: "저울 위에 경사로를 올리면 a가 경사도이고 b가 출발 높이가 돼요. a가 클수록 가파르고 b가 클수록 높이 시작해요.",
    memoryTip: "a는 기울기 b는 시작점, 직선은 쭉쭉 뻗어가기.",
    useWhen: "변화율이 일정한 관계를 식과 그래프로 나타낼 때 써요.",
    commonMistakes: ["a와 b의 역할을 바꿔서 읽는 실수가 많아요.", "b를 x절편으로 착각해서 점을 잘못 찍어요."],
    example: { question: "y = 2x + 1의 기울기와 y절편은?", steps: ["x 앞 숫자 2가 기울기예요.", "더해진 1이 y절편이에요.", "그래프는 (0, 1)을 지나며 오른쪽으로 올라가요."], answer: "기울기 2, y절편 1" },
    quickCheck: { question: "y = −3x + 4의 기울기와 y절편은?", answer: "기울기 −3, y절편 4" },
    relatedFormulaIds: ["mi_slope", "mi_intercept", "mi_function"]
  },
  {
    id: "mi_slope",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    emoji: "⛰️",
    unit: "일차함수",
    title: "기울기 구하기",
    formula: "기울기는 y증가량 ÷ x증가량",
    latex: "a = \\frac{\\Delta y}{\\Delta x}",
    shortDescription: "직선이 얼마나 가파르게 오르는지를 숫자로 재는 방법이에요.",
    easyExplanation: "그래프 위의 두 점을 골라 x가 얼마나 늘었는지와 y가 얼마나 늘었는지를 구해요. y증가량을 x증가량으로 나누면 기울기가 나와요.",
    funExplanation: "줄다리기 줄을 산 비탈에 올려놓고 가로로 2m 갈 때 세로로 4m 오르면 기울기는 2예요. 오르막이 급할수록 기울기가 커져요.",
    memoryTip: "위 증가 나누기 옆 증가, 오르면 플러스 내리면 마이너스.",
    useWhen: "두 점을 지나는 직선의 가파른 정도를 구할 때 써요.",
    commonMistakes: ["x증가량과 y증가량을 뒤집어 나누는 실수가 많아요.", "감소인데도 플러스로 적는 부호 실수가 많아요."],
    example: { question: "(1, 2)와 (3, 8)을 지나는 직선의 기울기는?", steps: ["x증가량은 3 − 1 = 2예요.", "y증가량은 8 − 2 = 6이에요.", "6 ÷ 2 = 3이므로 기울기는 3이에요."], answer: "3" },
    quickCheck: { question: "(0, 1)과 (2, 7)을 지나는 직선의 기울기는?", answer: "3" },
    relatedFormulaIds: ["mi_linear_func", "mi_distance"]
  },
  {
    id: "mi_intercept",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    emoji: "📍",
    unit: "일차함수",
    title: "x절편과 y절편",
    formula: "x절편은 y=0일 때 x, y절편은 x=0일 때 y",
    latex: "y = 2x + 3",
    shortDescription: "그래프가 두 축과 만나는 만남의 장소를 찾는 방법이에요.",
    easyExplanation: "y절편은 x에 0을 넣어서 바로 구할 수 있어요. x절편은 y에 0을 넣고 방정식을 풀어서 구하면 돼요.",
    funExplanation: "줄다리기 줄이 운동장 가로선과 세로선을 가로지르는 지점을 표시해요. 가로선 만남이 x절편이고 세로선 만남이 y절편이에요.",
    memoryTip: "y절편은 x에 0 넣기, x절편은 y에 0 넣기.",
    useWhen: "직선 그래프를 빠르게 그리거나 축과 만나는 점을 찾을 때 써요.",
    commonMistakes: ["절편을 점이 아니라 숫자 하나로만 적어서 혼동해요.", "x절편을 구할 때 y절편처럼 바로 읽으려 해요."],
    example: { question: "y = 2x − 4의 x절편과 y절편은?", steps: ["x에 0을 넣으면 y = −4이므로 y절편은 −4예요.", "y에 0을 넣으면 2x − 4 = 0이 돼요.", "x = 2이므로 x절편은 2예요."], answer: "x절편 2, y절편 −4" },
    quickCheck: { question: "y = x + 3의 x절편과 y절편은?", answer: "x절편 −3, y절편 3" },
    relatedFormulaIds: ["mi_linear_func", "mi_slope"]
  },
  {
    id: "mi_direct_inverse",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    emoji: "⚖️",
    unit: "비례",
    title: "정비례와 반비례",
    formula: "정비례는 y=ax, 반비례는 y=a÷x",
    latex: "y = ax, y = \\frac{a}{x}",
    shortDescription: "함께 커지면 정비례, 한쪽이 커질 때 다른 쪽이 작아지면 반비례예요.",
    easyExplanation: "정비례는 x가 두 배가 되면 y도 두 배가 되는 관계예요. 반비례는 x가 두 배가 되면 y는 절반이 되는 관계예요.",
    funExplanation: "저울의 양쪽에 같은 추를 올리면 함께 무거워져서 정비례가 돼요. 시소처럼 한쪽이 올라가면 다른 쪽이 내려가면 반비례예요.",
    memoryTip: "함께 크면 정비례, 거꾸로 가면 반비례.",
    useWhen: "두 양이 어떤 비례 관계인지 판단하고 식으로 나타낼 때 써요.",
    commonMistakes: ["x가 커질 때 y가 작아지는데도 정비례라고 해요.", "반비례 그래프를 직선으로 그리는 실수가 많아요."],
    example: { question: "y가 x에 정비례하고 x = 2일 때 y = 6이면 식은?", steps: ["y = ax에 x = 2와 y = 6을 넣어요.", "6 = 2a이므로 a = 3이에요.", "따라서 식은 y = 3x예요."], answer: "y = 3x" },
    quickCheck: { question: "y가 x에 반비례하고 x = 2일 때 y = 9이면 식은?", answer: "y = 18 ÷ x" },
    relatedFormulaIds: ["mi_function", "mi_linear_func"]
  },
  {
    id: "mi_quadratic_func",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "function",
    emoji: "🌈",
    unit: "이차함수",
    title: "이차함수 y=ax²",
    formula: "그래프는 포물선, 꼭짓점이 가장 높거나 낮은 점",
    latex: "y = ax^{2}",
    shortDescription: "공을 던졌을 때 그리듯 활처럼 휘어지는 포물선 그래프예요.",
    easyExplanation: "a가 플러스이면 아래로 볼록하게 열리고 마이너스이면 위로 볼록하게 열려요. a의 절대값이 클수록 폭이 좁아지고 그래프가 날렵해져요.",
    funExplanation: "줄다리기 줄을 가운데에서 잡아당기면 양쪽이 대칭으로 휘어져요. 그 휘어진 모양이 바로 이차함수 포물선과 닮았어요.",
    memoryTip: "플러스는 아래로 포옹, 마이너스는 위로 포옹.",
    useWhen: "던진 물체의 움직임처럼 곡선 관계를 나타낼 때 써요.",
    commonMistakes: ["볼록한 방향을 반대로 그리는 실수가 많아요.", "꼭짓점을 y절편과 헷갈려서 점을 잘못 찍어요."],
    example: { question: "y = 2x²에서 x = 3일 때 y의 값은?", steps: ["식에 x = 3을 대신 넣어요.", "x² = 9이므로 2 × 9로 계산해요.", "따라서 y = 18이에요."], answer: "18" },
    quickCheck: { question: "y = −x²에서 x = 4일 때 y의 값은?", answer: "−16" },
    relatedFormulaIds: ["mi_quadratic_formula", "mi_linear_func"]
  },
  {
    id: "mi_pythagoras",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    emoji: "📐",
    unit: "삼각형",
    title: "피타고라스 정리",
    formula: "직각삼각형에서 a² + b² = c², c는 빗변",
    latex: "a^{2} + b^{2} = c^{2}",
    shortDescription: "직각삼각형의 세 변 길이를 이어주는 가장 유명한 약속이에요.",
    easyExplanation: "직각을 낀 두 변을 제곱해서 더하면 빗변의 제곱과 같아져요. 한 변을 모를 때는 빗변 제곱에서 아는 변 제곱을 빼면 돼요.",
    funExplanation: "저울처럼 빗변의 무게가 나머지 두 변의 무게 합과 균형을 이뤄요. 짧은 변이 3과 4이면 빗변은 5로 딱 맞아요.",
    memoryTip: "직각 낀 둘 제곱 더하기, 빗변 제곱과 같아지기.",
    useWhen: "직각삼각형에서 모르는 변의 길이를 구해야 할 때 써요.",
    commonMistakes: ["빗변이 아닌 변을 c 자리에 넣는 실수가 많아요.", "제곱을 빼먹고 그냥 더해서 길이를 구해요."],
    example: { question: "직각을 낀 두 변이 6과 8일 때 빗변은?", steps: ["6² + 8² = 36 + 64로 계산해요.", "합은 100이므로 빗변의 제곱은 100이에요.", "100의 제곱근은 10이므로 빗변은 10이에요."], answer: "10" },
    quickCheck: { question: "직각을 낀 두 변이 5와 12일 때 빗변은?", answer: "13" },
    relatedFormulaIds: ["mi_distance", "mi_pyramid_vol"]
  },
  {
    id: "mi_congruent",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    emoji: "👯",
    unit: "합동",
    title: "삼각형의 합동조건",
    formula: "SSS와 SAS와 ASA 중 하나가 맞으면 합동",
    latex: "",
    shortDescription: "두 삼각형이 쌍둥이처럼 완전히 같은지를 판단하는 조건이에요.",
    easyExplanation: "세 변이 모두 같거나 두 변과 끼인각이 같으면 합동이에요. 한 변과 양 끝각이 같을 때도 두 삼각형은 완전히 겹쳐져요.",
    funExplanation: "줄다리기 팀원 세 명의 키와 간격이 모두 같으면 두 팀은 쌍둥이 팀이에요. 세 조건 중 하나만 맞아도 쌍둥이로 인정해요.",
    memoryTip: "세 변, 두 변 끼인각, 한 변 양 끝각.",
    useWhen: "두 도형이 완전히 같은 도형인지 증명하고 싶을 때 써요.",
    commonMistakes: ["끼인각이 아닌 다른 각을 써서 합동이라고 해요.", "변 하나와 각 하나로 합동이라고 착각해요."],
    example: { question: "두 삼각형의 세 변이 각각 4와 5와 6으로 같으면?", steps: ["세 변이 모두 같은지 확인해요.", "SSS 조건에 해당하므로 합동이 돼요.", "따라서 짝이 되는 각도 모두 같아요."], answer: "합동이에요" },
    quickCheck: { question: "두 변이 5와 7로 같고 끼인각이 같으면?", answer: "합동이에요" },
    relatedFormulaIds: ["mi_similar"]
  },
  {
    id: "mi_circle_angle",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "geometry",
    emoji: "⭕",
    unit: "원",
    title: "원주각",
    formula: "원주각은 같은 호의 중심각의 절반",
    latex: "w = \\frac{c}{2}",
    shortDescription: "원 둘레에서 보는 각이 중심에서 보는 각의 절반이 되는 규칙이에요.",
    easyExplanation: "같은 호를 바라보는 원주각들은 크기가 모두 같아요. 그 크기는 같은 호의 중심각의 정확히 절반이 돼요.",
    funExplanation: "줄다리기 심판이 한가운데에서 넓게 보고 선수가 가장자리에서 좁게 봐요. 가장자리 시야가 중심 시야의 절반이 되는 모습이에요.",
    memoryTip: "원은 절반의 마법, 중심각 나누기 2.",
    useWhen: "원 위의 각 크기를 구하거나 같은 각을 찾을 때 써요.",
    commonMistakes: ["바라보는 호가 다른 각끼리 같다고 하는 실수가 많아요.", "중심각과 원주각을 반대로 곱하거나 나눠요."],
    example: { question: "중심각이 80도인 호의 원주각은?", steps: ["같은 호를 바라보는지 확인해요.", "원주각은 중심각의 절반이므로 80 ÷ 2예요.", "따라서 원주각은 40도예요."], answer: "40도" },
    quickCheck: { question: "중심각이 100도인 호의 원주각은?", answer: "50도" },
    relatedFormulaIds: ["mi_sector", "mi_circle_area"]
  },
  {
    id: "mi_circle_area",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    emoji: "🥧",
    unit: "원",
    title: "원의 넓이",
    formula: "원의 넓이는 π × 반지름²",
    latex: "S = \\pi r^{2}",
    shortDescription: "둥근 파이를 반지름만 알면 넓이를 바로 구하는 공식이에요.",
    easyExplanation: "반지름을 제곱한 뒤에 원주율 π를 곱하면 넓이가 나와요. 반지름이 두 배가 되면 넓이는 네 배가 돼요.",
    funExplanation: "자판기에서 파이 한 판을 고르면 반지름 버튼을 눌러 크기가 정해져요. 반지름이 두 배인 파이는 네 판 만큼의 양이 나와요.",
    memoryTip: "반지름 제곱에 파이 곱하기, 두 배면 네 배 되기.",
    useWhen: "동그란 땅이나 접시의 크기를 구해야 할 때 써요.",
    commonMistakes: ["지름을 반지름으로 착각해서 네 배로 넓어져요.", "제곱을 빼먹고 반지름에 π만 곱해요."],
    example: { question: "반지름이 3인 원의 넓이는?", steps: ["반지름 3을 제곱하면 9예요.", "9에 π를 곱하면 9π가 돼요.", "따라서 넓이는 9π예요."], answer: "9π" },
    quickCheck: { question: "반지름이 5인 원의 넓이는?", answer: "25π" },
    relatedFormulaIds: ["mi_sector", "mi_cylinder_vol"]
  },
  {
    id: "mi_sector",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    emoji: "🍕",
    unit: "원",
    title: "부채꼴의 호와 넓이",
    formula: "중심각 ÷ 360만큼 원둘레와 원넓이를 잘라내기",
    latex: "l = 2\\pi r \\times \\frac{a}{360}, S = \\pi r^{2} \\times \\frac{a}{360}",
    shortDescription: "피자 한 조각처럼 각도만큼 잘라낸 부분의 길이와 넓이예요.",
    easyExplanation: "부채꼴은 전체 원에서 중심각만큼 잘라낸 조각이에요. 원둘레와 원넓이에 중심각을 360으로 나눈 비율을 곱하면 돼요.",
    funExplanation: "자판기에서 피자 한 판을 골라 90도 버튼을 누르면 4분의 1 조각이 나와요. 각도 버튼이 조각 크기를 정해줘요.",
    memoryTip: "각도 나누기 360 곱하기, 호도 넓이도 똑같이.",
    useWhen: "피자 조각이나 부채 모양의 길이와 넓이를 구할 때 써요.",
    commonMistakes: ["호의 길이에 넓이 비율을 반대로 곱해요.", "중심각 대신 호의 길이를 360으로 나눠요."],
    example: { question: "반지름 6, 중심각 90도인 부채꼴의 넓이는?", steps: ["원넓이는 36π예요.", "90 ÷ 360 = 4분의 1 비율이 나와요.", "36π의 4분의 1이므로 답은 9π예요."], answer: "9π" },
    quickCheck: { question: "반지름 4, 중심각 90도인 부채꼴의 호 길이는?", answer: "2π" },
    relatedFormulaIds: ["mi_circle_area", "mi_circle_angle"]
  },
  {
    id: "mi_cylinder_vol",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    emoji: "🛢️",
    unit: "입체",
    title: "기둥의 부피",
    formula: "기둥의 부피는 밑넓이 × 높이",
    latex: "V = S \\times h",
    shortDescription: "밑바닥 넓이를 높이만큼 차곡차곡 쌓는 부피 계산이에요.",
    easyExplanation: "기둥은 위아래 모양이 똑같아서 밑넓이만 알면 돼요. 그 밑넓이에 높이를 곱하면 전체 부피가 나와요.",
    funExplanation: "자판기 종이컵을 쌓으면 밑면 하나 높이가 계속 쌓여요. 컵을 높이 쌓을수록 음료가 더 많이 담겨요.",
    memoryTip: "밑넓이 곱하기 높이, 쌓을수록 커지기.",
    useWhen: "컵이나 상자 같은 기둥 모양 용기의 크기를 구할 때 써요.",
    commonMistakes: ["옆넓이를 밑넓이로 착각해서 곱해요.", "부피인데도 넓이 단위로 답을 적어요."],
    example: { question: "밑넓이 10, 높이 7인 기둥의 부피는?", steps: ["밑넓이 10을 확인해요.", "높이 7을 곱하면 70이 돼요.", "따라서 부피는 70이에요."], answer: "70" },
    quickCheck: { question: "밑넓이 9π, 높이 5인 원기둥의 부피는?", answer: "45π" },
    relatedFormulaIds: ["mi_circle_area", "mi_pyramid_vol"]
  },
  {
    id: "mi_pyramid_vol",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    emoji: "🔻",
    unit: "입체",
    title: "뿔의 부피",
    formula: "뿔의 부피는 같은 밑면 기둥의 3분의 1",
    latex: "V = \\frac{1}{3} \\times S \\times h",
    shortDescription: "뾰족하게 모이는 뿔은 기둥의 3분의 1만 담기는 공식이에요.",
    easyExplanation: "밑면과 높이가 같은 기둥과 뿔을 비교하면 뿔은 3분의 1만큼만 담겨요. 그래서 밑넓이에 높이를 곱한 뒤에 3으로 나누면 돼요.",
    funExplanation: "저울에 기둥 상자 모래를 올리고 뿔 상자 모래를 올리면 기둥이 세 배 무거워요. 뿔 세 개가 모여야 기둥 하나가 돼요.",
    memoryTip: "기둥 구하고 3으로 나누기, 뿔은 3분의 1 담기.",
    useWhen: "원뿔이나 사각뿔처럼 뾰족한 입체의 부피를 구할 때 써요.",
    commonMistakes: ["3분의 1을 곱하지 않고 기둥처럼 그대로 구해요.", "빗높이를 높이로 착각해서 길게 계산해요."],
    example: { question: "밑넓이 12, 높이 9인 뿔의 부피는?", steps: ["밑넓이 12에 높이 9를 곱하면 108이에요.", "뿔이므로 3분의 1을 곱해요.", "108 ÷ 3 = 36이므로 답은 36이에요."], answer: "36" },
    quickCheck: { question: "밑넓이 20, 높이 6인 뿔의 부피는?", answer: "40" },
    relatedFormulaIds: ["mi_cylinder_vol"]
  },
  {
    id: "mi_similar",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    emoji: "🔍",
    unit: "닮음",
    title: "닮음비와 넓이비·부피비",
    formula: "닮음비가 m:n이면 넓이비는 제곱, 부피비는 세제곱",
    latex: "m:n \\Rightarrow m^{2}:n^{2}, m^{3}:n^{3}",
    shortDescription: "모양은 같고 크기만 다른 도형의 길이와 넓이와 부피 관계예요.",
    easyExplanation: "대응하는 길이의 비가 닮음비가 되고 넓이의 비는 그 비를 제곱하면 돼요. 부피의 비는 그 비를 세제곱해서 구하면 돼요.",
    funExplanation: "자판기에서 작은 인형과 두 배 인형을 뽑으면 키는 2배지만 얼굴 넓이는 4배가 돼요. 몸무게에 해당하는 부피는 8배로 커져요.",
    memoryTip: "길이는 그대로, 넓이는 제곱, 부피는 세제곱.",
    useWhen: "확대하거나 축소한 도형의 넓이와 부피를 구할 때 써요.",
    commonMistakes: ["넓이비도 길이비와 같다고 생각하는 실수가 많아요.", "제곱과 세제곱을 바꿔서 넓이와 부피를 구해요."],
    example: { question: "닮음비가 2:3일 때 넓이비는?", steps: ["길이의 비 2:3을 확인해요.", "넓이비는 각각 제곱하므로 4:9예요.", "부피비라면 8:27이 돼요."], answer: "4:9" },
    quickCheck: { question: "닮음비가 1:2일 때 부피비는?", answer: "1:8" },
    relatedFormulaIds: ["mi_congruent", "mi_pythagoras"]
  },
  {
    id: "mi_distance",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    emoji: "📏",
    unit: "좌표",
    title: "두 점 사이의 거리",
    formula: "가로 차이와 세로 차이로 직각삼각형을 만들어 빗변 구하기",
    latex: "d = \\sqrt{a^{2} + b^{2}}",
    shortDescription: "지도 위 두 점 사이를 곧게 이은 최단 거리를 구하는 방법이에요.",
    easyExplanation: "두 점의 가로 차이와 세로 차이를 구해서 직각삼각형의 두 변으로 삼아요. 그 두 값을 제곱해서 더한 뒤에 제곱근을 하면 거리가 나와요.",
    funExplanation: "줄다리기 줄을 대각선으로 팽팽히 당기면 가로로 간 만큼과 세로로 간 만큼이 합쳐져요. 비탈 길이 재듯 피타고라스로 구해요.",
    memoryTip: "가로 차이 세로 차이, 제곱 더하고 루트 씌우기.",
    useWhen: "좌표평면 위의 두 지점 사이 거리를 구해야 할 때 써요.",
    commonMistakes: ["차이를 구하지 않고 좌표값을 그대로 제곱해요.", "마지막에 제곱근을 하지 않고 제곱 합에서 멈춰요."],
    example: { question: "(0, 0)과 (3, 4) 사이의 거리는?", steps: ["가로 차이는 3 − 0 = 3이에요.", "세로 차이는 4 − 0 = 4예요.", "9 + 16 = 25이므로 거리는 5예요."], answer: "5" },
    quickCheck: { question: "(1, 1)과 (4, 5) 사이의 거리는?", answer: "5" },
    relatedFormulaIds: ["mi_pythagoras", "mi_slope"]
  },
  {
    id: "mi_mean_med_mode",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    emoji: "📊",
    unit: "자료",
    title: "평균·중앙값·최빈값",
    formula: "평균은 합계 ÷ 개수, 중앙값은 가운데, 최빈값은 가장 많은 값",
    latex: "",
    shortDescription: "자료의 중심을 대표하는 세 가지 대표값을 구하는 방법이에요.",
    easyExplanation: "평균은 모두 더해서 개수로 나눈 값이에요. 중앙값은 크기 순서로 세웠을 때 가운데에 오는 값이고 최빈값은 가장 자주 나오는 값이에요.",
    funExplanation: "줄다리기 팀의 키를 줄 세우면 가운데 선수가 중앙값이고 가장 많은 키가 최빈값이에요. 모두 합쳐 나누면 평균 키가 나와요.",
    memoryTip: "평균은 나누기, 중앙은 가운데, 최빈은 단골손님.",
    useWhen: "시험 점수나 키처럼 자료의 중심을 한 숫자로 나타낼 때 써요.",
    commonMistakes: ["중앙값을 구할 때 순서대로 세우지 않고 그냥 가운데를 골라요.", "평균과 중앙값을 같은 것으로 착각해요."],
    example: { question: "2, 3, 7의 평균은?", steps: ["세 수를 모두 더하면 12예요.", "자료 개수는 3개예요.", "12 ÷ 3 = 4이므로 평균은 4예요."], answer: "4" },
    quickCheck: { question: "1, 2, 2, 5의 최빈값은?", answer: "2" },
    relatedFormulaIds: ["mi_histogram", "mi_relative_freq"]
  },
  {
    id: "mi_histogram",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    emoji: "📶",
    unit: "자료",
    title: "도수분포표와 히스토그램",
    formula: "자료를 구간으로 나누고 구간별 개수를 막대로 그리기",
    latex: "",
    shortDescription: "흩어진 자료를 구간별로 묶어서 막대 모양으로 보여주는 그림이에요.",
    easyExplanation: "자료를 일정한 구간으로 나누고 각 구간에 속한 개수를 세어 도수분포표를 만들어요. 그 도수를 막대 높이로 그리면 히스토그램이 완성돼요.",
    funExplanation: "자판기 음료를 맛별로 칸을 나누어 쌓으면 어느 맛이 인기인지 한눈에 보여요. 칸마다 막대를 세우는 것이 히스토그램이에요.",
    memoryTip: "구간 나누고 개수 세고, 막대 높이로 보이기.",
    useWhen: "자료가 어느 구간에 많이 모여 있는지 모양으로 보고 싶을 때 써요.",
    commonMistakes: ["구간의 경계를 겹치게 나눠서 개수가 두 번 세어져요.", "막대 사이를 띄워서 일반 막대그래프처럼 그려요."],
    example: { question: "점수 10, 12, 21, 22를 10점 구간으로 나누면?", steps: ["10점대에는 10과 12로 2개가 들어아요.", "20점대에는 21과 22로 2개가 들어아요.", "두 막대 높이가 같으므로 고르게 퍼졌어요."], answer: "10점대 2개, 20점대 2개" },
    quickCheck: { question: "히스토그램에서 가장 높은 막대는 무엇을 뜻할까요?", answer: "도수가 가장 큰 구간" },
    relatedFormulaIds: ["mi_mean_med_mode", "mi_boxplot"]
  },
  {
    id: "mi_probability",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    emoji: "🎲",
    unit: "확률",
    title: "확률의 정의",
    formula: "확률은 원하는 경우의 수 ÷ 전체 경우의 수",
    latex: "p = \\frac{a}{b}",
    shortDescription: "어떤 일이 일어날 가능성을 숫자로 나타내는 약속이에요.",
    easyExplanation: "가능한 모든 경우를 세어서 분모에 놓고 원하는 경우를 세어서 분자에 놓아요. 그 분수를 계산하면 0과 1 사이의 수가 나와요.",
    funExplanation: "자판기에 음료 5개 중 딸기맛 1개가 있으면 딸기가 나올 확률은 5분의 1이에요. 버튼을 누르기 전부터 가능성은 정해져 있어요.",
    memoryTip: "원하는 나누기 전체, 0과 1 사이 놓기.",
    useWhen: "주사위나 뽑기처럼 우연한 일의 가능성을 비교할 때 써요.",
    commonMistakes: ["전체를 세지 않고 원하는 것만 세어서 분수로 만들어요.", "확률이 1보다 크게 나오는 계산을 그대로 둬요."],
    example: { question: "주사위 한 개를 던져 3이 나올 확률은?", steps: ["전체 경우는 1부터 6까지 6가지예요.", "원하는 경우는 3 하나뿐이라 1가지예요.", "따라서 확률은 6분의 1이에요."], answer: "6분의 1" },
    quickCheck: { question: "동전 한 개를 던져 앞면이 나올 확률은?", answer: "2분의 1" },
    relatedFormulaIds: ["mi_count_cases", "mi_expected"]
  },
  {
    id: "mi_expected",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    emoji: "🎰",
    unit: "확률",
    title: "기댓값",
    formula: "기댓값은 각각의 확률 × 값의 합",
    latex: "E = \\sum p \\times x",
    shortDescription: "여러 번 반복했을 때 평균적으로 기대되는 값을 구하는 방법이에요.",
    easyExplanation: "각각 나올 수 있는 값에 그 확률을 곱한 뒤에 모두 더하면 돼요. 한 번의 결과가 아니라 여러 번 했을 때의 평균에 해당해요.",
    funExplanation: "자판기 뽑기에서 1000원짜리가 가끔 나오고 꽝이 많으면 평균 금액을 계산해요. 여러 번 뽑았을 때의 평균이 바로 기댓값이에요.",
    memoryTip: "확률 곱하기 값, 모두 더하면 기댓값.",
    useWhen: "게임이나 뽑기가 이득인지 손해인지 판단하고 싶을 때 써요.",
    commonMistakes: ["확률을 곱하지 않고 값만 더해서 평균을 내요.", "기댓값을 한 번 했을 때 꼭 나오는 값으로 착각해요."],
    example: { question: "500원 상품이 절반 확률, 100원 상품이 절반 확률이면 기댓값은?", steps: ["500 × 2분의 1 = 250을 계산해요.", "100 × 2분의 1 = 50을 계산해요.", "250 + 50 = 300이므로 기댓값은 300원이에요."], answer: "300원" },
    quickCheck: { question: "1000원을 절반 확률로 받는 게임의 기댓값은?", answer: "500원" },
    relatedFormulaIds: ["mi_probability"]
  },
  {
    id: "mi_count_cases",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "combinatorics",
    emoji: "🃏",
    unit: "경우의 수",
    title: "경우의 수",
    formula: "이어서 일어나면 곱하고 따로 일어나면 더하기",
    latex: "m + n, m \\times n",
    shortDescription: "가능한 모든 가지 수를 빠짐없이 세는 약속이에요.",
    easyExplanation: "두 일이 동시에 이어서 일어나면 경우를 서로 곱해서 세요. 두 일이 따로따로 하나만 일어나면 경우를 서로 더해서 세요.",
    funExplanation: "자판기에서 음료 3종과 간식 2종을 세트로 고르면 3 × 2 = 6가지가 나와요. 음료만 고르거나 간식만 고르면 3 + 2 = 5가지예요.",
    memoryTip: "이어지면 곱하기, 따로면 더하기.",
    useWhen: "동전 던지기나 길 찾기처럼 가능한 가지 수를 셀 때 써요.",
    commonMistakes: ["이어지는 경우인데도 더하기로 세는 실수가 많아요.", "같은 경우가 두 번 세어지도록 중복해서 세요."],
    example: { question: "셔츠 3장과 바지 2벌로 만들 수 있는 옷차림은?", steps: ["셔츠와 바지는 이어서 입으므로 곱하기로 세어요.", "3 × 2 = 6으로 계산해요.", "따라서 가능한 옷차림은 6가지예요."], answer: "6가지" },
    quickCheck: { question: "버스 2대와 전철 3대 중 하나를 타는 방법은?", answer: "5가지" },
    relatedFormulaIds: ["mi_probability"]
  },
  {
    id: "mi_relative_freq",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    emoji: "📉",
    unit: "자료",
    title: "상대도수",
    formula: "상대도수는 구간 도수 ÷ 전체 도수",
    latex: "r = \\frac{f}{n}",
    shortDescription: "전체 중에서 그 구간이 차지하는 비율을 나타내는 값이에요.",
    easyExplanation: "각 구간의 도수를 전체 개수로 나누면 상대도수가 나와요. 모든 구간의 상대도수를 더하면 1이 되어서 비율 비교가 쉬워져요.",
    funExplanation: "줄다리기 전체 선수 중 2학년이 몇 명인지 비율로 나타내면 상대도수예요. 선수 수가 달라도 비율로 비교하면 공평해져요.",
    memoryTip: "부분 나누기 전체, 합치면 1 되기.",
    useWhen: "자료 개수가 다른 두 집단의 분포를 비교하고 싶을 때 써요.",
    commonMistakes: ["도수를 그대로 상대도수라고 적는 실수가 많아요.", "상대도수의 합이 1이 되는지 확인하지 않아요."],
    example: { question: "전체 20명 중 10점대가 5명이면 상대도수는?", steps: ["구간 도수 5를 확인해요.", "전체 20으로 나누면 4분의 1이에요.", "소수로는 0.25이므로 답은 0.25예요."], answer: "0.25" },
    quickCheck: { question: "전체 50개 중 도수 10인 구간의 상대도수는?", answer: "0.2" },
    relatedFormulaIds: ["mi_histogram", "mi_probability"]
  },
  {
    id: "mi_boxplot",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    emoji: "📦",
    unit: "자료",
    title: "상자그림",
    formula: "최솟값과 사분위수와 중앙값과 최댓값 다섯 숫자로 상자 그리기",
    latex: "",
    shortDescription: "자료의 퍼짐을 상자 모양으로 한눈에 보여주는 그림이에요.",
    easyExplanation: "자료를 순서대로 세우고 사분위수를 찾아서 상자를 그려요. 상자 가운데 선은 중앙값이 되고 양쪽 선은 흩어짐을 보여줘요.",
    funExplanation: "줄다리기 선수들을 키 순서로 세우고 앞뒤 줄을 묶으면 상자가 생겨요. 가운데 선수가 중앙값이고 상자 길이가 흩어짐이에요.",
    memoryTip: "다섯 숫자 상자에 담기, 가운데 선은 중앙값.",
    useWhen: "두 반의 점수처럼 여러 자료의 퍼짐을 비교하고 싶을 때 써요.",
    commonMistakes: ["사분위수를 구할 때 중앙값을 포함해서 나누는 실수가 많아요.", "상자 길이를 전체 범위로 착각해서 읽어요."],
    example: { question: "1, 2, 3, 4, 5의 상자그림 중심선은?", steps: ["자료를 순서대로 세우면 그대로 1부터 5예요.", "가운데 값은 3이므로 중앙값은 3이에요.", "따라서 상자 가운데 선은 3에 그어요."], answer: "3" },
    quickCheck: { question: "2, 4, 6, 8의 중앙값은?", answer: "5" },
    relatedFormulaIds: ["mi_histogram", "mi_stddev"]
  },
  {
    id: "mi_stddev",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    emoji: "🎯",
    unit: "자료",
    title: "표준편차란?",
    formula: "표준편차는 분산에 루트를 씌운 값, 클수록 흩어짐이 큼",
    latex: "s = \\sqrt{V}",
    shortDescription: "자료가 평균에서 얼마나 흩어져 있는지를 재는 자예요.",
    easyExplanation: "각 자료에서 평균을 뺀 차이를 제곱해서 평균 내면 분산이 나와요. 그 분산에 루트를 씌운 값이 표준편차가 되어 원래 단위로 돌아와요.",
    funExplanation: "줄다리기 과녁 게임에서 점수가 과녁 중심에서 멀리 흩어지면 표준편차가 커져요. 한곳에 모이면 표준편차가 작아져요.",
    memoryTip: "평균 빼고 제곱 평균, 루트 씌우면 표준편차.",
    useWhen: "두 자료의 흩어진 정도를 숫자로 비교하고 싶을 때 써요.",
    commonMistakes: ["분산과 표준편차를 바꿔서 답하는 실수가 많아요.", "루트를 씌우지 않고 분산에서 멈추는 실수가 많아요."],
    example: { question: "분산이 25일 때 표준편차는?", steps: ["분산 25를 확인해요.", "표준편차는 분산에 루트를 씌운 값이에요.", "25의 제곱근은 5이므로 답은 5예요."], answer: "5" },
    quickCheck: { question: "분산이 16일 때 표준편차는?", answer: "4" },
    relatedFormulaIds: ["mi_mean_med_mode", "mi_boxplot"]
  }
];
