/* ============================================================
   수학아 놀자 (math) - 고등 공식 23개: 로그·삼각·수열·대수 (formula-hi-a.js)
   formula-data.js 가 합쳐서 window.MathFormulaData 로 만듭니다.
   ============================================================ */
window.MathFormulaHiA = [
  {
    id: "hi_exp_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    emoji: "🔟",
    unit: "지수",
    title: "지수법칙",
    formula: "a의 m제곱 × a의 n제곱 = a의 (m+n)제곱, (a의 m제곱)의 n제곱 = a의 (m×n)제곱",
    latex: "a^m \\times a^n = a^{m+n}, \\quad (a^m)^n = a^{mn}",
    shortDescription: "밑이 같은 거듭제곱을 간단히 계산하는 규칙이에요.",
    easyExplanation: "2를 여러 번 곱해야 할 때 매번 길게 쓰면 힘들어요. 그래서 지수는 긴 곱셈을 짧게 줄인 압축 표현이에요. 밑이 같으면 지수끼리 더하거나 빼거나 곱해서 간단히 계산해요.",
    funExplanation: "같은 모양의 상자를 층층이 쌓는 모습을 떠올려 보세요. 3층 위에 4층을 더 쌓으면 모두 7층이 돼요. 지수법칙도 밑이 같은 상자끼리 층수만 더하는 것과 같아요.",
    memoryTip: "밑이 같으면 지수는 더하고 빼고 곱해요!",
    useWhen: "밑이 같은 거듭제곱을 곱하거나 나누거나 다시 거듭제곱할 때 써요.",
    commonMistakes: ["밑이 다르면 지수끼리 더할 수 없어요.", "거듭제곱의 거듭제곱은 지수를 더하지 않고 곱해야 해요."],
    example: { question: "2의 3제곱 × 2의 4제곱의 값은?", steps: ["밑이 모두 2로 같음을 확인해요.", "지수를 더하면 3 + 4 = 7이 돼요.", "따라서 2의 7제곱이므로 128이에요."], answer: "2의 7제곱 = 128" },
    quickCheck: { question: "3의 2제곱 × 3의 3제곱의 값은?", answer: "3의 5제곱 = 243" },
    relatedFormulaIds: ["hi_log_def", "hi_log_laws"]
  },
  {
    id: "hi_log_def",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    emoji: "❓",
    unit: "로그",
    title: "로그의 뜻",
    formula: "log_a b = c ⇔ a의 c제곱 = b",
    latex: "\\log_a b = c \\iff a^c = b",
    shortDescription: "로그는 a를 몇 제곱해야 b가 되는지를 묻는 거꾸로 질문이에요.",
    easyExplanation: "2를 몇 제곱해야 8이 될지 궁금한 적이 있어요. 2의 3제곱이 8이니까 답은 3이에요. 이 질문을 기호로 쓰면 log_2 8 = 3이 돼요.",
    funExplanation: "엘리베이터를 생각해 보세요. 지수는 3층 버튼을 눌러 올라가는 거예요. 로그는 지금 8이라는 층에 있는데 몇 층 버튼을 눌렀는지 알아내는 거예요.",
    memoryTip: "로그는 지수의 거꾸로 질문! 몇 제곱해야 이 수가 될까?",
    useWhen: "거듭제곱 식에서 지수를 구해야 할 때 써요.",
    commonMistakes: ["밑과 진수 순서를 바꾸면 전혀 다른 값이에요.", "밑은 1이 아닌 양수여야 해요."],
    example: { question: "log_2 32의 값은?", steps: ["2를 몇 제곱해야 32인지 물어보는 식이에요.", "2의 1제곱부터 차례로 하면 2의 5제곱이 32예요.", "따라서 구하는 값은 5예요."], answer: "5" },
    quickCheck: { question: "log_3 27의 값은?", answer: "3" },
    relatedFormulaIds: ["hi_log_laws", "hi_exp_laws"]
  },
  {
    id: "hi_log_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    emoji: "🔄",
    unit: "로그",
    title: "로그의 성질",
    formula: "log_a (M×N) = log_a M + log_a N, log_a M의 n제곱 = n × log_a M",
    latex: "\\log_a (MN) = \\log_a M + \\log_a N, \\quad \\log_a M^n = n \\log_a M",
    shortDescription: "곱셈은 덧셈으로 바꾸어 로그 계산을 쉽게 해주는 규칙이에요.",
    easyExplanation: "큰 수의 곱셈을 로그로 계산해야 할 때가 있어요. 로그는 지수의 반대 질문이므로 곱셈이 덧셈으로 바뀌어요. 진수의 거듭제곱은 지수를 앞으로 꺼내서 곱하면 돼요.",
    funExplanation: "무거운 짐을 가벼운 조각으로 나누는 모습을 떠올려 보세요. 곱셈이라는 큰 짐을 덧셈이라는 작은 조각으로 나누는 거예요. 조각으로 나누면 계산이 훨씬 가벼워져요.",
    memoryTip: "곱은 합으로 나누면 차로 제곱은 앞으로!",
    useWhen: "로그의 곱셈이나 거듭제곱을 간단한 덧셈과 곱셈으로 고칠 때 써요.",
    commonMistakes: ["log_a (M+N)을 log_a M + log_a N으로 나누면 안 돼요.", "밑이 서로 다르면 성질을 바로 적용할 수 없어요."],
    example: { question: "log_2 8 + log_2 4의 값은?", steps: ["두 로그의 밑이 모두 2임을 확인해요.", "합을 하나의 로그로 모으면 log_2 (8×4) = log_2 32가 돼요.", "2의 5제곱이 32이므로 답은 5예요."], answer: "5" },
    quickCheck: { question: "log_3 9 + log_3 3의 값은?", answer: "3" },
    relatedFormulaIds: ["hi_log_def", "hi_common_log"]
  },
  {
    id: "hi_common_log",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    emoji: "💯",
    unit: "로그",
    title: "상용로그",
    formula: "log_10 N = log N, 자릿수 = 지표 + 1",
    latex: "\\log_{10} N = \\log N",
    shortDescription: "밑이 10인 로그로 자릿수와 크기를 쉽게 알아보는 도구예요.",
    easyExplanation: "1000처럼 0이 많은 수를 다룰 때가 있어요. 로그는 지수의 반대 질문이므로 밑을 10으로 정하면 자릿수가 보여요. log 1000 = 3처럼 0의 개수가 바로 답이 돼요.",
    funExplanation: "자전거 속도계를 떠올려 보세요. 실제 거리는 길지만 계기판 숫자는 작게 보여요. 상용로그도 큰 수를 작은 지표와 소수 부분으로 줄여서 보여줘요.",
    memoryTip: "밑이 10이면 생략! 자릿수는 지표에 하나 더!",
    useWhen: "큰 수의 자릿수나 소수점 위치를 빠르게 알고 싶을 때 써요.",
    commonMistakes: ["밑을 쓰지 않으면 자연로그가 아니라 상용로그예요.", "진수가 1보다 작으면 지표가 음수가 될 수 있어요."],
    example: { question: "log 10000의 값은?", steps: ["밑이 생략되었으므로 밑이 10인 상용로그예요.", "10을 몇 제곱해야 10000이 되는지 물어봐요.", "10의 4제곱이 10000이므로 답은 4예요."], answer: "4" },
    quickCheck: { question: "log 100의 값은?", answer: "2" },
    relatedFormulaIds: ["hi_log_def", "hi_log_laws"]
  },
  {
    id: "hi_trig_ratio",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "📐",
    unit: "삼각비",
    title: "삼각비 sin·cos·tan",
    formula: "sin = 높이 ÷ 빗변, cos = 밑변 ÷ 빗변, tan = 높이 ÷ 밑변",
    latex: "\\sin A = \\frac{a}{c}, \\quad \\cos A = \\frac{b}{c}, \\quad \\tan A = \\frac{a}{b}",
    shortDescription: "직각삼각형에서 각에 따라 변의 비율이 정해지는 관계예요.",
    easyExplanation: "기울어진 사다리의 기울기를 숫자로 나타내고 싶을 때가 있어요. 삼각함수는 각도와 길이의 관계 도구로 각이 정해지면 변의 비율이 정해져요. sin은 높이 나누기 빗변, cos은 밑변 나누기 빗변, tan은 높이 나누기 밑변이에요.",
    funExplanation: "그림자의 길이를 떠올려 보세요. 해가 낮을수록 그림자가 길어지듯이 각이 커지면 비율도 달라져요. 삼각비는 각도에 따라 그림자 길이를 미리 알려주는 표와 같아요.",
    memoryTip: "사높빗 코밑빗 탄높밑! 빗변을 기준으로 외워요!",
    useWhen: "직각삼각형에서 각이나 변의 길이를 구해야 할 때 써요.",
    commonMistakes: ["빗변을 기준으로 하지 않으면 분자와 분모가 바뀌어요.", "tan은 빗변이 아니라 밑변으로 나누어야 해요."],
    example: { question: "빗변이 10이고 한 예각이 A이며 마주보는 변이 6일 때 sin A는?", steps: ["sin은 높이 나누기 빗변임을 떠올려요.", "높이는 6이고 빗변은 10이므로 분수는 6 ÷ 10이에요.", "약분하면 5분의 3이므로 답은 0점 6이에요."], answer: "5분의 3 = 0점 6" },
    quickCheck: { question: "빗변이 5이고 밑변이 4일 때 각 A의 cos A는?", answer: "5분의 4 = 0점 8" },
    relatedFormulaIds: ["hi_special_angles", "hi_unit_circle"]
  },
  {
    id: "hi_special_angles",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "⭐",
    unit: "삼각비",
    title: "특수각의 삼각비",
    formula: "30°·45°·60°의 sin·cos·tan 값",
    latex: "\\sin 30^\\circ = \\frac{1}{2}, \\quad \\cos 60^\\circ = \\frac{1}{2}, \\quad \\tan 45^\\circ = 1",
    shortDescription: "자주 나오는 30도 45도 60도의 값을 바로 쓰는 표예요.",
    easyExplanation: "시험에서 삼각형의 길이를 자주 물어봐요. 삼각함수는 각도와 길이의 관계 도구이므로 자주 쓰는 각은 값을 외우면 편해요. 30도와 60도는 1대 2대 루트3 직각삼각형에서 나오고 45도는 1대 1대 루트2에서 나와요.",
    funExplanation: "단골 메뉴판을 떠올려 보세요. 매번 레시피를 보지 않고 바로 주문하듯이 자주 쓰는 각도 외워두면 빨라요. 30도와 60도는 단짝이고 45도는 혼자서 나오는 주인공이에요.",
    memoryTip: "삼십은 이분의 일 사십오는 루트이분의 일 육십은 루트삼분의 이!",
    useWhen: "30도 45도 60도가 나오는 삼각형의 변을 빠르게 구할 때 써요.",
    commonMistakes: ["30도와 60도의 sin과 cos 값을 서로 바꾸기 쉬워요.", "tan 60도는 루트3이지 3분의 루트3이 아니에요."],
    example: { question: "sin 30° + cos 60°의 값은?", steps: ["sin 30도가 2분의 1임을 떠올려요.", "cos 60도도 2분의 1임을 확인해요.", "두 값을 더하면 1이므로 답은 1이에요."], answer: "1" },
    quickCheck: { question: "tan 45°의 값은?", answer: "1" },
    relatedFormulaIds: ["hi_trig_ratio", "hi_unit_circle"]
  },
  {
    id: "hi_unit_circle",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "⭕",
    unit: "삼각함수",
    title: "일반각과 단위원",
    formula: "반지름이 1인 원 위의 점 (cosθ, sinθ)",
    latex: "P(\\theta) = (\\cos \\theta, \\sin \\theta)",
    shortDescription: "반지름이 1인 원 위에서 모든 각도의 삼각함수를 읽는 방법이에요.",
    easyExplanation: "90도를 넘는 큰 각도도 다루어야 할 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 반지름이 1인 원을 쓰면 모든 각도를 나타낼 수 있어요. 원 위의 점의 가로좌표가 cos이고 세로좌표가 sin이에요.",
    funExplanation: "시계 바늘 끝을 떠올려 보세요. 바늘이 한 바퀴를 돌면서도 끝의 위치는 항상 알 수 있어요. 단위원도 각도가 커져도 점의 위치로 삼각함수를 알려줘요.",
    memoryTip: "가로는 코사인 세로는 사인! 반지름은 일!",
    useWhen: "90도를 넘는 각이나 음의 각의 삼각함수를 구할 때 써요.",
    commonMistakes: ["가로와 세로를 바꾸면 sin과 cos이 바뀌어요.", "각도의 방향을 반대로 읽으면 부호가 달라져요."],
    example: { question: "각이 180°일 때 점의 좌표와 cos 180°는?", steps: ["단위원에서 180도는 왼쪽 끝 점을 가리켜요.", "그 점의 좌표는 가로가 마이너스 1이고 세로가 0이에요.", "가로좌표가 cos이므로 답은 마이너스 1이에요."], answer: "마이너스 1" },
    quickCheck: { question: "cos 90°의 값은?", answer: "0" },
    relatedFormulaIds: ["hi_trig_ratio", "hi_radian"]
  },
  {
    id: "hi_radian",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "🥧",
    unit: "삼각함수",
    title: "호도법",
    formula: "180° = π, 1라디안은 약 57.3°",
    latex: "180^\\circ = \\pi, \\quad 1^\\circ = \\frac{\\pi}{180}",
    shortDescription: "각도를 호의 길이로 나타내는 새로운 각도 단위예요.",
    easyExplanation: "삼각함수를 그래프로 그릴 때는 각도보다 길이가 편할 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 각도를 길이로 바꾸면 계산이 쉬워져요. 반원의 호의 길이가 π이므로 180도는 π와 같아요.",
    funExplanation: "피자를 떠올려 보세요. 조각의 벌어진 정도를 각도 대신 가장자리 길이로 말하는 거예요. 피자 한 조각의 껍질이 길수록 각도도 크다고 말해줘요.",
    memoryTip: "백팔십도는 파이야! 각도에 파이 나누기 백팔십!",
    useWhen: "삼각함수의 그래프나 미적분에서 각도를 길이로 다룰 때 써요.",
    commonMistakes: ["도와 라디안을 섞어서 계산하면 값이 전혀 달라져요.", "π를 180이 아니라 180도로 바꾸지 않고 숫자로만 쓰기 쉬워요."],
    example: { question: "90도를 호도법으로 나타내면?", steps: ["180도가 π임을 떠올려요.", "90도는 180도의 절반이므로 π의 절반이에요.", "따라서 답은 2분의 π예요."], answer: "2분의 π" },
    quickCheck: { question: "60도를 호도법으로 나타내면?", answer: "3분의 π" },
    relatedFormulaIds: ["hi_unit_circle", "hi_trig_graph"]
  },
  {
    id: "hi_trig_graph",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "🌊",
    unit: "삼각함수",
    title: "삼각함수 그래프",
    formula: "sin과 cos은 파도 모양으로 반복, tan은 끊기며 반복",
    latex: "y = \\sin x, \\quad y = \\cos x, \\quad y = \\tan x",
    shortDescription: "각도가 커질 때 삼각함수 값이 파도처럼 변하는 그림이에요.",
    easyExplanation: "계절처럼 반복되는 변화를 그림으로 보고 싶을 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 각도를 옆으로 늘리면 파도 모양이 나와요. sin은 0에서 시작해 오르내리고 cos은 1에서 시작해요.",
    funExplanation: "바닷가 파도를 떠올려 보세요. 밀려왔다가 밀려가기를 반복하듯이 sin과 cos도 오르락내리락해요. tan은 파도가 방파제에 부딪혀 끊기는 모습과 같아요.",
    memoryTip: "사인은 영에서 출발 코사인은 일에서 출발!",
    useWhen: "삼각함수의 최댓값이나 주기를 그림으로 확인할 때 써요.",
    commonMistakes: ["sin과 cos의 시작점을 서로 바꾸기 쉬워요.", "tan 그래프가 끊기는 점을 잊고 하나로 이어 그려요."],
    example: { question: "y = sin x의 최댓값과 그때 가장 작은 양의 x는?", steps: ["sin 그래프는 0에서 시작해 위로 올라가는 파도예요.", "가장 높은 값은 1임을 그래프에서 확인해요.", "처음으로 1이 되는 곳은 2분의 π이므로 답은 1과 2분의 π예요."], answer: "최댓값 1, x는 2분의 π" },
    quickCheck: { question: "y = cos 0의 값은?", answer: "1" },
    relatedFormulaIds: ["hi_unit_circle", "hi_trig_identity"]
  },
  {
    id: "hi_trig_identity",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "🪞",
    unit: "삼각함수",
    title: "삼각함수 항등식",
    formula: "sin²θ + cos²θ = 1, tanθ = sinθ ÷ cosθ",
    latex: "\\sin^2 \\theta + \\cos^2 \\theta = 1, \\quad \\tan \\theta = \\frac{\\sin \\theta}{\\cos \\theta}",
    shortDescription: "sin과 cos 사이에는 항상 성립하는 거울 같은 관계가 있어요.",
    easyExplanation: "sin을 알 때 cos을 구해야 하는 상황이 생겨요. 삼각함수는 각도와 길이의 관계 도구이므로 단위원 위의 점은 항상 빗변이 1이에요. 가로의 제곱과 세로의 제곱을 더하면 항상 1이 돼요.",
    funExplanation: "거울 속 내 모습을 떠올려 보세요. 키가 크면 그림자도 길어지듯이 sin과 cos은 서로 묶여 있어요. 하나가 커지면 다른 하나는 작아져서 제곱의 합은 항상 1이에요.",
    memoryTip: "사인제곱 더하기 코사인제곱은 언제나 일!",
    useWhen: "sin 값으로 cos 값을 구하거나 식을 간단히 할 때 써요.",
    commonMistakes: ["sin²θ + cos²θ를 (sinθ + cosθ)의 제곱으로 착각해요.", "tan을 cos 나누기 sin으로 뒤집어 쓰기 쉬워요."],
    example: { question: "sinθ = 5분의 3일 때 cos²θ의 값은? 단 θ는 예각", steps: ["항등식 sin²θ + cos²θ = 1을 떠올려요.", "sin의 제곱은 25분의 9이므로 cos²θ = 1 − 25분의 9예요.", "계산하면 25분의 16이므로 답은 25분의 16이에요."], answer: "25분의 16" },
    quickCheck: { question: "cosθ = 5분의 4일 때 sin²θ의 값은? 단 θ는 예각", answer: "25분의 9" },
    relatedFormulaIds: ["hi_trig_ratio", "hi_trig_graph"]
  },
  {
    id: "hi_sine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "📏",
    unit: "삼각형",
    title: "사인법칙",
    formula: "a ÷ sinA = b ÷ sinB = c ÷ sinC = 2R",
    latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R",
    shortDescription: "변의 길이와 마주보는 각의 sin 비율이 모두 같은 규칙이에요.",
    easyExplanation: "각 하나와 변 하나를 알 때 나머지 변을 구하고 싶을 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 변을 sin으로 나누면 모두 외접원의 지름과 같아져요. 이 비율을 이용하면 모르는 변과 각을 구할 수 있어요.",
    funExplanation: "세 명이 줄다리기를 같은 힘으로 당기는 모습을 떠올려 보세요. 각자 위치는 달라도 힘의 균형은 같아요. 사인법칙도 세 변이 서로 다른 각도에 있지만 비율은 하나로 같아요.",
    memoryTip: "변 나누기 사인 모두다 이알! 외접원 지름과 같아!",
    useWhen: "두 각과 한 변을 알 때 나머지 변이나 외접원의 반지름을 구할 때 써요.",
    commonMistakes: ["변과 그 변이 마주보지 않는 각을 짝지으면 안 돼요.", "2R을 R로 착각해서 반지름을 두 배로 구해요."],
    example: { question: "A = 30°, a = 6인 삼각형의 외접원 반지름 R은?", steps: ["사인법칙 a ÷ sinA = 2R을 떠올려요.", "sin 30°는 2분의 1이므로 6 ÷ 2분의 1 = 12가 돼요.", "2R = 12이므로 R = 6이에요."], answer: "6" },
    quickCheck: { question: "A = 90°, a = 10인 삼각형의 외접원 지름 2R은?", answer: "10" },
    relatedFormulaIds: ["hi_cosine_rule", "hi_trig_ratio"]
  },
  {
    id: "hi_cosine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    emoji: "📐",
    unit: "삼각형",
    title: "코사인법칙",
    formula: "c² = a² + b² − 2ab × cosC",
    latex: "c^2 = a^2 + b^2 - 2ab \\cos C",
    shortDescription: "두 변과 끼인각으로 나머지 한 변을 구하는 공식이에요.",
    easyExplanation: "두 변의 길이와 사이의 각을 알 때 건너편 변이 궁금할 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 각이 90도가 아니면 빗변 공식을 고쳐야 해요. 양쪽 변의 제곱을 더한 뒤 각도만큼 빼주면 돼요.",
    funExplanation: "문짝이 열리는 모습을 떠올려 보세요. 문짝 두 개는 그대로인데 벌어진 각도에 따라 끝 사이 거리가 달라져요. 코사인법칙은 벌어진 각도만큼 거리를 조절해주는 줄자와 같아요.",
    memoryTip: "두 변 제곱 더하고 각도만큼 빼줘요!",
    useWhen: "두 변과 끼인각을 알 때 나머지 변을 구하거나 세 변으로 각을 구할 때 써요.",
    commonMistakes: ["끼인각이 아니라 다른 각의 cos을 곱하기 쉬워요.", "2ab를 빼지 않고 더하면 전혀 다른 답이 나와요."],
    example: { question: "a = 3, b = 4, 끼인각 C = 90°일 때 c는?", steps: ["코사인법칙 c² = a² + b² − 2ab × cosC를 떠올려요.", "cos 90° = 0이므로 마지막 항이 0이 돼요.", "c² = 9 + 16 = 25이므로 c = 5예요."], answer: "5" },
    quickCheck: { question: "a = 5, b = 5, 끼인각 C = 60°일 때 c²은?", answer: "25" },
    relatedFormulaIds: ["hi_sine_rule", "hi_trig_identity"]
  },
  {
    id: "hi_arith_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    emoji: "🪜",
    unit: "수열",
    title: "등차수열",
    formula: "n번째 항 = 첫항 + (n−1) × 공차",
    latex: "a_n = a_1 + (n-1)d",
    shortDescription: "같은 수를 차례로 더해 만드는 규칙적인 숫자 줄이에요.",
    easyExplanation: "매일 같은 개수를 모을 때 전체 개수가 궁금할 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 등차수열은 같은 수를 계속 더해요. 첫항에 공차를 n−1번 더하면 n번째 수가 나와요.",
    funExplanation: "계단을 한 칸씩 오르는 모습을 떠올려 보세요. 항상 같은 높이로 오르므로 몇 번째 계단인지 쉽게 알 수 있어요. 등차수열도 걸음걸이가 일정한 계단과 같아요.",
    memoryTip: "첫항 더하기 엔마이너스일 곱하기 공차!",
    useWhen: "일정하게 늘어나는 수에서 n번째 수를 구할 때 써요.",
    commonMistakes: ["n 대신 n−1을 곱하지 않고 n을 곱하기 쉬워요.", "공차가 음수일 때 부호를 바꾸지 않고 더해요."],
    example: { question: "첫항이 3이고 공차가 4인 등차수열의 5번째 항은?", steps: ["일반항 a_n = a_1 + (n−1)d를 떠올려요.", "n = 5를 넣으면 3 + (5−1) × 4가 돼요.", "계산하면 3 + 16 = 19예요."], answer: "19" },
    quickCheck: { question: "첫항이 2이고 공차가 5인 등차수열의 4번째 항은?", answer: "17" },
    relatedFormulaIds: ["hi_arith_sum", "hi_geo_seq"]
  },
  {
    id: "hi_geo_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    emoji: "✖️",
    unit: "수열",
    title: "등비수열",
    formula: "n번째 항 = 첫항 × 공비의 (n−1)제곱",
    latex: "a_n = a_1 r^{n-1}",
    shortDescription: "같은 수를 차례로 곱해 만드는 규칙적인 숫자 줄이에요.",
    easyExplanation: "세균이 두 배씩 늘어날 때 나중 수가 궁금할 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 등비수열은 같은 수를 계속 곱해요. 첫항에 공비를 n−1번 곱하면 n번째 수가 나와요.",
    funExplanation: "종이를 계속 반으로 접는 모습을 떠올려 보세요. 한 번 접을 때마다 두께가 두 배가 돼요. 등비수열도 접을수록 깜짝 놀랄 만큼 빠르게 커져요.",
    memoryTip: "첫항 곱하기 공비의 엔마이너스일 제곱!",
    useWhen: "일정하게 곱해져 커지는 수에서 n번째 수를 구할 때 써요.",
    commonMistakes: ["n−1제곱이 아니라 n제곱을 곱하기 쉬워요.", "공비가 분수일 때 뒤집어서 곱하는 실수를 해요."],
    example: { question: "첫항이 2이고 공비가 3인 등비수열의 4번째 항은?", steps: ["일반항 a_n = a_1 × r의 (n−1)제곱을 떠올려요.", "n = 4를 넣으면 2 × 3의 3제곱이 돼요.", "3의 3제곱은 27이므로 답은 54예요."], answer: "54" },
    quickCheck: { question: "첫항이 3이고 공비가 2인 등비수열의 5번째 항은?", answer: "48" },
    relatedFormulaIds: ["hi_arith_seq", "hi_geo_sum"]
  },
  {
    id: "hi_arith_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    emoji: "➕",
    unit: "수열",
    title: "등차수열의 합",
    formula: "합 = n × (첫항 + 끝항) ÷ 2",
    latex: "S_n = \\frac{n(a_1 + a_n)}{2}",
    shortDescription: "일정하게 더해지는 수를 처음부터 끝까지 모두 더하는 공식이에요.",
    easyExplanation: "1부터 100까지 모두 더해야 할 때 하나씩 더하면 너무 오래 걸려요. 수열은 규칙을 가진 숫자 줄이므로 양쪽 끝을 짝지으면 합이 모두 같아져요. 양끝 합에 개수를 곱한 뒤 2로 나누면 돼요.",
    funExplanation: "양쪽에서 서로를 향해 달려와 만나는 친구를 떠올려 보세요. 앞에서 뒤에서 더한 짝이 모두 같은 합이 돼요. 짝의 합에 짝 개수를 곱하는 것이 등차수열의 합이에요.",
    memoryTip: "양끝 더해 개수 곱해 반으로 나눠!",
    useWhen: "등차수열의 처음부터 n번째까지의 합을 구할 때 써요.",
    commonMistakes: ["개수 n과 끝항의 번호를 헷갈려요.", "2로 나누는 것을 잊고 곱하기만 하고 끝내요."],
    example: { question: "1부터 10까지의 합은?", steps: ["첫항은 1이고 끝항은 10이며 개수는 10이에요.", "공식에 넣으면 10 × (1 + 10) ÷ 2가 돼요.", "계산하면 10 × 11 ÷ 2 = 55예요."], answer: "55" },
    quickCheck: { question: "1부터 20까지의 합은?", answer: "210" },
    relatedFormulaIds: ["hi_arith_seq", "hi_sigma"]
  },
  {
    id: "hi_geo_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    emoji: "🧮",
    unit: "수열",
    title: "등비수열의 합",
    formula: "합 = 첫항 × (1 − 공비의 n제곱) ÷ (1 − 공비)",
    latex: "S_n = \\frac{a_1 (1-r^n)}{1-r}",
    shortDescription: "일정하게 곱해지는 수를 처음부터 끝까지 모두 더하는 공식이에요.",
    easyExplanation: "두 배씩 커지는 수를 여러 개 더해야 할 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 등비수열의 합은 규칙을 이용해 한 번에 구해요. 첫항에 1에서 공비의 n제곱을 뺀 값을 곱한 뒤 1에서 공비를 뺀 값으로 나누면 돼요.",
    funExplanation: "눈덩이를 굴리는 모습을 떠올려 보세요. 굴릴수록 커지는 양이 달라지므로 하나씩 더하기 힘들어요. 등비수열의 합은 눈덩이가 커지는 규칙을 이용해 마지막 크기를 한 번에 재는 자와 같아요.",
    memoryTip: "첫항 곱하기 일마이너스알엔 나누기 일마이너스알!",
    useWhen: "등비수열의 처음부터 n번째까지의 합을 구할 때 써요.",
    commonMistakes: ["공비가 1일 때 그대로 나누면 0으로 나누게 돼요.", "분자와 분모의 1 − r 순서를 바꾸어 부호를 틀려요."],
    example: { question: "첫항 2, 공비 2인 등비수열의 처음 4개 항의 합은?", steps: ["합 공식 S_n = 첫항 × (1 − r의 n제곱) ÷ (1 − r)을 떠올려요.", "값을 넣으면 2 × (1 − 2의 4제곱) ÷ (1 − 2)가 돼요.", "계산하면 2 × (1 − 16) ÷ (−1) = 30이에요."], answer: "30" },
    quickCheck: { question: "첫항 3, 공비 2인 등비수열의 처음 3개 항의 합은?", answer: "21" },
    relatedFormulaIds: ["hi_geo_seq", "hi_sigma"]
  },
  {
    id: "hi_sigma",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    emoji: "Σ",
    unit: "수열",
    title: "시그마의 뜻과 성질",
    formula: "시그마는 k = 1부터 n까지의 합을 줄여 쓰는 기호",
    latex: "\\sum_{k=1}^{n} a_k = a_1 + a_2 + \\cdots + a_n",
    shortDescription: "긴 덧셈을 짧게 줄여 쓰는 약속 기호예요.",
    easyExplanation: "1부터 100까지 더한다는 말을 짧게 쓰고 싶을 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 시그마를 쓰면 시작과 끝만 보여주면 돼요. 시그마 밖의 수는 안으로 분배하여 각각 더할 수 있어요.",
    funExplanation: "긴 쇼핑 목록을 장바구니 하나로 묶는 모습을 떠올려 보세요. 물건을 하나씩 들지 않고 바구니째로 들고 가면 편해요. 시그마도 긴 덧셈을 하나의 바구니에 담는 기호예요.",
    memoryTip: "시그마는 합을 묶는 바구니! 밖의 수는 나눠 담아!",
    useWhen: "규칙 있는 덧셈을 짧게 쓰고 성질로 나누어 계산할 때 써요.",
    commonMistakes: ["시그마 안의 k와 밖의 n을 헷갈려요.", "제곱의 합을 합의 제곱과 같다고 착각해요."],
    example: { question: "시그마 k = 1부터 3까지 k의 합은?", steps: ["시그마는 k에 1부터 3까지 넣고 모두 더하라는 뜻이에요.", "1 + 2 + 3으로 풀어서 써요.", "더하면 6이므로 답은 6이에요."], answer: "6" },
    quickCheck: { question: "시그마 k = 1부터 4까지 2k의 합은?", answer: "20" },
    relatedFormulaIds: ["hi_arith_sum", "hi_geo_sum"]
  },
  {
    id: "hi_infinite_geo",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    emoji: "♾️",
    unit: "수열",
    title: "무한등비수열의 합",
    formula: "합 = 첫항 ÷ (1 − 공비), 단 공비의 절댓값이 1보다 작을 때",
    latex: "S = \\frac{a_1}{1-r}, \\quad |r| < 1",
    shortDescription: "영원히 더해도 끝이 있는 신기한 등비수열의 합이에요.",
    easyExplanation: "수를 끝없이 더하면 무한히 커질 것 같아 걱정될 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 공비가 작으면 더해도 어느 값에 가까워져요. 첫항을 1에서 공비를 뺀 값으로 나누면 그 끝값이 나와요.",
    funExplanation: "골대에 점점 가까워지는 공을 떠올려 보세요. 매번 남은 거리의 절반씩 가면 영원히 가도 골대에 닿지 않지만 가까워져요. 무한등비수열의 합은 공이 멈출 자리를 미리 알려줘요.",
    memoryTip: "첫항 나누기 일마이너스알! 공비는 일보다 작아야!",
    useWhen: "공비가 작은 등비수열을 끝없이 더한 값을 구할 때 써요.",
    commonMistakes: ["공비의 절댓값이 1보다 클 때도 공식을 그대로 써요.", "첫항 대신 두 번째 항을 나누는 실수를 해요."],
    example: { question: "첫항 1, 공비 2분의 1인 무한등비수열의 합은?", steps: ["공비의 절댓값이 1보다 작은지 확인해요.", "공식 첫항 ÷ (1 − 공비)에 값을 넣어요.", "1 ÷ (1 − 2분의 1) = 2이므로 답은 2예요."], answer: "2" },
    quickCheck: { question: "첫항 9, 공비 3분의 1인 무한등비수열의 합은?", answer: "13점 5" },
    relatedFormulaIds: ["hi_geo_sum", "hi_geo_seq"]
  },
  {
    id: "hi_induction",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    emoji: "🎲",
    unit: "증명",
    title: "수학적 귀납법",
    formula: "1일 때 성립 + k일 때 n = k+1도 성립 ⇒ 모두 성립",
    latex: "P(1) \\land (P(k) \\Rightarrow P(k+1)) \\Rightarrow P(n)",
    shortDescription: "도미노처럼 밀어 모든 자연수에서 성립함을 보이는 증명법이에요.",
    easyExplanation: "모든 자연수에 대해 성립함을 하나씩 확인할 수 없어 답답할 때가 있어요. 수열은 규칙을 가진 숫자 줄이므로 처음과 이어짐만 보이면 전체를 믿을 수 있어요. 첫 번째가 맞고 k번째가 맞다고 하면 다음도 맞음을 보이면 끝이에요.",
    funExplanation: "도미노가 쓰러지는 모습을 떠올려 보세요. 첫 조각이 쓰러지고 앞 조각이 뒤 조각을 쓰러뜨리면 모두 쓰러져요. 귀납법도 첫 도미노와 이어지는 규칙만 보이면 전체가 쓰러져요.",
    memoryTip: "첫 조각 쓰러뜨리고 다음 조각 잇기면 모두 쓰러져!",
    useWhen: "자연수 n에 대한 식이나 명제가 모두 맞음을 증명할 때 써요.",
    commonMistakes: ["첫 번째 확인을 빼먹고 이어짐만 보여요.", "k+1번째 식을 세울 때 k번째 가정을 쓰지 않아요."],
    example: { question: "1부터 n까지의 합이 n(n+1) ÷ 2임을 귀납법으로 보일 때 첫 단계는?", steps: ["n = 1일 때를 먼저 확인해야 해요.", "왼쪽은 1이고 오른쪽은 1 × 2 ÷ 2 = 1이에요.", "양쪽이 같으므로 첫 단계가 성립해요."], answer: "n = 1일 때 양쪽 모두 1로 성립" },
    quickCheck: { question: "귀납법의 두 번째 단계에서 가정하는 것은?", answer: "n = k일 때 성립한다고 가정" },
    relatedFormulaIds: ["hi_sigma", "hi_arith_sum"]
  },
  {
    id: "hi_remainder",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    emoji: "🧾",
    unit: "다항식",
    title: "나머지정리",
    formula: "다항식 f(x)를 x−a로 나눈 나머지는 f(a)",
    latex: "R = f(a)",
    shortDescription: "긴 나눗셈 없이 나머지를 바로 구하는 방법이에요.",
    easyExplanation: "다항식을 나누어 나머지를 구하려면 계산이 길어질 때가 있어요. x − a 뒤에 오는 수 a를 식에 그대로 넣으면 나머지가 나와요. 나눗셈을 하지 않고도 답을 알 수 있어요.",
    funExplanation: "택배 상자에 남은 빈 공간을 재는 모습을 떠올려 보세요. 상자를 다 뜯지 않고 구멍으로 손을 넣어 확인하는 것과 같아요. a를 넣는 것만으로 나머지라는 빈 공간이 보여요.",
    memoryTip: "나누는 식 뒤의 수 넣으면 나머지가 보여!",
    useWhen: "다항식을 일차식으로 나눈 나머지를 빠르게 구할 때 써요.",
    commonMistakes: ["x + a로 나눌 때는 마이너스 a를 넣어야 해요.", "나머지를 구했는데 몫까지 구했다고 착각해요."],
    example: { question: "f(x) = x² + 2x + 3을 x − 1로 나눈 나머지는?", steps: ["나머지정리에 따라 x = 1을 식에 넣어요.", "1의 제곱 + 2 × 1 + 3 = 6이 돼요.", "따라서 나머지는 6이에요."], answer: "6" },
    quickCheck: { question: "f(x) = x² + 1을 x − 2로 나눈 나머지는?", answer: "5" },
    relatedFormulaIds: ["hi_factor_thm", "hi_discriminant"]
  },
  {
    id: "hi_factor_thm",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    emoji: "✂️",
    unit: "다항식",
    title: "인수정리",
    formula: "f(a) = 0이면 x−a는 f(x)의 인수",
    latex: "f(a) = 0 \\iff (x-a) \\mid f(x)",
    shortDescription: "식을 0으로 만드는 수를 찾아 인수를 알아내는 방법이에요.",
    easyExplanation: "다항식을 인수분해하고 싶은데 어디서 시작할지 모를 때가 있어요. 식에 수를 넣어 0이 되면 그 수로 만든 일차식이 인수예요. 인수를 찾으면 나머지는 나누기로 구할 수 있어요.",
    funExplanation: "열쇠 구멍에 맞는 열쇠를 찾는 모습을 떠올려 보세요. 여러 열쇠를 넣어보다가 찰칵 맞으면 문이 열려요. 0을 만드는 수가 바로 식을 여는 열쇠예요.",
    memoryTip: "넣어서 영이면 인수야! 엑스마이너스아야!",
    useWhen: "삼차식 이상의 다항식을 인수분해할 때 써요.",
    commonMistakes: ["f(a) = 0인데 인수를 x + a로 잘못 써요.", "나머지가 0이 아닌데도 인수라고 착각해요."],
    example: { question: "f(x) = x³ − 6x² + 11x − 6의 한 인수는?", steps: ["x = 1을 넣으면 1 − 6 + 11 − 6 = 0이 돼요.", "따라서 x − 1은 인수예요.", "조립제법으로 나누면 나머지는 이차식이 돼요."], answer: "x − 1" },
    quickCheck: { question: "f(x) = x² − 4에서 f(2)의 값과 인수는?", answer: "0, x − 2는 인수" },
    relatedFormulaIds: ["hi_remainder", "hi_discriminant"]
  },
  {
    id: "hi_discriminant",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    emoji: "🔍",
    unit: "이차방정식",
    title: "판별식",
    formula: "D = b² − 4ac, D > 0이면 서로 다른 두 실근",
    latex: "D = b^2 - 4ac",
    shortDescription: "방정식을 풀기 전에 해의 개수를 미리 알려주는 숫자예요.",
    easyExplanation: "이차방정식을 풀기 전에 해가 몇 개인지 알고 싶을 때가 있어요. b의 제곱에서 4ac를 뺀 값 D를 구하면 해의 모습이 보여요. D가 양수면 두 개, 0이면 하나, 음수면 실수 해가 없어요.",
    funExplanation: "엑스레이 사진을 떠올려 보세요. 뜯어보지 않고도 안을 미리 볼 수 있어요. 판별식도 방정식을 끝까지 풀지 않고 해의 개수를 보여줘요.",
    memoryTip: "비제곱 빼기 사에이씨! 양수면 둘 영이면 하나!",
    useWhen: "이차방정식의 실근의 개수나 그래프와 만나는 점의 개수를 알 때 써요.",
    commonMistakes: ["b²이 아니라 2b로 계산하는 실수를 해요.", "D가 음수인데 해가 없다고 하지 않고 0이라고 써요."],
    example: { question: "x² − 4x + 3 = 0의 판별식 D와 근의 개수는?", steps: ["D = b² − 4ac에 a = 1, b = 마이너스 4, c = 3을 넣어요.", "16 − 12 = 4이므로 D = 4예요.", "D가 양수이므로 서로 다른 두 실근이에요."], answer: "D = 4, 서로 다른 두 실근" },
    quickCheck: { question: "x² + 2x + 1 = 0의 판별식 D는?", answer: "0" },
    relatedFormulaIds: ["hi_remainder", "hi_factor_thm"]
  },
  {
    id: "hi_trig_eq",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "trigonometry",
    emoji: "🎯",
    unit: "삼각함수",
    title: "삼각방정식",
    formula: "sin x = k, cos x = k를 단위원에서 각으로 찾기",
    latex: "\\sin x = k, \\quad \\cos x = k",
    shortDescription: "삼각함수 값이 주어졌을 때 각도를 찾아내는 방정식이에요.",
    easyExplanation: "sin 값이 2분의 1이 되는 각이 궁금할 때가 있어요. 삼각함수는 각도와 길이의 관계 도구이므로 단위원에서 높이가 2분의 1인 점을 찾아요. 0도부터 360도 사이에서는 대칭인 두 각이 답이 돼요.",
    funExplanation: "과녁에서 같은 점수 링을 찾는 모습을 떠올려 보세요. 왼쪽과 오른쪽 대칭 자리가 같은 점수예요. 삼각방정식도 단위원 위에서 높이가 같은 두 자리를 찾는 놀이와 같아요.",
    memoryTip: "단위원에서 높이 찾고 대칭각도 챙겨!",
    useWhen: "sin이나 cos 값이 주어졌을 때 범위 안의 각을 모두 구할 때 써요.",
    commonMistakes: ["범위 안의 해 하나만 구하고 대칭인 해를 빼먹어요.", "도와 라디안을 섞어서 답을 써요."],
    example: { question: "0° ≤ x < 360°에서 sin x = 2분의 1인 x는?", steps: ["단위원에서 높이가 2분의 1인 점을 찾아요.", "첫 번째 각은 30°임을 확인해요.", "대칭각 180° − 30° = 150°도 답이 돼요."], answer: "30°, 150°" },
    quickCheck: { question: "0° ≤ x < 360°에서 cos x = 2분의 1인 예각 x는?", answer: "60°" },
    relatedFormulaIds: ["hi_unit_circle", "hi_trig_graph"]
  }
];
