/* ============================================================
   수학아 놀자 (math) - 초등 문제 60개 (problem-el.js)
   problem-data.js 가 합쳐서 window.MathProblemData 로 만듭니다.
   ============================================================ */
window.MathProblemEl = [
  {
    id: "p_el_001",
    formulaId: "el_add_carry",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "27 + 15는 얼마인가요?",
    choices: null,
    answer: "42",
    unit: "",
    explanation: "받아올림이 있는 덧셈은 일의 자리부터 더하고 10이 넘으면 윗자리로 올려줘요. 문제에서는 27과 15를 더해야 해요. 일의 자리 7 + 5 = 12이므로 2를 쓰고 1을 받아올린 뒤 십의 자리 2 + 1 + 1 = 4를 계산해요. 따라서 답은 42입니다.",
    hint: "일의 자리부터 더하고 10이 넘으면 윗자리로 올려 보세요."
  },
  {
    id: "p_el_002",
    formulaId: "el_add_carry",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "46 + 37은 얼마인가요?",
    choices: ["83", "73", "93", "82"],
    answer: "83",
    unit: "",
    explanation: "받아올림이 있는 덧셈은 일의 자리부터 더하는 것이 약속이에요. 문제에서는 46과 37이 주어졌어요. 일의 자리 6 + 7 = 13이므로 3을 쓰고 1을 올린 뒤 십의 자리 4 + 3 + 1 = 8을 계산해요. 따라서 답은 83입니다.",
    hint: "6 + 7부터 계산하고 받아올린 1을 잊지 마세요."
  },
  {
    id: "p_el_003",
    formulaId: "el_sub_borrow",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "32 - 17은 얼마인가요?",
    choices: null,
    answer: "15",
    unit: "",
    explanation: "받아내림이 있는 뺄셈은 윗자리가 작으면 윗자리에서 10을 빌려와 빼요. 문제에서는 32에서 17을 빼야 해요. 일의 자리 2는 7보다 작으므로 10을 빌려와 12 - 7 = 5를 계산해요. 십의 자리는 3이 2가 되었으므로 2 - 1 = 1이 되어 답은 15입니다.",
    hint: "일의 자리가 모자라면 십의 자리에서 10을 빌려와 보세요."
  },
  {
    id: "p_el_004",
    formulaId: "el_sub_borrow",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "54 - 28은 얼마인가요?",
    choices: ["26", "36", "24", "28"],
    answer: "26",
    unit: "",
    explanation: "받아내림이 있는 뺄셈은 윗자리에서 10을 빌려오는 것이 핵심이에요. 문제에서는 54에서 28을 빼야 해요. 일의 자리 4 - 8은 안 되므로 14 - 8 = 6을 계산해요. 십의 자리는 5가 4가 되었으므로 4 - 2 = 2가 되어 답은 26입니다.",
    hint: "14 - 8을 먼저 하고 십의 자리가 하나 작아진 것을 기억하세요."
  },
  {
    id: "p_el_005",
    formulaId: "el_mult_table",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "7 × 8은 얼마인가요?",
    choices: null,
    answer: "56",
    unit: "",
    explanation: "구구단은 같은 수를 여러 번 더한 결과를 외워서 빠르게 구해요. 문제에서는 7단의 7 × 8을 물어봐요. 7 × 8은 7을 8번 더한 것과 같아요. 차례로 세면 56이 되므로 답은 56입니다.",
    hint: "7단의 리듬을 떠올리며 7 × 8을 외워 보세요."
  },
  {
    id: "p_el_006",
    formulaId: "el_mult_table",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "6 × 9는 얼마인가요?",
    choices: ["54", "45", "63", "56"],
    answer: "54",
    unit: "",
    explanation: "구구단은 묶음으로 세는 곱셈을 빨리 해주는 표예요. 문제에서는 6단의 6 × 9가 주어졌어요. 6 × 9는 6을 9번 더한 것과 같아요. 계산하면 54이므로 답은 54입니다.",
    hint: "6을 9번 더한 값을 구하듯이 6 × 9를 떠올려 보세요."
  },
  {
    id: "p_el_007",
    formulaId: "el_division",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "17을 5로 나눈 몫과 나머지는 무엇인가요?",
    choices: null,
    answer: "몫 3, 나머지 2",
    unit: "",
    explanation: "나눗셈은 몫 × 나누는 수 + 나머지 = 나누어지는 수로 검산해요. 문제에서는 나누어지는 수 17과 나누는 수 5가 주어졌어요. 5 × 3 = 15이므로 몫은 3이고 17 - 15 = 2예요. 따라서 답은 몫 3, 나머지 2입니다.",
    hint: "5의 단에서 17을 넘지 않는 가장 큰 수를 찾아보세요."
  },
  {
    id: "p_el_008",
    formulaId: "el_division",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "23을 4로 나눈 몫과 나머지는 무엇인가요?",
    choices: ["몫 5, 나머지 3", "몫 5, 나머지 2", "몫 6, 나머지 1", "몫 4, 나머지 3"],
    answer: "몫 5, 나머지 3",
    unit: "",
    explanation: "나눗셈에서 나머지는 나누는 수보다 항상 작아야 해요. 문제에서는 23을 4로 나누어야 해요. 4 × 5 = 20이므로 몫은 5이고 23 - 20 = 3이에요. 따라서 답은 몫 5, 나머지 3입니다.",
    hint: "4 × 5 = 20을 떠올리고 23에서 빼 보세요."
  },
  {
    id: "p_el_009",
    formulaId: "el_order_ops",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "3 + 2 × 4는 얼마인가요?",
    choices: null,
    answer: "11",
    unit: "",
    explanation: "혼합 계산은 곱셈과 나눗셈을 덧셈과 뺄셈보다 먼저 해요. 문제에서는 3과 2 × 4가 주어졌어요. 먼저 2 × 4 = 8을 계산해요. 3 + 8 = 11이므로 답은 11입니다.",
    hint: "덧셈보다 곱셈을 먼저 계산해 보세요."
  },
  {
    id: "p_el_010",
    formulaId: "el_order_ops",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "4 + 6 ÷ 2는 얼마인가요?",
    choices: ["7", "5", "10", "8"],
    answer: "7",
    unit: "",
    explanation: "혼합 계산은 괄호 다음으로 곱셈과 나눗셈을 먼저 해요. 문제에서는 4와 6 ÷ 2가 주어졌어요. 먼저 6 ÷ 2 = 3을 계산해요. 4 + 3 = 7이므로 답은 7입니다.",
    hint: "앞에서부터가 아니라 나눗셈부터 먼저 해 보세요."
  },
  {
    id: "p_el_011",
    formulaId: "el_rounding",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "47을 십의 자리에서 반올림하면 얼마인가요?",
    choices: null,
    answer: "50",
    unit: "",
    explanation: "십의 자리에서 반올림할 때는 일의 자리가 5 이상이면 올려줘요. 문제에서는 47의 일의 자리 7을 살펴봐요. 7은 5보다 크므로 십의 자리를 올려요. 따라서 답은 50입니다.",
    hint: "일의 자리가 5보다 큰지 작은지 먼저 살펴보세요."
  },
  {
    id: "p_el_012",
    formulaId: "el_rounding",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "62를 십의 자리에서 반올림하면 얼마인가요?",
    choices: ["60", "70", "65", "50"],
    answer: "60",
    unit: "",
    explanation: "반올림은 정한 자리 다음 숫자가 4 이하면 버려줘요. 문제에서는 62의 일의 자리 2를 살펴봐요. 2는 4보다 작으므로 십의 자리를 그대로 두어요. 따라서 답은 60입니다.",
    hint: "일의 자리 2는 버리는 쪽인지 올리는 쪽인지 생각해 보세요."
  },
  {
    id: "p_el_013",
    formulaId: "el_place_value",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "10000000은 어떻게 읽나요?",
    choices: null,
    answer: "천만",
    unit: "",
    explanation: "큰 수는 뒤에서부터 네 자리씩 끊어 만과 억으로 읽어요. 문제에서는 0이 7개인 10000000이 주어졌어요. 네 자리씩 끊으면 1000만으로 나누어져요. 1000만은 천만이므로 답은 천만입니다.",
    hint: "뒤에서 네 자리씩 끊고 만의 자리를 찾아보세요."
  },
  {
    id: "p_el_014",
    formulaId: "el_place_value",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "100000000은 어떻게 읽나요?",
    choices: ["1억", "천만", "10억", "1조"],
    answer: "1억",
    unit: "",
    explanation: "큰 수는 10000씩 묶어 만과 억과 조로 읽어요. 문제에서는 0이 8개인 100000000이 주어졌어요. 뒤에서 네 자리씩 끊으면 억 단위에 1이 와요. 따라서 답은 1억입니다.",
    hint: "0의 개수를 세어 억의 자리인지 확인해 보세요."
  },
  {
    id: "p_el_015",
    formulaId: "el_time_calc",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "2시 50분에서 3시 20분까지는 몇 분인가요?",
    choices: null,
    answer: "30분",
    unit: "분",
    explanation: "걸린 시간은 끝 시각에서 시작 시각을 빼서 구해요. 문제에서는 시작 2시 50분과 끝 3시 20분이 주어졌어요. 20분에서 50분은 뺄 수 없으므로 1시간을 빌려와 80 - 50 = 30을 계산해요. 따라서 답은 30분입니다.",
    hint: "분이 모자라면 시간에서 1시간을 빌려 60분을 더해 보세요."
  },
  {
    id: "p_el_016",
    formulaId: "el_time_calc",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "4시 10분에서 5시 5분까지는 몇 분인가요?",
    choices: ["55분", "65분", "45분", "1시간 5분"],
    answer: "55분",
    unit: "분",
    explanation: "시간 계산은 1시간을 60분으로 바꾸어 생각해요. 문제에서는 시작 4시 10분과 끝 5시 5분이 주어졌어요. 5분을 65분으로 생각하면 65 - 10 = 55를 계산해요. 따라서 답은 55분입니다.",
    hint: "5시 5분의 분을 60분을 더한 65분으로 바꿔 보세요."
  },
  {
    id: "p_el_017",
    formulaId: "el_fraction_mean",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "사과 1개를 똑같이 4등분한 것 중 1조각은 어떻게 나타내나요?",
    choices: null,
    answer: "4분의 1",
    unit: "",
    explanation: "분수는 전체를 똑같이 나눈 것 중 몇 개인지 나타내요. 문제에서는 전체를 4등분했으므로 분모는 4예요. 가져간 조각은 1개이므로 분자는 1이에요. 따라서 답은 4분의 1입니다.",
    hint: "전체를 몇 조각으로 나누었는지 먼저 세어 보세요."
  },
  {
    id: "p_el_018",
    formulaId: "el_fraction_mean",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "초콜릿 1개를 똑같이 5등분한 것 중 3조각은 어떻게 나타내나요?",
    choices: ["5분의 3", "3분의 5", "5분의 2", "3분의 1"],
    answer: "5분의 3",
    unit: "",
    explanation: "분수에서 아래 수는 전체 조각 수이고 위 수는 가져간 조각 수예요. 문제에서는 전체 5조각 중 3조각이 주어졌어요. 분모는 5이고 분자는 3이에요. 따라서 답은 5분의 3입니다.",
    hint: "아래에는 전체 조각 수, 위에는 가져간 수를 써 보세요."
  },
  {
    id: "p_el_019",
    formulaId: "el_equiv_fraction",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "2/3와 크기가 같고 분모가 6인 분수는 무엇인가요?",
    choices: null,
    answer: "4/6",
    unit: "",
    explanation: "크기가 같은 분수는 분모와 분자에 같은 수를 곱해서 만들어요. 문제에서는 2/3를 분모가 6이 되게 바꾸어야 해요. 분모 3에 2를 곱했으므로 분자에도 2를 곱해요. 2 × 2 = 4이므로 답은 4/6입니다.",
    hint: "분모를 3에서 6으로 만드는 수를 분자에도 곱해 보세요."
  },
  {
    id: "p_el_020",
    formulaId: "el_equiv_fraction",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "1/2와 크기가 같고 분모가 4인 분수는 무엇인가요?",
    choices: ["2/4", "1/4", "3/4", "4/2"],
    answer: "2/4",
    unit: "",
    explanation: "분모와 분자에 같은 수를 곱해도 분수의 크기는 그대로예요. 문제에서는 1/2를 분모가 4인 분수로 바꾸어야 해요. 분모 2에 2를 곱했으므로 분자 1에도 2를 곱해요. 따라서 답은 2/4입니다.",
    hint: "위와 아래에 똑같이 2를 곱해 보세요."
  },
  {
    id: "p_el_021",
    formulaId: "el_fraction_add",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "2/5 + 1/5는 얼마인가요?",
    choices: null,
    answer: "3/5",
    unit: "",
    explanation: "분모가 같은 분수는 분자끼리만 더하고 분모는 그대로 두어요. 문제에서는 분모가 5로 같아요. 분자 2 + 1 = 3을 계산해요. 분모 5를 그대로 쓰므로 답은 3/5입니다.",
    hint: "조각 크기는 그대로 두고 조각 개수만 더해 보세요."
  },
  {
    id: "p_el_022",
    formulaId: "el_fraction_add",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "4/7 - 2/7은 얼마인가요?",
    choices: ["2/7", "6/7", "2/5", "4/7"],
    answer: "2/7",
    unit: "",
    explanation: "분모가 같은 뺄셈은 분자끼리만 빼는 것이 약속이에요. 문제에서는 분모가 7로 같아요. 분자 4 - 2 = 2를 계산해요. 분모 7을 그대로 쓰므로 답은 2/7입니다.",
    hint: "분모는 그대로 두고 4 - 2만 계산해 보세요."
  },
  {
    id: "p_el_023",
    formulaId: "el_decimal_mean",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "0.3을 분수로 나타내면 무엇인가요?",
    choices: null,
    answer: "10분의 3",
    unit: "",
    explanation: "소수 첫째 자리는 1을 10등분한 것 중 몇 개인지 나타내요. 문제에서는 소수 0.3이 주어졌어요. 0.3은 10등분한 것 중 3칸이에요. 따라서 답은 10분의 3입니다.",
    hint: "소수점 아래 첫째 자리는 10분의 몇인지 떠올려 보세요."
  },
  {
    id: "p_el_024",
    formulaId: "el_decimal_mean",
    schoolLevel: "elementary",
    gradeLevel: "elementary3",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "0.07을 분수로 나타내면 무엇인가요?",
    choices: ["100분의 7", "10분의 7", "7", "10분의 70"],
    answer: "100분의 7",
    unit: "",
    explanation: "소수 둘째 자리는 1을 100등분한 것 중 몇 개인지 나타내요. 문제에서는 소수 0.07이 주어졌어요. 0.07은 100등분한 것 중 7칸이에요. 따라서 답은 100분의 7입니다.",
    hint: "소수점 아래 둘째 자리는 100분의 몇인지 생각해 보세요."
  },
  {
    id: "p_el_025",
    formulaId: "el_frac_decimal",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "3/4을 소수로 바꾸면 얼마인가요?",
    choices: null,
    answer: "0.75",
    unit: "",
    explanation: "분수를 소수로 바꾸려면 분자 ÷ 분모를 계산해요. 문제에서는 분자 3과 분모 4가 주어졌어요. 3 ÷ 4를 계산하면 0.75가 나와요. 따라서 답은 0.75입니다.",
    hint: "3 ÷ 4를 세로로 나누어 소수까지 구해 보세요."
  },
  {
    id: "p_el_026",
    formulaId: "el_frac_decimal",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "1/4을 소수로 바꾸면 얼마인가요?",
    choices: ["0.25", "0.4", "0.14", "2.5"],
    answer: "0.25",
    unit: "",
    explanation: "분수는 분자를 분모로 나눈 것과 같은 값이에요. 문제에서는 1/4이 주어졌어요. 1 ÷ 4를 계산하면 0.25가 나와요. 따라서 답은 0.25입니다.",
    hint: "1 ÷ 4를 계산하면 0보다 작은 수가 나와요."
  },
  {
    id: "p_el_027",
    formulaId: "el_decimal_add",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "0.45 + 0.3은 얼마인가요?",
    choices: null,
    answer: "0.75",
    unit: "",
    explanation: "소수의 덧셈은 소수점을 맞추고 자릿값끼리 더해요. 문제에서는 0.45와 0.3이 주어졌어요. 0.3을 0.30으로 생각하면 45 + 30 = 75처럼 계산해요. 소수점을 맞추어 찍으면 답은 0.75입니다.",
    hint: "소수점을 세로로 맞추고 빈자리는 0으로 채워 보세요."
  },
  {
    id: "p_el_028",
    formulaId: "el_decimal_add",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "0.8 - 0.25는 얼마인가요?",
    choices: ["0.55", "0.65", "0.45", "1.05"],
    answer: "0.55",
    unit: "",
    explanation: "소수의 뺄셈은 소수점 위치를 맞추는 것이 가장 중요해요. 문제에서는 0.8과 0.25가 주어졌어요. 0.8을 0.80으로 생각하면 80 - 25 = 55처럼 계산해요. 소수점을 그대로 내려 찍으면 답은 0.55입니다.",
    hint: "0.8을 0.80으로 바꾸어 자릿수를 맞추어 보세요."
  },
  {
    id: "p_el_029",
    formulaId: "el_mixed_number",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "fractions",
    level: 1,
    type: "input",
    question: "2와 1/3을 가분수로 바꾸면 무엇인가요?",
    choices: null,
    answer: "7/3",
    unit: "",
    explanation: "대분수를 가분수로 바꾸려면 자연수와 분모를 곱한 뒤 분자를 더해요. 문제에서는 자연수 2와 분수 1/3이 주어졌어요. 2 × 3 = 6에 분자 1을 더하면 7이에요. 분모 3은 그대로 두므로 답은 7/3입니다.",
    hint: "2 × 3을 먼저 하고 1을 더해 분자로 써 보세요."
  },
  {
    id: "p_el_030",
    formulaId: "el_mixed_number",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "fractions",
    level: 2,
    type: "choice",
    question: "1과 3/4을 가분수로 바꾸면 무엇인가요?",
    choices: ["7/4", "4/7", "5/4", "7/3"],
    answer: "7/4",
    unit: "",
    explanation: "가분수는 분자가 분모보다 큰 분수로 조각을 모두 풀어 센 모습이에요. 문제에서는 자연수 1과 분수 3/4이 주어졌어요. 1 × 4 = 4에 분자 3을 더하면 7이에요. 따라서 답은 7/4입니다.",
    hint: "1 × 4 + 3을 계산해 분자로 쓰고 분모는 그대로 두세요."
  },
  {
    id: "p_el_031",
    formulaId: "el_rect_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "가로가 6cm, 세로가 4cm인 직사각형의 넓이는 얼마인가요?",
    choices: null,
    answer: "24㎠",
    unit: "㎠",
    explanation: "직사각형의 넓이는 가로 × 세로로 구해요. 문제에서는 가로 6cm와 세로 4cm가 주어졌어요. 식에 넣으면 6 × 4가 되어요. 계산하면 24이므로 답은 24㎠입니다.",
    hint: "직사각형 넓이는 가로와 세로를 곱해요. 먼저 공식부터 떠올려 봐요."
  },
  {
    id: "p_el_032",
    formulaId: "el_rect_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "가로가 7cm, 세로가 4cm인 직사각형의 넓이는 얼마인가요?",
    choices: ["28㎠", "22㎠", "24㎠", "32㎠"],
    answer: "28㎠",
    unit: "㎠",
    explanation: "직사각형의 넓이는 가로 × 세로예요. 문제에서는 가로 7cm와 세로 4cm가 주어졌어요. 7 × 4를 계산하면 28이 되어요. 따라서 답은 28㎠입니다.",
    hint: "7 × 4를 계산해 보세요. 단위는 ㎠예요."
  },
  {
    id: "p_el_033",
    formulaId: "el_square_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "한 변이 9cm인 정사각형의 넓이는 얼마인가요?",
    choices: null,
    answer: "81㎠",
    unit: "㎠",
    explanation: "정사각형의 넓이는 한 변 × 한 변으로 구해요. 문제에서는 한 변이 9cm로 주어졌어요. 식에 넣으면 9 × 9가 되어요. 계산하면 81이므로 답은 81㎠입니다.",
    hint: "정사각형은 한 변을 두 번 곱해요. 9 × 9를 떠올려 보세요."
  },
  {
    id: "p_el_034",
    formulaId: "el_square_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "한 변이 6cm인 정사각형의 넓이는 얼마인가요?",
    choices: ["36㎠", "24㎠", "30㎠", "42㎠"],
    answer: "36㎠",
    unit: "㎠",
    explanation: "정사각형은 가로와 세로 길이가 똑같은 도형이에요. 문제에서는 한 변이 6cm로 주어졌어요. 6 × 6을 계산하면 36이 되어요. 따라서 답은 36㎠입니다.",
    hint: "6 × 6을 계산하고 단위로 ㎠를 붙여 보세요."
  },
  {
    id: "p_el_035",
    formulaId: "el_triangle_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "밑변이 8cm, 높이가 5cm인 삼각형의 넓이는 얼마인가요?",
    choices: null,
    answer: "20㎠",
    unit: "㎠",
    explanation: "삼각형의 넓이는 밑변 × 높이 ÷ 2로 구해요. 문제에서는 밑변 8cm와 높이 5cm가 주어졌어요. 식에 넣으면 8 × 5 ÷ 2가 되어요. 40 ÷ 2 = 20이므로 답은 20㎠입니다.",
    hint: "밑변과 높이를 곱한 뒤 꼭 2로 나누어 보세요."
  },
  {
    id: "p_el_036",
    formulaId: "el_triangle_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "밑변이 6cm, 높이가 4cm인 삼각형의 넓이는 얼마인가요?",
    choices: ["12㎠", "24㎠", "10㎠", "20㎠"],
    answer: "12㎠",
    unit: "㎠",
    explanation: "삼각형은 같은 직사각형을 반으로 나눈 넓이와 같아요. 문제에서는 밑변 6cm와 높이 4cm가 주어졌어요. 6 × 4 = 24를 먼저 계산해요. 24 ÷ 2 = 12이므로 답은 12㎠입니다.",
    hint: "6 × 4를 한 뒤 반으로 나누는 것을 잊지 마세요."
  },
  {
    id: "p_el_037",
    formulaId: "el_parallelogram_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "밑변이 7cm, 높이가 4cm인 평행사변형의 넓이는 얼마인가요?",
    choices: null,
    answer: "28㎠",
    unit: "㎠",
    explanation: "평행사변형의 넓이는 밑변 × 높이로 구해요. 문제에서는 밑변 7cm와 높이 4cm가 주어졌어요. 식에 넣으면 7 × 4가 되어요. 계산하면 28이므로 답은 28㎠입니다.",
    hint: "평행사변형은 밑변과 높이를 곱하기만 해 보세요."
  },
  {
    id: "p_el_038",
    formulaId: "el_parallelogram_area",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "밑변이 5cm, 높이가 6cm인 평행사변형의 넓이는 얼마인가요?",
    choices: ["30㎠", "15㎠", "22㎠", "60㎠"],
    answer: "30㎠",
    unit: "㎠",
    explanation: "평행사변형은 삐딱한 조각을 옮기면 직사각형이 되어 넓이가 같아요. 문제에서는 밑변 5cm와 높이 6cm가 주어졌어요. 5 × 6을 계산하면 30이 되어요. 따라서 답은 30㎠입니다.",
    hint: "빗변이 아니라 밑변에 수직인 높이를 골라 곱해 보세요."
  },
  {
    id: "p_el_039",
    formulaId: "el_rect_perimeter",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "가로가 8cm, 세로가 5cm인 직사각형의 둘레는 몇 cm인가요?",
    choices: null,
    answer: "26cm",
    unit: "cm",
    explanation: "직사각형의 둘레는 (가로 + 세로) × 2로 구해요. 문제에서는 가로 8cm와 세로 5cm가 주어졌어요. 식에 넣으면 (8 + 5) × 2가 되어요. 13 × 2 = 26이므로 답은 26cm입니다.",
    hint: "가로와 세로를 먼저 더한 뒤 두 배를 해 보세요."
  },
  {
    id: "p_el_040",
    formulaId: "el_rect_perimeter",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "가로가 7cm, 세로가 5cm인 직사각형의 둘레는 몇 cm인가요?",
    choices: ["24cm", "35cm", "12cm", "26cm"],
    answer: "24cm",
    unit: "cm",
    explanation: "직사각형의 둘레는 바깥을 한 바퀴 돈 길이를 말해요. 문제에서는 가로 7cm와 세로 5cm가 주어졌어요. 7 + 5 = 12를 먼저 계산해요. 12 × 2 = 24이므로 답은 24cm입니다.",
    hint: "둘레는 넓이가 아니에요. 네 변을 모두 더하는 셈으로 구해 보세요."
  },
  {
    id: "p_el_041",
    formulaId: "el_circle_parts",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "반지름이 7cm인 원의 지름은 몇 cm인가요?",
    choices: null,
    answer: "14cm",
    unit: "cm",
    explanation: "원의 지름은 반지름 × 2로 구해요. 문제에서는 반지름 7cm가 주어졌어요. 식에 넣으면 7 × 2가 되어요. 계산하면 14이므로 답은 14cm입니다.",
    hint: "지름은 반지름의 두 배예요. 7 × 2를 해 보세요."
  },
  {
    id: "p_el_042",
    formulaId: "el_circle_parts",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "지름이 10cm인 원의 반지름은 몇 cm인가요?",
    choices: ["5cm", "10cm", "20cm", "15cm"],
    answer: "5cm",
    unit: "cm",
    explanation: "반지름은 원의 중심에서 가장자리까지의 거리로 지름의 절반이에요. 문제에서는 지름 10cm가 주어졌어요. 10 ÷ 2를 계산하면 5가 되어요. 따라서 답은 5cm입니다.",
    hint: "지름을 반으로 나누면 반지름이 돼요. 10 ÷ 2를 해 보세요."
  },
  {
    id: "p_el_043",
    formulaId: "el_box_volume",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "가로가 4cm, 세로가 3cm, 높이가 5cm인 상자의 부피는 얼마인가요?",
    choices: null,
    answer: "60㎤",
    unit: "㎤",
    explanation: "직육면체의 부피는 가로 × 세로 × 높이로 구해요. 문제에서는 가로 4cm와 세로 3cm와 높이 5cm가 주어졌어요. 식에 넣으면 4 × 3 × 5가 되어요. 12 × 5 = 60이므로 답은 60㎤입니다.",
    hint: "바닥 넓이를 먼저 구하고 높이를 곱해 보세요."
  },
  {
    id: "p_el_044",
    formulaId: "el_box_volume",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "가로가 2cm, 세로가 3cm, 높이가 4cm인 상자의 부피는 얼마인가요?",
    choices: ["24㎤", "12㎤", "18㎤", "29㎤"],
    answer: "24㎤",
    unit: "㎤",
    explanation: "부피는 바닥에 깔리는 칸 수에 층수를 곱한 것과 같아요. 문제에서는 가로 2cm와 세로 3cm와 높이 4cm가 주어졌어요. 2 × 3 = 6에 4를 곱하면 24가 되어요. 따라서 답은 24㎤입니다.",
    hint: "2 × 3 × 4를 순서대로 곱하고 단위로 ㎤를 붙여 보세요."
  },
  {
    id: "p_el_045",
    formulaId: "el_angle",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "반듯하게 벌어진 직각은 몇 도인가요?",
    choices: null,
    answer: "90°",
    unit: "°",
    explanation: "각은 벌어진 정도를 도 단위로 재고 직각은 90도로 정해져 있어요. 문제에서는 반듯하게 벌어진 직각을 물어봐요. 각도기로 재면 90도를 가리켜요. 따라서 답은 90°입니다.",
    hint: "각도기의 반듯한 모서리를 떠올리며 직각의 도수를 말해 보세요."
  },
  {
    id: "p_el_046",
    formulaId: "el_angle",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "100°인 각은 예각과 직각과 둔각 중 무엇인가요?",
    choices: ["둔각", "직각", "예각", "평각"],
    answer: "둔각",
    unit: "",
    explanation: "각은 90도보다 작으면 예각이고 크면 둔각이라고 해요. 문제에서는 100°가 주어졌어요. 100°는 90°보다 커요. 따라서 답은 둔각입니다.",
    hint: "90°보다 큰 각은 둔각이에요. 100°와 비교해 보세요."
  },
  {
    id: "p_el_047",
    formulaId: "el_symmetry",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "하트 모양을 가운데 세로선으로 접어 완전히 겹쳐지면 무엇이라고 하나요?",
    choices: null,
    answer: "선대칭 도형이다",
    unit: "",
    explanation: "접었을 때 포개어지면 선대칭 도형이라고 해요. 문제에서는 하트 모양과 가운데 세로선이 주어졌어요. 선을 따라 접는다고 상상하면 왼쪽과 오른쪽이 겹쳐져요. 따라서 답은 선대칭 도형이다입니다.",
    hint: "접어서 겹쳐지면 선대칭이에요. 하트를 반으로 접어 보세요."
  },
  {
    id: "p_el_048",
    formulaId: "el_symmetry",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "평행사변형을 한 점을 중심으로 180도 돌렸을 때 원래 모양과 겹쳐지면 무엇인가요?",
    choices: ["점대칭", "선대칭", "대칭이 아니다", "선대칭도 되고 점대칭도 된다"],
    answer: "점대칭",
    unit: "",
    explanation: "한 점을 중심으로 180도 돌려 겹쳐지면 점대칭 도형이라고 해요. 문제에서는 평행사변형을 180도 돌리는 상황이 주어졌어요. 돌린 모양이 원래 모양과 정확히 겹쳐져요. 따라서 답은 점대칭입니다.",
    hint: "돌려서 겹쳐지면 점대칭이에요. 180도 돌린 모습을 떠올려 보세요."
  },
  {
    id: "p_el_049",
    formulaId: "el_average",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "ratio",
    level: 1,
    type: "input",
    question: "사탕 6개와 8개와 10개를 똑같이 나누면 한 몫은 몇 개인가요?",
    choices: null,
    answer: "8개",
    unit: "개",
    explanation: "평균은 모두 합한 뒤 개수로 나누어 구해요. 문제에서는 6개와 8개와 10개가 주어졌어요. 합은 6 + 8 + 10 = 24예요. 24 ÷ 3 = 8이므로 답은 8개입니다.",
    hint: "모두 더한 뒤 3으로 나누어 평균을 구해 보세요."
  },
  {
    id: "p_el_050",
    formulaId: "el_average",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "ratio",
    level: 2,
    type: "choice",
    question: "시험 점수 70점과 80점과 90점의 평균은 몇 점인가요?",
    choices: ["80점", "70점", "90점", "85점"],
    answer: "80점",
    unit: "점",
    explanation: "평균은 전체 합을 개수로 나눈 대표값이에요. 문제에서는 70점과 80점과 90점이 주어졌어요. 합은 70 + 80 + 90 = 240예요. 240 ÷ 3 = 80이므로 답은 80점입니다.",
    hint: "세 점수를 모두 더하고 3으로 나누어 보세요."
  },
  {
    id: "p_el_051",
    formulaId: "el_ratio",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "ratio",
    level: 1,
    type: "input",
    question: "전체 25명 중 모범생이 5명일 때 비율과 백분율은 무엇인가요?",
    choices: null,
    answer: "0.2, 20%",
    unit: "",
    explanation: "비율은 비교하는 양 ÷ 기준량으로 구하고 백분율은 100을 곱해요. 문제에서는 기준량 25명과 비교하는 양 5명이 주어졌어요. 5 ÷ 25 = 0.2이고 100을 곱하면 20%예요. 따라서 답은 0.2, 20%입니다.",
    hint: "5 ÷ 25를 계산하고 100을 곱해 백분율로 바꾸어 보세요."
  },
  {
    id: "p_el_052",
    formulaId: "el_ratio",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "ratio",
    level: 2,
    type: "choice",
    question: "10문제 중 7문제를 맞혔을 때 정답 비율과 백분율은 무엇인가요?",
    choices: ["0.7, 70%", "0.3, 30%", "0.7, 7%", "7, 70%"],
    answer: "0.7, 70%",
    unit: "",
    explanation: "비율은 기준량을 1로 볼 때 비교하는 양이 몇 배인지 나타내요. 문제에서는 기준량 10문제와 맞힌 7문제가 주어졌어요. 7 ÷ 10 = 0.7이고 백분율로는 70%예요. 따라서 답은 0.7, 70%입니다.",
    hint: "7 ÷ 10을 하고 뒤에 %를 붙이려면 100을 곱해 보세요."
  },
  {
    id: "p_el_053",
    formulaId: "el_speed",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "ratio",
    level: 1,
    type: "input",
    question: "2시간에 100km를 간 자동차의 속력은 시속 몇 km인가요?",
    choices: null,
    answer: "시속 50km",
    unit: "km",
    explanation: "속력은 거리 ÷ 시간으로 1시간당 간 거리를 구해요. 문제에서는 거리 100km와 시간 2시간이 주어졌어요. 식에 넣으면 100 ÷ 2가 되어요. 계산하면 50이므로 답은 시속 50km입니다.",
    hint: "거리를 시간으로 나누면 속력이 나와요. 100 ÷ 2를 해 보세요."
  },
  {
    id: "p_el_054",
    formulaId: "el_speed",
    schoolLevel: "elementary",
    gradeLevel: "elementary5",
    topic: "ratio",
    level: 2,
    type: "choice",
    question: "3시간에 90km를 간 기차의 속력은 시속 몇 km인가요?",
    choices: ["시속 30km", "시속 27km", "시속 33km", "시속 90km"],
    answer: "시속 30km",
    unit: "km",
    explanation: "속력은 일정한 시간 동안 이동한 거리로 얼마나 빠른지 나타내요. 문제에서는 거리 90km와 시간 3시간이 주어졌어요. 90 ÷ 3을 계산하면 30이 되어요. 따라서 답은 시속 30km입니다.",
    hint: "90 ÷ 3을 계산하고 앞에 시속을 붙여 보세요."
  },
  {
    id: "p_el_055",
    formulaId: "el_money",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "1000원을 내고 600원짜리 지우개를 사면 거스름돈은 얼마인가요?",
    choices: null,
    answer: "400원",
    unit: "원",
    explanation: "거스름돈은 낸 돈 - 물건값으로 구해요. 문제에서는 낸 돈 1000원과 물건값 600원이 주어졌어요. 식에 넣으면 1000 - 600이 되어요. 계산하면 400이므로 답은 400원입니다.",
    hint: "낸 돈에서 물건값을 빼 보세요. 1000 - 600을 떠올려 보세요."
  },
  {
    id: "p_el_056",
    formulaId: "el_money",
    schoolLevel: "elementary",
    gradeLevel: "elementary2",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "500원을 내고 350원짜리 과자를 사면 거스름돈은 얼마인가요?",
    choices: ["150원", "200원", "250원", "100원"],
    answer: "150원",
    unit: "원",
    explanation: "거스름돈은 낸 돈에서 물건값을 빼면 나와요. 문제에서는 낸 돈 500원과 물건값 350원이 주어졌어요. 500 - 350을 계산하면 150이 되어요. 따라서 답은 150원입니다.",
    hint: "500 - 350을 일의 자리부터 받아내림으로 계산해 보세요."
  },
  {
    id: "p_el_057",
    formulaId: "el_probability_easy",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "statistics",
    level: 1,
    type: "input",
    question: "동전을 한 번 던져 앞면이 나올 가능성을 말하면 무엇인가요?",
    choices: null,
    answer: "반반",
    unit: "",
    explanation: "가능성은 확실과 불가능과 가능과 반반으로 말해요. 문제에서는 앞면과 뒷면 두 가지 경우가 주어졌어요. 어느 쪽도 유리하지 않고 절반씩 가능해요. 따라서 답은 반반입니다.",
    hint: "앞면과 뒷면이 똑같이 나올 때는 반반이라고 말해 보세요."
  },
  {
    id: "p_el_058",
    formulaId: "el_probability_easy",
    schoolLevel: "elementary",
    gradeLevel: "elementary6",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "주머니에 빨간 공만 들어 있을 때 빨간 공이 나올 가능성은 무엇인가요?",
    choices: ["확실", "불가능", "반반", "매우 불가능"],
    answer: "확실",
    unit: "",
    explanation: "반드시 일어나면 확실이라고 말하고 절대 안 일어나면 불가능이라고 해요. 문제에서는 주머니에 빨간 공만 들어 있어요. 무엇을 꺼내도 빨간 공이 나와요. 따라서 답은 확실입니다.",
    hint: "다른 색 공이 없으면 빨간 공은 반드시 나와요."
  },
  {
    id: "p_el_059",
    formulaId: "el_pattern",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 1,
    type: "input",
    question: "3, 6, 9 다음에 올 수는 무엇인가요?",
    choices: null,
    answer: "12",
    unit: "",
    explanation: "규칙 찾기는 앞뒤 수의 차이가 일정한지 살펴봐요. 문제에서는 3과 6과 9가 주어졌어요. 6 - 3 = 3이고 9 - 6 = 3으로 3씩 커져요. 9 + 3 = 12이므로 답은 12입니다.",
    hint: "앞뒤 수의 차이가 얼마인지 구하고 마지막 수에 더해 보세요."
  },
  {
    id: "p_el_060",
    formulaId: "el_pattern",
    schoolLevel: "elementary",
    gradeLevel: "elementary4",
    topic: "arithmetic",
    level: 2,
    type: "choice",
    question: "5, 10, 15 다음에 올 수는 무엇인가요?",
    choices: ["20", "18", "25", "16"],
    answer: "20",
    unit: "",
    explanation: "수 배열의 규칙은 앞뒤 차에서 찾을 수 있어요. 문제에서는 5와 10과 15가 주어졌어요. 10 - 5 = 5이고 15 - 10 = 5로 5씩 커져요. 15 + 5 = 20이므로 답은 20입니다.",
    hint: "5씩 커지는 규칙을 떠올리며 15 + 5를 해 보세요."
  }
];
