/* ============================================================
   수학아 놀자 (math) - 중등 문제 70개 (problem-mi.js)
   problem-data.js 가 합쳐서 window.MathProblemData 로 만듭니다.
   ============================================================ */
window.MathProblemMi = [
  {
    id: "p_mi_001",
    formulaId: "mi_signed_add",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "(+3) + (+7)의 값은?",
    choices: null,
    answer: "10",
    unit: "",
    explanation: "부호가 같은 덧셈은 숫자를 더하고 공통 부호를 붙이는 공식이에요. 주어진 두 수는 모두 플러스이므로 3 더하기 7을 계산해요. 3 더하기 7은 10이므로 답은 10입니다.",
    hint: "부호가 같으면 숫자를 더하고 그 부호를 붙여 보세요."
  },
  {
    id: "p_mi_002",
    formulaId: "mi_signed_add",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "(-5) + (+9)의 값은?",
    choices: ["-14", "-4", "4", "14"],
    answer: "4",
    unit: "",
    explanation: "부호가 다른 덧셈은 큰 수에서 작은 수를 빼고 큰 수의 부호를 따르는 공식이에요. 주어진 수는 마이너스 5와 플러스 9이므로 9 빼기 5를 계산해요. 9 빼기 5는 4이고 큰 수가 플러스이므로 답은 4입니다.",
    hint: "큰 수에서 작은 수를 빼고 큰 수의 부호를 붙여 보세요."
  },
  {
    id: "p_mi_003",
    formulaId: "mi_signed_mul",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "(-3) × (-4)의 값은?",
    choices: null,
    answer: "12",
    unit: "",
    explanation: "부호가 같은 곱셈은 답이 플러스가 되는 공식이에요. 주어진 두 수는 모두 마이너스이므로 답의 부호는 플러스로 정해요. 3 곱하기 4는 12이므로 답은 12입니다.",
    hint: "부호가 같으면 플러스로 정하고 숫자만 곱해 보세요."
  },
  {
    id: "p_mi_004",
    formulaId: "mi_signed_mul",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "(-4) × (+3)의 값은?",
    choices: ["-12", "-7", "7", "12"],
    answer: "-12",
    unit: "",
    explanation: "부호가 다른 곱셈은 답이 마이너스가 되는 공식이에요. 주어진 수는 마이너스와 플러스이므로 답의 부호는 마이너스로 정해요. 4 곱하기 3은 12이므로 답은 마이너스 12입니다.",
    hint: "부호가 다르면 마이너스로 정하고 숫자만 곱해 보세요."
  },
  {
    id: "p_mi_005",
    formulaId: "mi_expression",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "한 개에 1000원인 우유 x개의 가격을 식으로 나타내면?",
    choices: null,
    answer: "1000x",
    unit: "원",
    explanation: "수와 문자의 곱은 곱하기를 생략하고 수를 앞에 쓰는 공식이에요. 주어진 값은 1000과 문자 엑스이므로 1000 곱하기 엑스로 시작해요. 기호를 생략하면 1000엑스이므로 답은 1000엑스입니다.",
    hint: "곱하기 기호를 빼고 숫자를 문자 앞에 붙여 보세요."
  },
  {
    id: "p_mi_006",
    formulaId: "mi_expression",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "a를 5로 나눈 식을 간단히 나타낸 것은?",
    choices: ["5a", "5분의 a", "a 빼기 5", "a 더하기 5"],
    answer: "5분의 a",
    unit: "",
    explanation: "문자의 나눗셈은 분수 모양으로 바꾸는 공식이에요. 주어진 식은 에이를 5로 나누므로 분모를 5로 놓아요. 분자를 에이로 놓으면 5분의 에이이므로 답은 5분의 에이입니다.",
    hint: "나누기는 분수로 바꾸고 나누는 수를 분모에 놓아 보세요."
  },
  {
    id: "p_mi_007",
    formulaId: "mi_like_terms",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "3x + 7x를 간단히 하면?",
    choices: null,
    answer: "10x",
    unit: "",
    explanation: "동류항은 문자와 차수가 같은 항끼리 모아 계수만 더하는 공식이에요. 주어진 항은 3엑스와 7엑스이므로 계수 3과 7을 더해요. 3 더하기 7은 10이므로 답은 10엑스입니다.",
    hint: "같은 문자끼리 모아서 앞의 숫자만 더해 보세요."
  },
  {
    id: "p_mi_008",
    formulaId: "mi_like_terms",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "5a + 3b - 2a를 간단히 하면?",
    choices: ["6a", "3a + 3b", "6ab", "8a + 3b"],
    answer: "3a + 3b",
    unit: "",
    explanation: "동류항 정리는 같은 문자끼리만 모아 계산하는 공식이에요. 주어진 식에서 5에이와 마이너스 2에이는 동류항이므로 정리해요. 5 빼기 2는 3이므로 답은 3에이 더하기 3비입니다.",
    hint: "에이끼리 먼저 정리하고 비는 그대로 두어 보세요."
  },
  {
    id: "p_mi_009",
    formulaId: "mi_linear_eq",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "x + 7 = 15일 때 x의 값은?",
    choices: null,
    answer: "8",
    unit: "",
    explanation: "일차방정식은 이항으로 푸는 공식이에요. 주어진 식에서 더하기 7을 오른쪽으로 넘기면 빼기 7이 돼요. 15 빼기 7은 8이므로 답은 8입니다.",
    hint: "더하기 7을 오른쪽으로 넘겨서 빼기로 바꾸어 보세요."
  },
  {
    id: "p_mi_010",
    formulaId: "mi_linear_eq",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "3x - 4 = 11일 때 x의 값은?",
    choices: ["3", "5", "7", "15"],
    answer: "5",
    unit: "",
    explanation: "일차방정식은 이항한 뒤 양변을 나누는 공식이에요. 주어진 식에서 빼기 4를 넘기면 3엑스는 15가 돼요. 양변을 3으로 나누면 5이므로 답은 5입니다.",
    hint: "빼기 4를 먼저 넘기고 양변을 3으로 나누어 보세요."
  },
  {
    id: "p_mi_011",
    formulaId: "mi_eq_bracket",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 1,
    type: "input",
    question: "2(x + 3) = 12일 때 x의 값은?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "괄호가 있는 방정식은 분배법칙으로 괄호를 먼저 푸는 공식이에요. 주어진 식에 2를 분배하면 2엑스 더하기 6은 12가 돼요. 6을 넘기면 2엑스는 6이므로 답은 3입니다.",
    hint: "앞의 2를 괄호 안의 모든 항에 곱해 보세요."
  },
  {
    id: "p_mi_012",
    formulaId: "mi_eq_bracket",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "3(x - 2) = 15일 때 x의 값은?",
    choices: ["5", "6", "7", "9"],
    answer: "7",
    unit: "",
    explanation: "괄호가 있는 방정식은 괄호를 풀고 이항하는 공식이에요. 주어진 식에 3을 분배하면 3엑스 빼기 6은 15가 돼요. 6을 넘기면 3엑스는 21이므로 답은 7입니다.",
    hint: "3을 두 항에 모두 곱한 뒤 빼기 6을 넘겨 보세요."
  },
  {
    id: "p_mi_013",
    formulaId: "mi_transpose",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "2x + y = 12를 y에 대해 풀면?",
    choices: null,
    answer: "y = -2x + 12",
    unit: "",
    explanation: "등식의 변형은 원하는 문자를 남기고 나머지를 이항하는 공식이에요. 주어진 식에서 와이를 남기려면 2엑스를 오른쪽으로 넘겨요. 2엑스를 넘기면 빼기가 되므로 답은 와이는 마이너스 2엑스 더하기 12입니다.",
    hint: "와이를 남기고 2엑스를 오른쪽으로 넘겨 보세요."
  },
  {
    id: "p_mi_014",
    formulaId: "mi_transpose",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "x + 2y = 10을 x에 대해 풀면?",
    choices: ["x = -2y + 10", "x = 2y + 10", "x = 2y - 10", "x = -2y - 10"],
    answer: "x = -2y + 10",
    unit: "",
    explanation: "등식의 변형은 구하려는 문자를 한쪽에 남기는 공식이에요. 주어진 식에서 엑스를 남기려면 2와이를 오른쪽으로 넘겨요. 2와이를 넘기면 빼기가 되므로 답은 엑스는 마이너스 2와이 더하기 10입니다.",
    hint: "엑스를 남기고 2와이를 오른쪽으로 넘겨 보세요."
  },
  {
    id: "p_mi_015",
    formulaId: "mi_inequality",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "-2x < 8의 해는?",
    choices: null,
    answer: "x > -4",
    unit: "",
    explanation: "일차부등식은 음수로 나누면 부등호 방향이 바뀌는 공식이에요. 주어진 식의 양변을 마이너스 2로 나누려고 해요. 음수로 나누므로 작은 기호가 큰 기호로 바뀌어 답은 엑스는 마이너스 4보다 큽니다.",
    hint: "마이너스 2로 나눈 뒤 부등호 방향을 뒤집어 보세요."
  },
  {
    id: "p_mi_016",
    formulaId: "mi_inequality",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "-3x + 2 ≥ 11의 해는?",
    choices: ["x ≥ -3", "x ≤ -3", "x ≥ 3", "x ≤ 3"],
    answer: "x ≤ -3",
    unit: "",
    explanation: "일차부등식은 정리한 뒤 음수로 나누면 방향을 바꾸는 공식이에요. 주어진 식에서 2를 넘기면 마이너스 3엑스는 9보다 크거나 같아져요. 마이너스 3으로 나누고 방향을 뒤집으면 답은 엑스는 마이너스 3보다 작거나 같습니다.",
    hint: "2를 먼저 넘기고 마이너스 3으로 나눈 뒤 방향을 바꾸어 보세요."
  },
  {
    id: "p_mi_017",
    formulaId: "mi_system_add",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "x + y = 9와 x - y = 1을 함께 만족하는 x의 값은?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "가감법은 두 식을 더하거나 빼서 한 문자를 없애는 공식이에요. 주어진 두 식을 더하면 와이가 사라지고 2엑스는 10이 돼요. 양변을 2로 나누면 5이므로 답은 5입니다.",
    hint: "두 식을 그대로 더해서 와이를 없애 보세요."
  },
  {
    id: "p_mi_018",
    formulaId: "mi_system_add",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "x + y = 8과 x - y = 2의 해는?",
    choices: ["x = 3, y = 5", "x = 5, y = 3", "x = 6, y = 2", "x = 4, y = 4"],
    answer: "x = 5, y = 3",
    unit: "",
    explanation: "가감법은 두 식을 더해 한 문자를 소거하는 공식이에요. 주어진 두 식을 더하면 2엑스는 10이 되어 엑스는 5가 돼요. 엑스 5를 첫 식에 대입하면 답은 엑스는 5 와이는 3입니다.",
    hint: "두 식을 더해 와이를 지우고 엑스를 먼저 구해 보세요."
  },
  {
    id: "p_mi_019",
    formulaId: "mi_system_sub",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "y = 2x와 x + y = 9를 만족하는 x의 값은?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "대입법은 한 식을 다른 식에 대신 넣는 공식이에요. 주어진 첫 식의 와이 자리에 2엑스를 두 번째 식에 넣어요. 엑스 더하기 2엑스는 9이므로 답은 3입니다.",
    hint: "와이 자리에 2엑스를 넣고 식을 풀어 보세요."
  },
  {
    id: "p_mi_020",
    formulaId: "mi_system_sub",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "y = x + 2와 x + y = 10의 해는?",
    choices: ["x = 4, y = 6", "x = 6, y = 4", "x = 5, y = 5", "x = 3, y = 5"],
    answer: "x = 4, y = 6",
    unit: "",
    explanation: "대입법은 정리된 식을 다른 식에 끼워 넣는 공식이에요. 주어진 와이 자리에 엑스 더하기 2를 넣으면 2엑스 더하기 2는 10이 돼요. 엑스는 4가 되므로 답은 엑스는 4 와이는 6입니다.",
    hint: "엑스 더하기 2를 와이 대신 넣고 엑스부터 구해 보세요."
  },
  {
    id: "p_mi_021",
    formulaId: "mi_factor_common",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "6x + 9를 인수분해한 결과는?",
    choices: null,
    answer: "3(2x + 3)",
    unit: "",
    explanation: "공통인수 묶기는 모든 항의 공통 부분을 앞으로 꺼내는 공식이에요. 주어진 식의 6과 9는 공통으로 3을 가지고 있어요. 3을 꺼내면 3 괄호 2엑스 더하기 3이므로 답은 3 괄호 2엑스 더하기 3입니다.",
    hint: "6과 9의 공통인 3을 앞으로 꺼내 보세요."
  },
  {
    id: "p_mi_022",
    formulaId: "mi_factor_common",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "4xy + 6x를 인수분해한 결과는?",
    choices: ["2x(2y + 3)", "2(2xy + 3x)", "4x(y + 6)", "x(4y + 6)"],
    answer: "2x(2y + 3)",
    unit: "",
    explanation: "공통인수 묶기는 공통 문자와 공통 수를 함께 꺼내는 공식이에요. 주어진 두 항은 공통으로 2와 엑스를 가지고 있어요. 2엑스를 꺼내면 답은 2엑스 괄호 2와이 더하기 3입니다.",
    hint: "두 항에 공통인 2엑스를 앞으로 꺼내 보세요."
  },
  {
    id: "p_mi_023",
    formulaId: "mi_quadratic_formula",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    level: 3,
    type: "input",
    question: "x² - 5x + 6 = 0의 작은 해는?",
    choices: null,
    answer: "2",
    unit: "",
    explanation: "이차방정식 근의 공식은 판별식으로 해를 구하는 공식이에요. 주어진 식에서 에이는 1 비는 마이너스 5 씨는 6을 확인해요. 계산하면 엑스는 2 또는 3이므로 작은 답은 2입니다.",
    hint: "인수분해로 2와 3 중 작은 값을 찾아 보세요."
  },
  {
    id: "p_mi_024",
    formulaId: "mi_quadratic_formula",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "algebra",
    level: 3,
    type: "choice",
    question: "x² - 4x + 4 = 0의 해는?",
    choices: ["x = -2", "x = 1", "x = 2", "x = 4"],
    answer: "x = 2",
    unit: "",
    explanation: "이차방정식은 완전제곱식이나 근의 공식으로 푸는 공식이에요. 주어진 식은 엑스 빼기 2의 제곱은 0으로 바뀌어요. 엑스 빼기 2가 0이므로 답은 엑스는 2입니다.",
    hint: "엑스 빼기 2의 제곱 모양으로 바꾸어 보세요."
  },
  {
    id: "p_mi_025",
    formulaId: "mi_function",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    level: 1,
    type: "input",
    question: "y = 2x에서 x = 5일 때 y의 값은?",
    choices: null,
    answer: "10",
    unit: "",
    explanation: "함수는 하나의 입력에 하나의 출력이 정해지는 공식이에요. 주어진 식에 엑스 5를 대입하면 와이는 2 곱하기 5가 돼요. 2 곱하기 5는 10이므로 답은 10입니다.",
    hint: "엑스 자리에 5를 넣고 곱셈을 계산해 보세요."
  },
  {
    id: "p_mi_026",
    formulaId: "mi_function",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    level: 2,
    type: "choice",
    question: "다음 중 함수가 아닌 것은?",
    choices: ["y = 2x + 1", "y = x 나누기 3", "x제곱 + y제곱 = 1", "y = -x + 2"],
    answer: "x제곱 + y제곱 = 1",
    unit: "",
    explanation: "함수는 엑스 하나에 와이가 하나로 정해지는 공식이에요. 주어진 보기 중 엑스제곱 더하기 와이제곱은 1은 와이가 두 개가 나와요. 따라서 함수가 아닌 답은 엑스제곱 더하기 와이제곱은 1입니다.",
    hint: "엑스 하나에 와이가 두 개 나오는 관계를 찾아 보세요."
  },
  {
    id: "p_mi_027",
    formulaId: "mi_linear_func",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 1,
    type: "choice",
    question: "y = 3x + 2의 기울기와 y절편은?",
    choices: ["기울기 3, y절편 2", "기울기 2, y절편 3", "기울기 -3, y절편 2", "기울기 3, y절편 -2"],
    answer: "기울기 3, y절편 2",
    unit: "",
    explanation: "일차함수 와이는 에이엑스 더하기 비에서 에이는 기울기이고 비는 와이절편인 공식이에요. 주어진 식에서 엑스 앞 숫자는 3이고 더해진 수는 2예요. 따라서 답은 기울기 3 와이절편 2입니다.",
    hint: "엑스 앞 숫자가 기울기이고 더해진 수가 와이절편이에요."
  },
  {
    id: "p_mi_028",
    formulaId: "mi_linear_func",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 2,
    type: "input",
    question: "y = -2x + 5의 y절편은?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "일차함수에서 와이절편은 엑스가 0일 때의 값인 공식이에요. 주어진 식에 엑스 0을 대입하면 와이는 5가 돼요. 따라서 구하는 와이절편의 답은 5입니다.",
    hint: "엑스에 0을 넣으면 바로 와이절편이 나와요."
  },
  {
    id: "p_mi_029",
    formulaId: "mi_slope",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 2,
    type: "input",
    question: "(1, 2)와 (3, 8)을 지나는 직선의 기울기는?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "기울기는 와이증가량을 엑스증가량으로 나누는 공식이에요. 주어진 두 점에서 엑스증가량은 3 빼기 1로 2가 돼요. 와이증가량은 8 빼기 2로 6이므로 답은 3입니다.",
    hint: "와이 차이를 엑스 차이로 나누어 보세요."
  },
  {
    id: "p_mi_030",
    formulaId: "mi_slope",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 3,
    type: "choice",
    question: "(0, -1)과 (4, 7)을 지나는 직선의 기울기는?",
    choices: ["1", "2", "4", "8"],
    answer: "2",
    unit: "",
    explanation: "기울기는 와이증가량을 엑스증가량으로 나누는 공식이에요. 주어진 두 점에서 엑스증가량은 4이고 와이증가량은 8이에요. 8 나누기 4는 2이므로 답은 2입니다.",
    hint: "와이 증가 8을 엑스 증가 4로 나누어 보세요."
  },
  {
    id: "p_mi_031",
    formulaId: "mi_intercept",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 2,
    type: "input",
    question: "y = 3x - 6의 x절편은?",
    choices: null,
    answer: "2",
    unit: "",
    explanation: "엑스절편은 와이에 0을 넣고 푸는 공식이에요. 주어진 식에 와이 0을 대입하면 3엑스 빼기 6은 0이 돼요. 3엑스는 6이므로 답은 2입니다.",
    hint: "와이에 0을 넣고 방정식을 풀어 보세요."
  },
  {
    id: "p_mi_032",
    formulaId: "mi_intercept",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "function",
    level: 2,
    type: "choice",
    question: "y = -x + 4의 x절편과 y절편은?",
    choices: ["x절편 4, y절편 4", "x절편 -4, y절편 4", "x절편 4, y절편 -4", "x절편 2, y절편 2"],
    answer: "x절편 4, y절편 4",
    unit: "",
    explanation: "와이절편은 엑스에 0을 넣고 엑스절편은 와이에 0을 넣는 공식이에요. 주어진 식에 엑스 0을 넣으면 와이는 4가 돼요. 와이 0을 넣으면 엑스는 4이므로 답은 엑스절편 4 와이절편 4입니다.",
    hint: "엑스와 와이에 번갈아 0을 넣어 보세요."
  },
  {
    id: "p_mi_033",
    formulaId: "mi_direct_inverse",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    level: 1,
    type: "choice",
    question: "y가 x에 정비례하고 x = 3일 때 y = 12이면 식은?",
    choices: ["y = 4x", "y = 3x", "y = 12x", "y = x + 9"],
    answer: "y = 4x",
    unit: "",
    explanation: "정비례는 와이는 에이엑스 모양이고 에이는 와이 나누기 엑스인 공식이에요. 주어진 값 엑스 3과 와이 12를 대입하면 에이는 4가 돼요. 따라서 구하는 식의 답은 와이는 4엑스입니다.",
    hint: "12를 3으로 나누어 비례상수를 먼저 구해 보세요."
  },
  {
    id: "p_mi_034",
    formulaId: "mi_direct_inverse",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "function",
    level: 2,
    type: "input",
    question: "y가 x에 반비례하고 x = 3일 때 y = 4이면 비례상수 a의 값은?",
    choices: null,
    answer: "12",
    unit: "",
    explanation: "반비례는 와이는 에이 나누기 엑스이고 에이는 엑스 곱하기 와이인 공식이에요. 주어진 값 엑스 3과 와이 4를 곱해서 에이를 구해요. 3 곱하기 4는 12이므로 답은 12입니다.",
    hint: "엑스와 와이를 곱하면 비례상수가 나와요."
  },
  {
    id: "p_mi_035",
    formulaId: "mi_quadratic_func",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "function",
    level: 2,
    type: "input",
    question: "y = 2x²에서 x = 3일 때 y의 값은?",
    choices: null,
    answer: "18",
    unit: "",
    explanation: "이차함수 와이는 에이엑스제곱은 대입으로 값을 구하는 공식이에요. 주어진 식에 엑스 3을 넣으면 엑스제곱은 9가 돼요. 2 곱하기 9는 18이므로 답은 18입니다.",
    hint: "3의 제곱을 먼저 구하고 2를 곱해 보세요."
  },
  {
    id: "p_mi_036",
    formulaId: "mi_quadratic_func",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "function",
    level: 3,
    type: "choice",
    question: "y = -x²의 그래프에 대한 설명으로 옳은 것은?",
    choices: ["위로 볼록하고 꼭짓점은 원점이다", "아래로 볼록하고 꼭짓점은 원점이다", "직선이다", "오른쪽으로 올라가는 직선이다"],
    answer: "위로 볼록하고 꼭짓점은 원점이다",
    unit: "",
    explanation: "이차함수 와이는 에이엑스제곱은 에이가 음수이면 위로 볼록한 공식이에요. 주어진 식의 에이는 마이너스 1이므로 위로 볼록하게 열려요. 꼭짓점은 원점이므로 답은 위로 볼록하고 꼭짓점은 원점입니다.",
    hint: "에이의 부호로 볼록한 방향을 판단해 보세요."
  },
  {
    id: "p_mi_037",
    formulaId: "mi_pythagoras",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "직각을 낀 두 변이 6과 8일 때 빗변의 길이는?",
    choices: null,
    answer: "10",
    unit: "",
    explanation: "피타고라스 정리는 직각을 낀 두 변의 제곱합이 빗변의 제곱인 공식이에요. 주어진 두 변을 제곱하면 36과 64가 나와 더해요. 합이 100이므로 제곱근을 구하면 답은 10입니다.",
    hint: "6의 제곱과 8의 제곱을 더하고 제곱근을 구해 보세요."
  },
  {
    id: "p_mi_038",
    formulaId: "mi_pythagoras",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "빗변이 13이고 한 변이 5인 직각삼각형의 다른 한 변은?",
    choices: ["8", "10", "12", "18"],
    answer: "12",
    unit: "",
    explanation: "피타고라스 정리는 빗변 제곱에서 아는 변 제곱을 빼는 공식이에요. 주어진 빗변 13의 제곱은 169이고 한 변 5의 제곱은 25예요. 169 빼기 25는 144이므로 답은 12입니다.",
    hint: "13의 제곱에서 5의 제곱을 빼고 제곱근을 구해 보세요."
  },
  {
    id: "p_mi_039",
    formulaId: "mi_congruent",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "세 변이 각각 4와 5와 6으로 같은 두 삼각형은?",
    choices: ["합동이다", "닮음이지만 합동이 아니다", "합동이 아니다", "넓이만 같다"],
    answer: "합동이다",
    unit: "",
    explanation: "삼각형 합동조건은 세 변이 같으면 합동인 공식이에요. 주어진 두 삼각형은 세 변이 4와 5와 6으로 각각 같아요. 세 변 조건을 만족하므로 답은 합동입니다.",
    hint: "세 변이 모두 같은 조건이 있는지 확인해 보세요."
  },
  {
    id: "p_mi_040",
    formulaId: "mi_congruent",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 3,
    type: "input",
    question: "두 변이 5와 7로 같고 끼인각이 같은 두 삼각형은 합동인가요?",
    choices: null,
    answer: "합동이다",
    unit: "",
    explanation: "삼각형 합동조건은 두 변과 끼인각이 같으면 합동인 공식이에요. 주어진 두 삼각형은 5와 7인 두 변과 끼인각이 같아요. 조건을 만족하므로 답은 합동입니다.",
    hint: "끼인각이 맞는지 확인하고 합동이라고 답해 보세요."
  },
  {
    id: "p_mi_041",
    formulaId: "mi_circle_angle",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "중심각이 80도인 호의 원주각의 크기는?",
    choices: null,
    answer: "40",
    unit: "도",
    explanation: "원주각은 같은 호의 중심각의 절반인 공식이에요. 주어진 중심각은 80도이므로 절반을 구하려고 해요. 80 나누기 2는 40이므로 답은 40도입니다.",
    hint: "중심각을 2로 나누어 원주각을 구해 보세요."
  },
  {
    id: "p_mi_042",
    formulaId: "mi_circle_angle",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "한 호의 원주각이 35도일 때 중심각의 크기는?",
    choices: ["17도", "35도", "70도", "105도"],
    answer: "70도",
    unit: "",
    explanation: "중심각은 같은 호의 원주각의 두 배인 공식이에요. 주어진 원주각은 35도이므로 두 배를 구하려고 해요. 35 곱하기 2는 70이므로 답은 70도입니다.",
    hint: "원주각을 2배하면 중심각이 나와요."
  },
  {
    id: "p_mi_043",
    formulaId: "mi_circle_area",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "반지름이 4인 원의 넓이는?",
    choices: null,
    answer: "16π",
    unit: "",
    explanation: "원의 넓이는 원주율 곱하기 반지름의 제곱인 공식이에요. 주어진 반지름 4를 제곱하면 16이 나와요. 16에 원주율을 곱하므로 답은 16파이입니다.",
    hint: "반지름을 제곱한 뒤 파이를 곱해 보세요."
  },
  {
    id: "p_mi_044",
    formulaId: "mi_circle_area",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "반지름이 6인 원의 넓이는?",
    choices: ["6π", "12π", "36π", "216π"],
    answer: "36π",
    unit: "",
    explanation: "원의 넓이는 원주율 곱하기 반지름의 제곱인 공식이에요. 주어진 반지름 6을 제곱하면 36이 나와요. 36에 원주율을 곱하므로 답은 36파이입니다.",
    hint: "6을 제곱하면 36이니 파이를 곱해 보세요."
  },
  {
    id: "p_mi_045",
    formulaId: "mi_sector",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "반지름이 6이고 중심각이 90도인 부채꼴의 넓이는?",
    choices: null,
    answer: "9π",
    unit: "",
    explanation: "부채꼴 넓이는 원넓이에 중심각 나누기 360을 곱하는 공식이에요. 주어진 원의 넓이는 36파이이고 비율은 4분의 1이에요. 36파이의 4분의 1은 9파이이므로 답은 9파이입니다.",
    hint: "원넓이를 구하고 4분의 1을 곱해 보세요."
  },
  {
    id: "p_mi_046",
    formulaId: "mi_sector",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "반지름이 4이고 중심각이 90도인 부채꼴의 호의 길이는?",
    choices: ["π", "2π", "4π", "8π"],
    answer: "2π",
    unit: "",
    explanation: "부채꼴 호의 길이는 원둘레에 중심각 나누기 360을 곱하는 공식이에요. 주어진 원의 둘레는 8파이이고 비율은 4분의 1이에요. 8파이의 4분의 1은 2파이이므로 답은 2파이입니다.",
    hint: "원둘레를 구하고 4분의 1을 곱해 보세요."
  },
  {
    id: "p_mi_047",
    formulaId: "mi_cylinder_vol",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 1,
    type: "input",
    question: "밑넓이가 10이고 높이가 7인 기둥의 부피는?",
    choices: null,
    answer: "70",
    unit: "",
    explanation: "기둥의 부피는 밑넓이 곱하기 높이인 공식이에요. 주어진 밑넓이는 10이고 높이는 7이에요. 10 곱하기 7은 70이므로 답은 70입니다.",
    hint: "밑넓이에 높이를 곱해 보세요."
  },
  {
    id: "p_mi_048",
    formulaId: "mi_cylinder_vol",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "geometry",
    level: 2,
    type: "choice",
    question: "밑넓이가 9π이고 높이가 5인 원기둥의 부피는?",
    choices: ["14π", "45π", "46π", "90π"],
    answer: "45π",
    unit: "",
    explanation: "기둥의 부피는 밑넓이 곱하기 높이인 공식이에요. 주어진 밑넓이는 9파이이고 높이는 5예요. 9 곱하기 5는 45이므로 답은 45파이입니다.",
    hint: "9에 5를 곱하고 파이를 붙여 보세요."
  },
  {
    id: "p_mi_049",
    formulaId: "mi_pyramid_vol",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "밑넓이가 12이고 높이가 9인 뿔의 부피는?",
    choices: null,
    answer: "36",
    unit: "",
    explanation: "뿔의 부피는 밑넓이 곱하기 높이의 3분의 1인 공식이에요. 주어진 밑넓이 12에 높이 9를 곱하면 108이 돼요. 108을 3으로 나누면 36이므로 답은 36입니다.",
    hint: "밑넓이와 높이를 곱한 뒤 3으로 나누어 보세요."
  },
  {
    id: "p_mi_050",
    formulaId: "mi_pyramid_vol",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "밑넓이가 21이고 높이가 6인 뿔의 부피는?",
    choices: ["42", "63", "126", "27"],
    answer: "42",
    unit: "",
    explanation: "뿔의 부피는 밑넓이 곱하기 높이의 3분의 1인 공식이에요. 주어진 밑넓이 21에 높이 6을 곱하면 126이 돼요. 126을 3으로 나누면 42이므로 답은 42입니다.",
    hint: "21과 6을 곱한 뒤 3으로 나누어 보세요."
  },
  {
    id: "p_mi_051",
    formulaId: "mi_similar",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "닮음비가 2 대 3인 두 도형의 넓이비는 4 대 몇인가요?",
    choices: null,
    answer: "9",
    unit: "",
    explanation: "닮은 도형의 넓이비는 닮음비를 각각 제곱하는 공식이에요. 주어진 닮음비는 2 대 3이므로 각각 제곱하려고 해요. 2의 제곱은 4이고 3의 제곱은 9이므로 답은 9입니다.",
    hint: "3을 제곱하여 넓이비의 뒷수를 구해 보세요."
  },
  {
    id: "p_mi_052",
    formulaId: "mi_similar",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "닮음비가 1 대 2인 두 입체의 부피비는?",
    choices: ["1 대 2", "1 대 4", "1 대 6", "1 대 8"],
    answer: "1 대 8",
    unit: "",
    explanation: "닮은 입체의 부피비는 닮음비를 각각 세제곱하는 공식이에요. 주어진 닮음비는 1 대 2이므로 각각 세제곱하려고 해요. 1의 세제곱은 1이고 2의 세제곱은 8이므로 답은 1 대 8입니다.",
    hint: "2를 세제곱하여 부피비의 뒷수를 구해 보세요."
  },
  {
    id: "p_mi_053",
    formulaId: "mi_distance",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 2,
    type: "input",
    question: "(0, 0)과 (3, 4) 사이의 거리는?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "두 점 사이의 거리는 가로 차이와 세로 차이로 구하는 공식이에요. 주어진 두 점의 가로 차이는 3이고 세로 차이는 4예요. 9 더하기 16은 25이므로 답은 5입니다.",
    hint: "가로 차이와 세로 차이를 제곱해 더한 뒤 제곱근을 구해 보세요."
  },
  {
    id: "p_mi_054",
    formulaId: "mi_distance",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "geometry",
    level: 3,
    type: "choice",
    question: "(1, 2)와 (4, 6) 사이의 거리는?",
    choices: ["4", "5", "7", "25"],
    answer: "5",
    unit: "",
    explanation: "두 점 사이의 거리는 가로 차이와 세로 차이로 구하는 공식이에요. 주어진 두 점의 가로 차이는 3이고 세로 차이는 4예요. 9 더하기 16은 25이므로 답은 5입니다.",
    hint: "가로 차이 3과 세로 차이 4로 직각삼각형을 만들어 보세요."
  },
  {
    id: "p_mi_055",
    formulaId: "mi_mean_med_mode",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    level: 1,
    type: "input",
    question: "2, 4, 6의 평균은?",
    choices: null,
    answer: "4",
    unit: "",
    explanation: "평균은 모두 더해서 개수로 나누는 공식이에요. 주어진 세 수를 모두 더하면 12가 나와요. 12를 3으로 나누면 4이므로 답은 4입니다.",
    hint: "세 수를 더한 뒤 3으로 나누어 보세요."
  },
  {
    id: "p_mi_056",
    formulaId: "mi_mean_med_mode",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "1, 2, 2, 5, 9의 최빈값은?",
    choices: ["1", "2", "5", "9"],
    answer: "2",
    unit: "",
    explanation: "최빈값은 가장 자주 나오는 값인 공식이에요. 주어진 자료에서 2는 두 번 나오고 나머지는 한 번씩 나와요. 가장 많은 값이 2이므로 답은 2입니다.",
    hint: "가장 여러 번 나오는 숫자를 찾아 보세요."
  },
  {
    id: "p_mi_057",
    formulaId: "mi_histogram",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    level: 1,
    type: "choice",
    question: "히스토그램에서 가장 높은 막대가 뜻하는 것은?",
    choices: ["도수가 가장 큰 구간이다", "평균이다", "중앙값이다", "합계이다"],
    answer: "도수가 가장 큰 구간이다",
    unit: "",
    explanation: "히스토그램은 구간별 도수를 막대 높이로 나타내는 공식이에요. 주어진 그림에서 막대가 높을수록 그 구간의 개수가 많아요. 따라서 가장 높은 막대의 답은 도수가 가장 큰 구간입니다.",
    hint: "막대 높이가 도수의 크기라고 생각해 보세요."
  },
  {
    id: "p_mi_058",
    formulaId: "mi_histogram",
    schoolLevel: "middle",
    gradeLevel: "middle1",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "전체 40명 중 10점대가 8명이면 10점대의 도수는?",
    choices: null,
    answer: "8",
    unit: "명",
    explanation: "도수분포표는 각 구간에 속한 개수를 세는 공식이에요. 주어진 전체 40명 중 10점대에 속한 학생을 세어요. 10점대는 8명이므로 답은 8명입니다.",
    hint: "그 구간에 속한 사람 수만 세어 보세요."
  },
  {
    id: "p_mi_059",
    formulaId: "mi_probability",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    level: 1,
    type: "choice",
    question: "주사위 한 개를 던질 때 3이 나올 확률은?",
    choices: ["6분의 1", "3분의 1", "2분의 1", "1"],
    answer: "6분의 1",
    unit: "",
    explanation: "확률은 원하는 경우 나누기 전체 경우인 공식이에요. 주어진 주사위의 전체 경우는 6가지이고 원하는 경우는 1가지예요. 1 나누기 6이므로 답은 6분의 1입니다.",
    hint: "전체 6가지 중 원하는 1가지를 분수로 나타내 보세요."
  },
  {
    id: "p_mi_060",
    formulaId: "mi_probability",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "동전 한 개를 던질 때 앞면이 나올 확률은?",
    choices: null,
    answer: "2분의 1",
    unit: "",
    explanation: "확률은 원하는 경우 나누기 전체 경우인 공식이에요. 주어진 동전의 전체 경우는 앞뒤 2가지이고 원하는 앞면은 1가지예요. 1 나누기 2이므로 답은 2분의 1입니다.",
    hint: "앞면 1가지를 전체 2가지로 나누어 보세요."
  },
  {
    id: "p_mi_061",
    formulaId: "mi_expected",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "500원을 2분의 1 확률로 받는 게임의 기댓값은?",
    choices: null,
    answer: "250",
    unit: "원",
    explanation: "기댓값은 값에 확률을 곱하고 모두 더하는 공식이에요. 주어진 값 500에 확률 2분의 1을 곱하려고 해요. 500의 절반은 250이므로 답은 250원입니다.",
    hint: "500에 2분의 1을 곱해 보세요."
  },
  {
    id: "p_mi_062",
    formulaId: "mi_expected",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 3,
    type: "choice",
    question: "1000원 상품이 절반 확률이고 200원 상품이 절반 확률일 때 기댓값은?",
    choices: ["400원", "500원", "600원", "1200원"],
    answer: "600원",
    unit: "",
    explanation: "기댓값은 각각의 값에 확률을 곱해 더하는 공식이에요. 주어진 1000의 절반은 500이고 200의 절반은 100이에요. 500 더하기 100은 600이므로 답은 600원입니다.",
    hint: "두 상품의 절반 값을 각각 구해 더해 보세요."
  },
  {
    id: "p_mi_063",
    formulaId: "mi_count_cases",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "combinatorics",
    level: 1,
    type: "input",
    question: "셔츠 3장과 바지 2벌로 만들 수 있는 옷차림은?",
    choices: null,
    answer: "6",
    unit: "가지",
    explanation: "이어서 일어나는 경우의 수는 서로 곱하는 공식이에요. 주어진 셔츠 3장과 바지 2벌은 이어서 입으므로 곱해요. 3 곱하기 2는 6이므로 답은 6가지입니다.",
    hint: "셔츠 수와 바지 수를 곱해 보세요."
  },
  {
    id: "p_mi_064",
    formulaId: "mi_count_cases",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "combinatorics",
    level: 2,
    type: "choice",
    question: "버스 2대와 전철 3대 중 하나를 타는 방법은?",
    choices: ["5가지", "6가지", "8가지", "9가지"],
    answer: "5가지",
    unit: "",
    explanation: "따로 일어나는 경우의 수는 서로 더하는 공식이에요. 주어진 버스와 전철은 하나만 타므로 더해서 세어요. 2 더하기 3은 5이므로 답은 5가지입니다.",
    hint: "하나만 고르는 경우이니 더하기로 세어 보세요."
  },
  {
    id: "p_mi_065",
    formulaId: "mi_relative_freq",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "전체 20명 중 도수가 5명인 구간의 상대도수는?",
    choices: null,
    answer: "4분의 1",
    unit: "",
    explanation: "상대도수는 구간 도수 나누기 전체 도수인 공식이에요. 주어진 구간 도수는 5이고 전체는 20이므로 나누어요. 5 나누기 20은 4분의 1이므로 답은 4분의 1입니다.",
    hint: "5를 20으로 나누어 비율을 구해 보세요."
  },
  {
    id: "p_mi_066",
    formulaId: "mi_relative_freq",
    schoolLevel: "middle",
    gradeLevel: "middle2",
    topic: "statistics",
    level: 3,
    type: "choice",
    question: "전체 40명 중 도수가 8명인 구간의 상대도수는?",
    choices: ["5분의 1", "4분의 1", "2분의 1", "8분의 1"],
    answer: "5분의 1",
    unit: "",
    explanation: "상대도수는 구간 도수 나누기 전체 도수인 공식이에요. 주어진 구간 도수는 8이고 전체는 40이므로 나누어요. 8 나누기 40은 5분의 1이므로 답은 5분의 1입니다.",
    hint: "8을 40으로 나누어 비율을 구해 보세요."
  },
  {
    id: "p_mi_067",
    formulaId: "mi_boxplot",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "1, 2, 3, 4, 5의 중앙값은?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "상자그림의 가운데 선은 중앙값인 공식이에요. 주어진 자료를 순서대로 세우면 1부터 5까지 그대로예요. 가운데 값은 3이므로 답은 3입니다.",
    hint: "순서대로 세운 뒤 가운데 값을 찾아 보세요."
  },
  {
    id: "p_mi_068",
    formulaId: "mi_boxplot",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 3,
    type: "choice",
    question: "2, 4, 6, 8의 중앙값은?",
    choices: ["4", "5", "6", "8"],
    answer: "5",
    unit: "",
    explanation: "짝수 개 자료의 중앙값은 가운데 두 수의 평균인 공식이에요. 주어진 자료의 가운데 두 수는 4와 6이에요. 4 더하기 6은 10이고 절반은 5이므로 답은 5입니다.",
    hint: "가운데 두 수 4와 6의 평균을 구해 보세요."
  },
  {
    id: "p_mi_069",
    formulaId: "mi_stddev",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 2,
    type: "input",
    question: "분산이 25일 때 표준편차는?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "표준편차는 분산에 제곱근을 씌우는 공식이에요. 주어진 분산은 25이므로 제곱근을 구하려고 해요. 25의 제곱근은 5이므로 답은 5입니다.",
    hint: "25의 제곱근을 구해 보세요."
  },
  {
    id: "p_mi_070",
    formulaId: "mi_stddev",
    schoolLevel: "middle",
    gradeLevel: "middle3",
    topic: "statistics",
    level: 3,
    type: "choice",
    question: "분산이 36일 때 표준편차는?",
    choices: ["6", "12", "18", "36"],
    answer: "6",
    unit: "",
    explanation: "표준편차는 분산에 제곱근을 씌우는 공식이에요. 주어진 분산은 36이므로 제곱근을 구하려고 해요. 36의 제곱근은 6이므로 답은 6입니다.",
    hint: "36의 제곱근을 구해 보세요."
  }
];
