/* ============================================================
   수학아 놀자 (math) - 고등 문제 46개: 대수·미적분·경우의 수·벡터·통계 (problem-hi-b.js)
   problem-data.js 가 합쳐서 window.MathProblemData 로 만듭니다.
   ============================================================ */
window.MathProblemHiB = [
  {
    id: "p_hi_041",
    formulaId: "hi_factor_thm",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "다항식 f(x) = x³ − 3x² − 4x + 12에서 f(2) = 0일 때 한 인수는 무엇입니까?",
    choices: null,
    answer: "x − 2",
    unit: "",
    explanation: "인수정리에 따르면 f(a) = 0이면 x − a가 인수입니다. 주어진 식에 x = 2를 대입하면 f(2) = 0이 성립합니다. 따라서 한 인수는 x − 2가 되므로 답은 x − 2입니다.",
    hint: "f(a) = 0이면 x − a가 인수예요. a가 얼마인지 확인해 보세요."
  },
  {
    id: "p_hi_042",
    formulaId: "hi_discriminant",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "이차방정식 x² + 4x + k = 0이 중근을 가질 때 상수 k의 값은 얼마입니까?",
    choices: ["2", "4", "8", "16"],
    answer: "4",
    unit: "",
    explanation: "판별식 D = b² − 4ac를 이용합니다. 주어진 방정식에서 a = 1이고 b = 4이며 c = k입니다. 중근 조건 D = 0에 대입하면 16 − 4k = 0이 되어 k = 4를 구합니다.",
    hint: "중근 조건은 판별식이 0이 되는 경우예요."
  },
  {
    id: "p_hi_043",
    formulaId: "hi_discriminant",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 3,
    type: "input",
    question: "이차방정식 x² − 6x + m = 0이 서로 다른 두 실근을 가질 때 m이 만족하는 조건은 무엇입니까?",
    choices: null,
    answer: "m < 9",
    unit: "",
    explanation: "서로 다른 두 실근 조건은 판별식 D > 0입니다. 주어진 방정식에서 D = 36 − 4m입니다. 부등식 36 − 4m > 0을 풀면 m < 9를 구합니다.",
    hint: "서로 다른 두 실근은 판별식이 0보다 클 때 나타나요."
  },
  {
    id: "p_hi_044",
    formulaId: "hi_trig_eq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "choice",
    question: "0 ≤ x < 2π 범위에서 sin x = 1⁄2을 만족하는 x의 값은 무엇입니까?",
    choices: ["π⁄6, 5π⁄6", "π⁄3, 2π⁄3", "π⁄4, 3π⁄4", "π⁄6, π⁄3"],
    answer: "π⁄6, 5π⁄6",
    unit: "",
    explanation: "사인방정식 sin x = 1⁄2의 기본해는 x = π⁄6입니다. 단위원에서 사인값이 같은 대칭각은 π − π⁄6입니다. 따라서 0 ≤ x < 2π 범위에서 답은 π⁄6과 5π⁄6입니다.",
    hint: "사인값이 같은 두 각은 π를 기준으로 대칭이에요."
  },
  {
    id: "p_hi_045",
    formulaId: "hi_trig_eq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 3,
    type: "input",
    question: "0 ≤ x < 2π 범위에서 cos x = −√2⁄2를 만족하는 x의 값 중 작은 값을 구하세요.",
    choices: null,
    answer: "3π⁄4",
    unit: "",
    explanation: "코사인방정식 cos x = −√2⁄2를 생각합니다. 제2사분면의 기준각은 π⁄4이므로 해는 π − π⁄4입니다. 계산하면 3π⁄4가 되므로 작은 해는 3π⁄4입니다.",
    hint: "코사인이 음수이면 제2사분면과 제3사분면을 떠올려 보세요."
  },
  {
    id: "p_hi_046",
    formulaId: "hi_limit",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "극한 lim(x→2) (x² − 4)⁄(x − 2)의 값은 얼마입니까?",
    choices: ["2", "3", "4", "6"],
    answer: "4",
    unit: "",
    explanation: "분자 x² − 4는 (x − 2)(x + 2)로 인수분해됩니다. 분모와 공통인수 x − 2를 약분하면 식은 x + 2가 됩니다. x = 2를 대입하면 4를 구합니다.",
    hint: "분자를 먼저 인수분해한 뒤 공통인수를 약분해 보세요."
  },
  {
    id: "p_hi_047",
    formulaId: "hi_limit",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "극한 lim(x→0) sin 3x⁄x의 값은 얼마입니까?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "기본 극한 lim(x→0) sin x⁄x = 1을 이용합니다. 주어진 식을 3 × sin 3x⁄3x 형태로 변형합니다. 3x를 t로 두면 극한값이 1이 되므로 전체 답은 3입니다.",
    hint: "sin x⁄x 꼴이 보이도록 분모 분자에 같은 상수를 곱해 보세요."
  },
  {
    id: "p_hi_048",
    formulaId: "hi_derivative",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 1,
    type: "choice",
    question: "함수 f(x) = x² + 3x + 1에 대하여 x = 1에서의 미분계수 f′(1)은 얼마입니까?",
    choices: ["3", "4", "5", "6"],
    answer: "5",
    unit: "",
    explanation: "미분 공식에 따라 f′(x) = 2x + 3입니다. 주어진 점은 x = 1입니다. x = 1을 대입하면 2 + 3 = 5가 되므로 답은 5입니다.",
    hint: "먼저 도함수를 구한 뒤 x = 1을 대입해 보세요."
  },
  {
    id: "p_hi_049",
    formulaId: "hi_derivative",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "input",
    question: "함수 f(x) = 2x³ − x² + 4에 대하여 x = 1에서의 미분계수 f′(1)을 구하세요.",
    choices: null,
    answer: "4",
    unit: "",
    explanation: "미분 공식에 따라 f′(x) = 6x² − 2x입니다. 주어진 점은 x = 1입니다. x = 1을 대입하면 6 − 2 = 4가 되므로 답은 4입니다.",
    hint: "각 항을 차례로 미분한 뒤 x = 1을 대입해 보세요."
  },
  {
    id: "p_hi_050",
    formulaId: "hi_power_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 1,
    type: "choice",
    question: "함수 f(x) = x⁵의 도함수 f′(x)는 무엇입니까?",
    choices: ["4x⁴", "5x⁴", "5x⁵", "x⁴"],
    answer: "5x⁴",
    unit: "",
    explanation: "거듭제곱 미분법 (xⁿ)′ = nxⁿ⁻¹을 적용합니다. 주어진 지수는 n = 5입니다. 공식에 대입하면 5x⁴이 되므로 답은 5x⁴입니다.",
    hint: "지수를 앞으로 내리고 지수에서 1을 빼 보세요."
  },
  {
    id: "p_hi_051",
    formulaId: "hi_power_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "input",
    question: "함수 f(x) = 3x⁴ + 2x²의 도함수 f′(x)를 구하세요.",
    choices: null,
    answer: "12x³ + 4x",
    unit: "",
    explanation: "거듭제곱 미분법을 각 항에 적용합니다. 주어진 함수는 3x⁴과 2x²의 합입니다. 각각 미분하면 12x³과 4x가 되므로 답은 12x³ + 4x입니다.",
    hint: "각 항마다 지수를 앞으로 내리고 지수를 1씩 줄여 보세요."
  },
  {
    id: "p_hi_052",
    formulaId: "hi_product_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "함수 f(x) = x²sin x의 도함수 f′(x)는 무엇입니까?",
    choices: ["2x sin x + x² cos x", "2x cos x − x² sin x", "2x sin x − x² cos x", "x² cos x − 2x sin x"],
    answer: "2x sin x + x² cos x",
    unit: "",
    explanation: "곱의 미분법 (uv)′ = u′v + uv′를 사용합니다. u = x²이고 v = sin x이므로 u′ = 2x이고 v′ = cos x입니다. 공식에 대입하면 2x sin x + x² cos x를 구합니다.",
    hint: "앞을 미분한 것과 뒤를 미분한 것을 각각 더하는 방식이에요."
  },
  {
    id: "p_hi_053",
    formulaId: "hi_product_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "함수 f(x) = xeˣ의 도함수 f′(x)를 구하세요.",
    choices: null,
    answer: "eˣ + xeˣ",
    unit: "",
    explanation: "곱의 미분법 (uv)′ = u′v + uv′를 사용합니다. u = x이고 v = eˣ이므로 u′ = 1이고 v′ = eˣ입니다. 공식에 대입하면 eˣ + xeˣ을 구합니다.",
    hint: "x의 도함수는 1이고 지수함수의 도함수는 그대로 유지돼요."
  },
  {
    id: "p_hi_054",
    formulaId: "hi_chain_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "함수 f(x) = (2x + 1)³의 도함수 f′(x)는 무엇입니까?",
    choices: ["3(2x + 1)²", "6(2x + 1)²", "6x(2x + 1)²", "2(2x + 1)²"],
    answer: "6(2x + 1)²",
    unit: "",
    explanation: "합성함수 미분법인 연쇄법칙을 적용합니다. 겉함수의 미분은 3(2x + 1)²이고 속함수 2x + 1의 미분은 2입니다. 두 값을 곱하면 6(2x + 1)²을 구합니다.",
    hint: "겉을 먼저 미분하고 안에 있는 식의 미분을 곱해 보세요."
  },
  {
    id: "p_hi_055",
    formulaId: "hi_chain_rule",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "함수 f(x) = sin(x²)의 도함수 f′(x)를 구하세요.",
    choices: null,
    answer: "2x cos(x²)",
    unit: "",
    explanation: "합성함수 미분법인 연쇄법칙을 적용합니다. 겉함수 sin의 미분은 cos(x²)이고 속함수 x²의 미분은 2x입니다. 두 값을 곱하면 2x cos(x²)을 구합니다.",
    hint: "사인을 미분하면 코사인이 되고 뒤에 x²의 미분을 곱해 보세요."
  },
  {
    id: "p_hi_056",
    formulaId: "hi_tangent",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "곡선 y = x² 위의 점 (1, 1)에서의 접선의 기울기는 얼마입니까?",
    choices: ["1", "2", "3", "4"],
    answer: "2",
    unit: "",
    explanation: "접선의 기울기는 그 점에서의 미분계수와 같습니다. y = x²의 도함수는 y′ = 2x입니다. x = 1을 대입하면 기울기 2를 구합니다.",
    hint: "접선의 기울기는 도함수에 점의 x좌표를 대입한 값이에요."
  },
  {
    id: "p_hi_057",
    formulaId: "hi_tangent",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "곡선 y = x³ − 2x 위의 점 (1, −1)에서의 접선의 방정식을 구하세요.",
    choices: null,
    answer: "y = x − 2",
    unit: "",
    explanation: "접선의 기울기는 도함수 y′ = 3x² − 2로 구합니다. x = 1을 대입하면 기울기는 1입니다. 점 (1, −1)을 지나고 기울기가 1인 직선이므로 답은 y = x − 2입니다.",
    hint: "기울기를 먼저 구한 뒤 점과 기울기를 이용해 직선의 식을 세워 보세요."
  },
  {
    id: "p_hi_058",
    formulaId: "hi_extrema",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "함수 f(x) = x² − 4x + 3이 극값을 가지는 x의 값은 얼마입니까?",
    choices: ["0", "1", "2", "4"],
    answer: "2",
    unit: "",
    explanation: "극값 후보는 도함수가 0인 점에서 찾습니다. f′(x) = 2x − 4이므로 방정식은 2x − 4 = 0입니다. 이를 풀면 x = 2를 구합니다.",
    hint: "도함수가 0이 되는 지점을 먼저 찾아보세요."
  },
  {
    id: "p_hi_059",
    formulaId: "hi_extrema",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "함수 f(x) = x³ − 3x의 극댓값은 얼마입니까?",
    choices: null,
    answer: "2",
    unit: "",
    explanation: "도함수 f′(x) = 3x² − 3에서 f′(x) = 0을 풀면 x = −1과 x = 1을 얻습니다. 증가 감소표를 그리면 x = −1에서 극대임을 알 수 있습니다. f(−1) = 2이므로 극댓값은 2입니다.",
    hint: "도함수가 0인 두 점 중 왼쪽 점이 극대인지 확인해 보세요."
  },
  {
    id: "p_hi_060",
    formulaId: "hi_indef_integral",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 1,
    type: "choice",
    question: "부정적분 ∫ 2x dx의 결과는 무엇입니까?",
    choices: ["x²", "x² + C", "2x² + C", "x + C"],
    answer: "x² + C",
    unit: "",
    explanation: "거듭제곱 적분 공식 ∫ xⁿ dx = xⁿ⁺¹⁄(n + 1) + C를 사용합니다. 주어진 피적분함수는 2x입니다. 적분하면 x² + C가 되므로 답은 x² + C입니다.",
    hint: "x를 적분하면 x²의 절반이 됨을 이용해 보세요."
  },
  {
    id: "p_hi_061",
    formulaId: "hi_indef_integral",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "input",
    question: "부정적분 ∫ (3x² + 2x + 1) dx를 구하세요.",
    choices: null,
    answer: "x³ + x² + x + C",
    unit: "",
    explanation: "각 항을 거듭제곱 적분 공식으로 적분합니다. 주어진 식은 3x²과 2x와 1의 합입니다. 각각 적분하면 x³과 x²과 x가 되므로 답은 x³ + x² + x + C입니다.",
    hint: "각 항을 나누어 적분한 뒤 모두 더하고 적분상수를 붙여 보세요."
  },
  {
    id: "p_hi_062",
    formulaId: "hi_def_integral",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 2,
    type: "choice",
    question: "정적분 ∫₀¹ 2x dx의 값은 얼마입니까?",
    choices: ["1", "2", "3", "4"],
    answer: "1",
    unit: "",
    explanation: "먼저 원시함수 F(x) = x²를 구합니다. 적분 구간은 0부터 1까지입니다. F(1) − F(0) = 1 − 0이므로 답은 1입니다.",
    hint: "원시함수를 구한 뒤 위끝값에서 아래끝값을 빼 보세요."
  },
  {
    id: "p_hi_063",
    formulaId: "hi_def_integral",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "calculus",
    level: 3,
    type: "input",
    question: "정적분 ∫₁² (3x² + 1) dx의 값은 얼마입니까?",
    choices: null,
    answer: "8",
    unit: "",
    explanation: "먼저 원시함수 F(x) = x³ + x를 구합니다. 적분 구간은 1부터 2까지이므로 F(2) = 10이고 F(1) = 2입니다. F(2) − F(1) = 10 − 2를 계산하면 8이 되므로 답은 8입니다.",
    hint: "원시함수를 구한 뒤 양 끝값을 각각 대입하여 빼 보세요."
  },
  {
    id: "p_hi_064",
    formulaId: "hi_permutation",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 1,
    type: "choice",
    question: "5명 중에서 1등과 2등을 뽑는 경우의 수는 얼마입니까?",
    choices: ["10", "20", "25", "30"],
    answer: "20",
    unit: "가지",
    explanation: "순서를 고려하므로 순열 공식 ₅P₂를 사용합니다. 주어진 인원은 5명이고 뽑는 자리는 2자리입니다. 5 × 4를 계산하면 20가지가 되므로 답은 20입니다.",
    hint: "순서가 중요하므로 5 × 4로 계산해 보세요."
  },
  {
    id: "p_hi_065",
    formulaId: "hi_permutation",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 2,
    type: "input",
    question: "서로 다른 4권의 책을 일렬로 세우는 경우의 수는 얼마입니까?",
    choices: null,
    answer: "24",
    unit: "가지",
    explanation: "일렬로 나열하므로 4의 계승을 사용합니다. 주어진 책은 4권입니다. 4 × 3 × 2 × 1을 계산하면 24가 되므로 답은 24입니다.",
    hint: "4 × 3 × 2 × 1을 차례로 계산해 보세요."
  },
  {
    id: "p_hi_066",
    formulaId: "hi_combination",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 1,
    type: "choice",
    question: "5명 중에서 2명의 대표를 뽑는 경우의 수는 얼마입니까?",
    choices: ["5", "10", "15", "20"],
    answer: "10",
    unit: "가지",
    explanation: "순서를 고려하지 않으므로 조합 공식 ₅C₂를 사용합니다. 주어진 인원은 5명이고 뽑는 인원은 2명입니다. (5 × 4)⁄(2 × 1)을 계산하면 10이 되므로 답은 10입니다.",
    hint: "순열 값을 2의 계승으로 나누어 보세요."
  },
  {
    id: "p_hi_067",
    formulaId: "hi_combination",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 2,
    type: "input",
    question: "6개의 과일 중에서 3개를 고르는 경우의 수는 얼마입니까?",
    choices: null,
    answer: "20",
    unit: "가지",
    explanation: "순서를 고려하지 않으므로 조합 공식 ₆C₃을 사용합니다. 주어진 과일은 6개이고 고르는 개수는 3개입니다. (6 × 5 × 4)⁄(3 × 2 × 1)을 계산하면 20이 되므로 답은 20입니다.",
    hint: "분자는 6부터 3개를 곱하고 분모는 3의 계승으로 나누어 보세요."
  },
  {
    id: "p_hi_068",
    formulaId: "hi_binomial_thm",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 2,
    type: "choice",
    question: "(x + y)⁴의 전개식에서 x³y의 계수는 얼마입니까?",
    choices: ["3", "4", "6", "12"],
    answer: "4",
    unit: "",
    explanation: "이항정리에 따르면 (x + y)⁴의 일반항은 ₄Cᵣx⁴⁻ʳyʳ입니다. x³y항은 r = 1일 때 나타납니다. ₄C₁ = 4이므로 답은 4입니다.",
    hint: "x³y는 네 자리 중 y가 들어갈 자리 하나를 고르는 경우예요."
  },
  {
    id: "p_hi_069",
    formulaId: "hi_binomial_thm",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "combinatorics",
    level: 3,
    type: "input",
    question: "(x + 2)⁵의 전개식에서 x³의 계수는 얼마입니까?",
    choices: null,
    answer: "40",
    unit: "",
    explanation: "이항정리에 따르면 (x + 2)⁵의 일반항은 ₅Cᵣx⁵⁻ʳ2ʳ입니다. x³항은 5 − r = 3이므로 r = 2일 때 나타납니다. ₅C₂ × 2² = 10 × 4이므로 답은 40입니다.",
    hint: "x의 지수가 3이 되는 r 값을 먼저 찾아보세요."
  },
  {
    id: "p_hi_070",
    formulaId: "hi_stars_bars",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "combinatorics",
    level: 2,
    type: "choice",
    question: "같은 모양의 사탕 5개를 3명의 학생에게 남김없이 나누어 주는 경우의 수는 얼마입니까?",
    choices: ["15", "21", "25", "35"],
    answer: "21",
    unit: "가지",
    explanation: "중복조합 공식 H(n, r) = C(n + r − 1, r)을 사용합니다. 학생 수 n = 3이고 사탕 수 r = 5입니다. C(7, 5) = C(7, 2)를 계산하면 21이 되므로 답은 21입니다.",
    hint: "막대 2개와 별 5개를 일렬로 나열하는 경우로 바꾸어 보세요."
  },
  {
    id: "p_hi_071",
    formulaId: "hi_stars_bars",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "combinatorics",
    level: 3,
    type: "input",
    question: "x + y + z = 4를 만족하는 음이 아닌 정수해의 개수는 몇 개입니까?",
    choices: null,
    answer: "15",
    unit: "개",
    explanation: "음이 아닌 정수해의 개수는 중복조합 H(3, 4)와 같습니다. 변수 개수는 3개이고 합은 4입니다. C(6, 4) = C(6, 2)를 계산하면 15가 되므로 답은 15입니다.",
    hint: "공 4개와 칸막이 2개를 나열하는 경우로 바꾸어 보세요."
  },
  {
    id: "p_hi_072",
    formulaId: "hi_binom_prob",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "동전을 3번 던질 때 앞면이 2번 나올 확률은 얼마입니까?",
    choices: ["1⁄8", "3⁄8", "1⁄2", "5⁄8"],
    answer: "3⁄8",
    unit: "",
    explanation: "이항분포 확률 공식 C(n, k)pᵏqⁿ⁻ᵏ를 사용합니다. 시행 횟수는 3이고 앞면 확률은 1⁄2입니다. C(3, 2) × (1⁄2)³을 계산하면 3⁄8이 되므로 답은 3⁄8입니다.",
    hint: "3번 중 앞면이 나올 자리 2곳을 고르는 경우부터 세어 보세요."
  },
  {
    id: "p_hi_073",
    formulaId: "hi_binom_prob",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 3,
    type: "input",
    question: "주사위를 4번 던질 때 1의 눈이 1번 나올 확률을 구하세요.",
    choices: null,
    answer: "80⁄243",
    unit: "",
    explanation: "이항분포 확률 공식 C(n, k)pᵏqⁿ⁻ᵏ를 사용합니다. 시행 횟수는 4이고 1의 눈이 나올 확률은 1⁄6입니다. C(4, 1) × (1⁄6) × (5⁄6)³을 계산하면 80⁄243이 되므로 답은 80⁄243입니다.",
    hint: "성공 확률 1⁄6과 실패 확률 5⁄6을 구분하여 대입해 보세요."
  },
  {
    id: "p_hi_074",
    formulaId: "hi_vector_add",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 1,
    type: "choice",
    question: "벡터 a = (1, 2)와 벡터 b = (3, 1)의 합 a + b는 무엇입니까?",
    choices: ["(3, 2)", "(4, 3)", "(4, 2)", "(1, 3)"],
    answer: "(4, 3)",
    unit: "",
    explanation: "벡터의 덧셈은 성분끼리 더하여 계산합니다. 주어진 벡터는 a = (1, 2)이고 b = (3, 1)입니다. x성분끼리 y성분끼리 더하면 (4, 3)이 되므로 답은 (4, 3)입니다.",
    hint: "x좌표끼리 y좌표끼리 각각 더해 보세요."
  },
  {
    id: "p_hi_075",
    formulaId: "hi_vector_add",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 2,
    type: "input",
    question: "벡터 a = (2, −1)과 벡터 b = (−1, 4)에 대하여 2a + b를 구하세요.",
    choices: null,
    answer: "(3, 2)",
    unit: "",
    explanation: "벡터의 실수배와 덧셈을 차례로 계산합니다. 주어진 벡터에서 2a = (4, −2)입니다. 여기에 b = (−1, 4)를 더하면 (3, 2)가 되므로 답은 (3, 2)입니다.",
    hint: "먼저 2a를 구한 뒤 b의 성분을 각각 더해 보세요."
  },
  {
    id: "p_hi_076",
    formulaId: "hi_inner_product",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 2,
    type: "choice",
    question: "벡터 a = (2, 3)과 벡터 b = (1, −2)의 내적 a · b의 값은 얼마입니까?",
    choices: ["−4", "−2", "4", "8"],
    answer: "−4",
    unit: "",
    explanation: "벡터의 내적 공식 a · b = x₁x₂ + y₁y₂를 사용합니다. 주어진 성분은 (2, 3)과 (1, −2)입니다. 2 × 1 + 3 × (−2)를 계산하면 −4가 되므로 답은 −4입니다.",
    hint: "x좌표끼리 곱한 값과 y좌표끼리 곱한 값을 더해 보세요."
  },
  {
    id: "p_hi_077",
    formulaId: "hi_inner_product",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 3,
    type: "input",
    question: "벡터 a = (1, 2)와 벡터 b = (3, k)가 서로 수직일 때 상수 k의 값은 얼마입니까?",
    choices: null,
    answer: "−3⁄2",
    unit: "",
    explanation: "두 벡터가 수직이면 내적이 0이 됩니다. 주어진 벡터의 내적은 1 × 3 + 2 × k입니다. 방정식 3 + 2k = 0을 풀면 k = −3⁄2가 되므로 답은 −3⁄2입니다.",
    hint: "수직 조건은 내적이 0이 되는 것이에요."
  },
  {
    id: "p_hi_078",
    formulaId: "hi_position_vector",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 2,
    type: "choice",
    question: "점 A(1, 2)와 점 B(4, 6)에 대하여 벡터 AB는 무엇입니까?",
    choices: ["(3, 4)", "(4, 4)", "(5, 8)", "(3, 8)"],
    answer: "(3, 4)",
    unit: "",
    explanation: "위치벡터의 뺄셈 공식 AB = B − A를 사용합니다. 주어진 점은 A(1, 2)이고 B(4, 6)입니다. 각 성분을 빼면 (3, 4)가 되므로 답은 (3, 4)입니다.",
    hint: "도착점 좌표에서 출발점 좌표를 빼 보세요."
  },
  {
    id: "p_hi_079",
    formulaId: "hi_position_vector",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "vector",
    level: 3,
    type: "input",
    question: "점 A(2, 1)과 점 B(6, 5)에 대하여 선분 AB를 1 : 3으로 내분하는 점의 좌표는 무엇입니까?",
    choices: null,
    answer: "(3, 2)",
    unit: "",
    explanation: "내분점 공식 ((nx₁ + mx₂)⁄(m + n), (ny₁ + my₂)⁄(m + n))을 사용합니다. 주어진 점과 비율은 A(2, 1)과 B(6, 5)와 1 : 3입니다. 공식에 대입하면 (3, 2)가 되므로 답은 (3, 2)입니다.",
    hint: "내분점 공식에 비율과 좌표를 차례로 대입해 보세요."
  },
  {
    id: "p_hi_080",
    formulaId: "hi_normal_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "확률변수 X가 정규분포 N(50, 10²)을 따를 때 P(40 ≤ X ≤ 60)의 값은 얼마입니까?",
    choices: ["0.3413", "0.6826", "0.9544", "0.9974"],
    answer: "0.6826",
    unit: "",
    explanation: "표준화 공식 Z = (X − m)⁄σ를 사용합니다. 주어진 평균은 50이고 표준편차는 10입니다. 구간을 표준화하면 P(−1 ≤ Z ≤ 1)이 되어 확률 0.6826을 구합니다.",
    hint: "평균에서 표준편차만큼 떨어진 구간은 약 68퍼센트예요."
  },
  {
    id: "p_hi_081",
    formulaId: "hi_normal_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 3,
    type: "input",
    question: "확률변수 X가 표준정규분포 N(0, 1)을 따르고 P(Z ≥ 1.96) = 0.025일 때 P(|Z| ≤ 1.96)의 값은 얼마입니까?",
    choices: null,
    answer: "0.95",
    unit: "",
    explanation: "표준정규분포의 대칭성을 이용합니다. 주어진 꼬리 확률은 양쪽 각각 0.025입니다. 전체 확률 1에서 0.05를 빼면 0.95가 되므로 답은 0.95입니다.",
    hint: "양쪽 꼬리 확률을 전체 1에서 빼 보세요."
  },
  {
    id: "p_hi_082",
    formulaId: "hi_binom_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "X가 이항분포 B(10, 1⁄2)을 따를 때 평균 E(X)의 값은 얼마입니까?",
    choices: ["2", "5", "10", "20"],
    answer: "5",
    unit: "",
    explanation: "이항분포의 평균 공식 E(X) = np를 사용합니다. 주어진 시행 횟수는 10이고 성공 확률은 1⁄2입니다. 10 × 1⁄2을 계산하면 5가 되므로 답은 5입니다.",
    hint: "시행 횟수와 성공 확률을 곱해 보세요."
  },
  {
    id: "p_hi_083",
    formulaId: "hi_binom_dist",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 3,
    type: "input",
    question: "X가 이항분포 B(20, 1⁄4)을 따를 때 분산 V(X)의 값은 얼마입니까?",
    choices: null,
    answer: "15⁄4",
    unit: "",
    explanation: "이항분포의 분산 공식 V(X) = npq를 사용합니다. 주어진 값은 n = 20이고 p = 1⁄4이며 q = 3⁄4입니다. 20 × 1⁄4 × 3⁄4을 계산하면 15⁄4가 되므로 답은 15⁄4입니다.",
    hint: "시행 횟수와 성공 확률과 실패 확률을 모두 곱해 보세요."
  },
  {
    id: "p_hi_084",
    formulaId: "hi_estimation",
    schoolLevel: "high",
    gradeLevel: "high3",
    topic: "statistics",
    level: 2,
    type: "choice",
    question: "모평균 m에 대한 신뢰도 95퍼센트 신뢰구간이 48 ≤ m ≤ 52일 때 표본평균은 얼마입니까?",
    choices: ["49", "50", "51", "52"],
    answer: "50",
    unit: "",
    explanation: "신뢰구간은 표본평균을 중심으로 대칭입니다. 주어진 구간의 양 끝은 48과 52입니다. 두 값의 평균 (48 + 52)⁄2를 계산하면 50이 되므로 답은 50입니다.",
    hint: "신뢰구간의 양 끝값을 더하여 2로 나누어 보세요."
  },
  {
    id: "p_hi_085",
    formulaId: "hi_exp_func",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "function",
    level: 2,
    type: "choice",
    question: "지수함수 y = 2ˣ의 그래프가 반드시 지나는 점은 무엇입니까?",
    choices: ["(0, 0)", "(0, 1)", "(1, 0)", "(2, 1)"],
    answer: "(0, 1)",
    unit: "",
    explanation: "지수함수 y = aˣ은 a⁰ = 1 성질을 가집니다. 주어진 밑은 2이므로 x = 0일 때 y = 1입니다. 따라서 그래프는 점 (0, 1)을 지나므로 답은 (0, 1)입니다.",
    hint: "x = 0을 대입하면 모든 지수함수의 y절편을 알 수 있어요."
  },
  {
    id: "p_hi_086",
    formulaId: "hi_amgm",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 2,
    type: "choice",
    question: "양수 x에 대하여 x + 4⁄x의 최솟값은 얼마입니까?",
    choices: ["2", "4", "6", "8"],
    answer: "4",
    unit: "",
    explanation: "산술기하평균 부등식 a + b ≥ 2√ab를 사용합니다. 주어진 식에서 a = x이고 b = 4⁄x입니다. 2√4 = 4를 계산하면 최솟값 4를 구합니다.",
    hint: "두 수의 곱이 일정할 때 합이 최소가 되는 경우를 떠올려 보세요."
  }
];
