/* ============================================================
   수학아 놀자 (math) - 고등 문제 40개: 로그·삼각·수열 (problem-hi-a.js)
   problem-data.js 가 합쳐서 window.MathProblemData 로 만듭니다.
   ============================================================ */
window.MathProblemHiA = [
  {
    id: "p_hi_001",
    formulaId: "hi_exp_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 1,
    type: "choice",
    question: "2의 3제곱 곱하기 2의 4제곱의 값은?",
    choices: ["64", "128", "256", "512"],
    answer: "128",
    unit: "",
    explanation: "지수법칙은 밑이 같을 때 지수를 더하는 규칙이에요. 주어진 식의 밑은 모두 2로 같아요. 지수를 더하면 3 더하기 4는 7이 돼요. 따라서 2의 7제곱인 128이 답이에요.",
    hint: "밑이 같으면 지수끼리 더해 보세요."
  },
  {
    id: "p_hi_002",
    formulaId: "hi_exp_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 2,
    type: "input",
    question: "3의 2제곱을 다시 3제곱하면 3의 몇 제곱이 됩니까? 지수를 구하세요.",
    choices: null,
    answer: "6",
    unit: "",
    explanation: "거듭제곱의 거듭제곱은 지수끼리 곱하는 규칙이에요. 주어진 식의 안쪽 지수는 2이고 바깥쪽 지수는 3이에요. 두 지수를 곱하면 2 곱하기 3은 6이 돼요. 따라서 3의 6제곱이므로 지수는 6이에요.",
    hint: "거듭제곱을 한 번 더 거듭제곱하면 지수끼리 곱하세요."
  },
  {
    id: "p_hi_003",
    formulaId: "hi_log_def",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 1,
    type: "choice",
    question: "log_3 81의 값은?",
    choices: ["2", "3", "4", "5"],
    answer: "4",
    unit: "",
    explanation: "로그는 밑을 몇 제곱해야 진수가 되는지를 묻는 질문이에요. 주어진 식의 밑은 3이고 진수는 81이에요. 3을 거듭제곱하면 3의 4제곱이 81이 돼요. 따라서 구하는 값은 4예요.",
    hint: "3을 몇 번 곱해야 81이 되는지 세어 보세요."
  },
  {
    id: "p_hi_004",
    formulaId: "hi_log_def",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 2,
    type: "input",
    question: "log_2 32의 값은?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "로그는 밑을 몇 제곱해야 진수가 되는지를 묻는 질문이에요. 주어진 식의 밑은 2이고 진수는 32예요. 2를 거듭제곱하면 2의 5제곱이 32가 돼요. 따라서 구하는 값은 5예요.",
    hint: "2를 거듭제곱해서 32가 되는 횟수를 세어 보세요."
  },
  {
    id: "p_hi_005",
    formulaId: "hi_log_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 1,
    type: "choice",
    question: "log_2 8 더하기 log_2 4의 값은?",
    choices: ["4", "5", "6", "7"],
    answer: "5",
    unit: "",
    explanation: "로그의 성질에 따르면 로그의 합은 진수의 곱과 같아요. 두 로그의 밑은 모두 2로 같아요. 진수를 곱하면 8 곱하기 4는 32가 되어 log_2 32가 돼요. 2의 5제곱이 32이므로 답은 5예요.",
    hint: "로그의 합은 진수끼리 곱한 로그와 같아요."
  },
  {
    id: "p_hi_006",
    formulaId: "hi_log_laws",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 2,
    type: "input",
    question: "log_2 4의 3제곱의 값은?",
    choices: null,
    answer: "6",
    unit: "",
    explanation: "진수의 거듭제곱은 지수를 앞으로 꺼내는 성질이 있어요. 주어진 식은 log_2 4의 3제곱이에요. 지수 3을 앞으로 꺼내면 3 곱하기 log_2 4가 돼요. log_2 4는 2이므로 3 곱하기 2는 6이에요.",
    hint: "진수의 거듭제곱 지수를 로그 앞으로 꺼내 보세요."
  },
  {
    id: "p_hi_007",
    formulaId: "hi_common_log",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 1,
    type: "choice",
    question: "log 10000의 값은? 밑이 생략된 상용로그예요.",
    choices: ["2", "3", "4", "5"],
    answer: "4",
    unit: "",
    explanation: "상용로그는 밑이 10인 로그를 뜻해요. 10을 몇 제곱해야 10000이 되는지 물어보는 식이에요. 10의 4제곱이 10000이에요. 따라서 구하는 값은 4예요.",
    hint: "10000을 만들려면 10을 몇 번 곱해야 하는지 세어 보세요."
  },
  {
    id: "p_hi_008",
    formulaId: "hi_common_log",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "logarithm",
    level: 2,
    type: "input",
    question: "2000의 상용로그의 지표는?",
    choices: null,
    answer: "3",
    unit: "",
    explanation: "상용로그의 지표는 자릿수에서 1을 뺀 값이에요. 주어진 2000은 네 자리 수예요. 네 자리 수의 지표는 4 빼기 1이 돼요. 따라서 지표는 3이에요.",
    hint: "자릿수를 세고 거기에서 1을 빼 보세요."
  },
  {
    id: "p_hi_009",
    formulaId: "hi_trig_ratio",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "빗변의 길이가 10이고 높이가 6인 직각삼각형에서 구하는 각의 사인 값은?",
    choices: ["5분의 3", "5분의 4", "3분의 4", "2분의 1"],
    answer: "5분의 3",
    unit: "",
    explanation: "사인은 빗변 분의 높이로 구하는 비율이에요. 주어진 빗변은 10이고 높이는 6이에요. 분수에 대입하면 10분의 6이 돼요. 약분하면 5분의 3이 답이에요.",
    hint: "사인은 빗변 분의 높이라는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_010",
    formulaId: "hi_trig_ratio",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "input",
    question: "빗변이 13이고 밑변이 5인 직각삼각형에서 구하는 각의 코사인 값은?",
    choices: null,
    answer: "13분의 5",
    unit: "",
    explanation: "코사인은 빗변 분의 밑변으로 구하는 비율이에요. 주어진 빗변은 13이고 밑변은 5예요. 분수에 대입하면 13분의 5가 돼요. 더 이상 약분되지 않으므로 답은 13분의 5예요.",
    hint: "코사인은 빗변 분의 밑변이라는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_011",
    formulaId: "hi_special_angles",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "사인 60도의 값은?",
    choices: ["2분의 1", "2분의 루트2", "2분의 루트3", "1"],
    answer: "2분의 루트3",
    unit: "",
    explanation: "특별한 각의 삼각비는 외워 두면 계산이 빨라져요. 60도의 사인 값은 2분의 루트3으로 정해져 있어요. 보기의 값들과 하나씩 비교해 보세요. 따라서 2분의 루트3이 답이에요.",
    hint: "30도와 60도의 사인 값을 서로 바꾸지 않도록 주의하세요."
  },
  {
    id: "p_hi_012",
    formulaId: "hi_special_angles",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "input",
    question: "탄젠트 45도의 값은?",
    choices: null,
    answer: "1",
    unit: "",
    explanation: "45도의 직각삼각형은 두 직각변이 서로 같아요. 탄젠트는 밑변 분의 높이이므로 1이 돼요. 45도는 특별한 각이라서 값이 1로 정해져 있어요. 따라서 답은 1이에요.",
    hint: "45도 삼각형은 두 직각변의 길이가 같다는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_013",
    formulaId: "hi_unit_circle",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "단위원 위에서 90도에 대응하는 점의 좌표는?",
    choices: ["(1, 0)", "(0, 1)", "(-1, 0)", "(0, -1)"],
    answer: "(0, 1)",
    unit: "",
    explanation: "단위원은 반지름이 1인 원 위의 점으로 삼각비를 나타내요. 90도는 원의 꼭대기에 해당하는 각도예요. 꼭대기 점의 좌표는 가로가 0이고 세로가 1이에요. 따라서 (0, 1)이 답이에요.",
    hint: "단위원에서 90도가 가리키는 위치를 그림으로 떠올려 보세요."
  },
  {
    id: "p_hi_014",
    formulaId: "hi_unit_circle",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "input",
    question: "코사인 180도의 값은?",
    choices: null,
    answer: "-1",
    unit: "",
    explanation: "단위원에서 코사인은 점의 가로 좌표와 같아요. 180도에 대응하는 점은 가로가 -1이고 세로가 0이에요. 가로 좌표를 읽으면 -1이 돼요. 따라서 답은 -1이에요.",
    hint: "단위원에서 코사인은 가로 좌표라는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_015",
    formulaId: "hi_radian",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "180도를 라디안으로 나타내면?",
    choices: ["2분의 파이", "파이", "2파이", "4분의 파이"],
    answer: "파이",
    unit: "",
    explanation: "라디안은 호의 길이로 각도를 재는 단위예요. 180도는 반원과 같은 각도예요. 반원의 호에 대응하는 라디안은 파이예요. 따라서 답은 파이예요.",
    hint: "180도가 파이라는 기본 관계를 떠올려 보세요."
  },
  {
    id: "p_hi_016",
    formulaId: "hi_radian",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "input",
    question: "90도를 라디안으로 나타내면?",
    choices: null,
    answer: "2분의 파이",
    unit: "",
    explanation: "180도가 파이에 대응한다는 관계를 이용해요. 90도는 180도의 절반인 각도예요. 파이의 절반을 구하면 2분의 파이가 돼요. 따라서 답은 2분의 파이예요.",
    hint: "90도는 180도의 절반이라는 것을 이용해 보세요."
  },
  {
    id: "p_hi_017",
    formulaId: "hi_trig_graph",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "사인 함수 그래프의 주기는?",
    choices: ["파이", "2파이", "2분의 파이", "4파이"],
    answer: "2파이",
    unit: "",
    explanation: "사인 그래프는 물결처럼 반복되는 모양이에요. 한 물결이 완성되는 구간이 바로 주기예요. 사인 함수는 2파이가 지나면 같은 모양이 반복돼요. 따라서 주기는 2파이예요.",
    hint: "사인 그래프가 한 바퀴 돌아 같은 모양이 되는 구간을 떠올려 보세요."
  },
  {
    id: "p_hi_018",
    formulaId: "hi_trig_graph",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "input",
    question: "코사인 0도의 값은?",
    choices: null,
    answer: "1",
    unit: "",
    explanation: "코사인 그래프는 0도에서 가장 높은 점에서 시작해요. 단위원에서 0도에 대응하는 점은 가로가 1이고 세로가 0이에요. 가로 좌표가 코사인 값이므로 1이 돼요. 따라서 답은 1이에요.",
    hint: "코사인 그래프가 시작하는 가장 높은 점을 떠올려 보세요."
  },
  {
    id: "p_hi_019",
    formulaId: "hi_trig_identity",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 1,
    type: "choice",
    question: "같은 각에 대하여 사인의 제곱 더하기 코사인의 제곱의 값은?",
    choices: ["0", "1", "2", "-1"],
    answer: "1",
    unit: "",
    explanation: "삼각함수의 기본 항등식에 따르면 두 제곱의 합은 항상 1이에요. 어떤 각을 넣어도 이 관계는 변하지 않아요. 보기의 숫자들과 비교하면 1과 일치해요. 따라서 답은 1이에요.",
    hint: "가장 기본이 되는 삼각함수 항등식을 떠올려 보세요."
  },
  {
    id: "p_hi_020",
    formulaId: "hi_trig_identity",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "input",
    question: "예각 세타에 대하여 사인 세타가 5분의 3일 때 코사인 세타의 값은?",
    choices: null,
    answer: "5분의 4",
    unit: "",
    explanation: "사인 제곱 더하기 코사인 제곱은 1이라는 항등식을 이용해요. 사인이 5분의 3이므로 제곱하면 25분의 9가 돼요. 1에서 빼면 코사인 제곱은 25분의 16이 돼요. 예각이므로 양수인 5분의 4가 답이에요.",
    hint: "기본 항등식에 사인 값을 대입하고 코사인을 구해 보세요."
  },
  {
    id: "p_hi_021",
    formulaId: "hi_sine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "choice",
    question: "외접원의 반지름이 4이고 한 각이 30도일 때 그 각이 마주 보는 변의 길이는?",
    choices: ["2", "4", "6", "8"],
    answer: "4",
    unit: "",
    explanation: "사인법칙은 변을 사인으로 나눈 값이 외접원 지름과 같다는 규칙이에요. 외접원 지름은 4 곱하기 2로 8이에요. 30도의 사인은 2분의 1이므로 변의 길이는 8 곱하기 2분의 1이 돼요. 계산하면 4가 답이에요.",
    hint: "변의 길이는 외접원 지름에 사인 값을 곱한 것과 같아요."
  },
  {
    id: "p_hi_022",
    formulaId: "hi_sine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 3,
    type: "input",
    question: "외접원의 반지름이 6이고 한 각이 90도일 때 그 각이 마주 보는 변의 길이는?",
    choices: null,
    answer: "12",
    unit: "",
    explanation: "사인법칙에 따르면 구하는 변은 외접원 지름 곱하기 사인 값이에요. 외접원 지름은 6 곱하기 2로 12예요. 90도의 사인은 1이에요. 따라서 12 곱하기 1은 12가 답이에요.",
    hint: "90도의 사인 값과 외접원 지름을 곱해 보세요."
  },
  {
    id: "p_hi_023",
    formulaId: "hi_cosine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 2,
    type: "choice",
    question: "두 변의 길이가 3과 4이고 끼인각이 90도일 때 마주 보는 변의 길이는?",
    choices: ["3", "4", "5", "6"],
    answer: "5",
    unit: "",
    explanation: "코사인법칙은 세 변과 한 각의 관계를 나타내는 규칙이에요. 끼인각이 90도이므로 코사인 값이 0이 돼요. 식에 대입하면 9 더하기 16 빼기 0으로 25가 돼요. 제곱근을 구하면 5가 답이에요.",
    hint: "90도의 코사인이 0이 된다는 것을 이용해 보세요."
  },
  {
    id: "p_hi_024",
    formulaId: "hi_cosine_rule",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "trigonometry",
    level: 3,
    type: "input",
    question: "두 변의 길이가 5와 5이고 끼인각이 60도일 때 마주 보는 변의 길이는?",
    choices: null,
    answer: "5",
    unit: "",
    explanation: "코사인법칙에 세 값을 순서대로 대입해요. 60도의 코사인은 2분의 1이에요. 계산하면 25 더하기 25 빼기 25로 25가 돼요. 제곱근을 구하면 5가 답이에요.",
    hint: "60도의 코사인 값을 먼저 떠올리고 식에 대입해 보세요."
  },
  {
    id: "p_hi_025",
    formulaId: "hi_arith_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "첫째항이 2이고 공차가 3인 등차수열의 다섯째항은?",
    choices: ["11", "12", "14", "17"],
    answer: "14",
    unit: "",
    explanation: "등차수열의 일반항은 첫째항에 공차 곱하기 항번호 빼기 1을 더해요. 주어진 첫째항은 2이고 공차는 3이에요. 다섯째항이므로 2 더하기 3 곱하기 4를 계산해요. 따라서 14가 답이에요.",
    hint: "첫째항에서 공차를 네 번 더한다는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_026",
    formulaId: "hi_arith_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 2,
    type: "input",
    question: "5, 9, 13으로 시작하는 등차수열의 열째항은?",
    choices: null,
    answer: "41",
    unit: "",
    explanation: "등차수열에서는 이웃한 항의 차이가 일정해요. 주어진 수열의 공차는 9 빼기 5로 4예요. 일반항에 대입하면 열째항은 5 더하기 4 곱하기 9가 돼요. 계산하면 41이 답이에요.",
    hint: "이웃한 두 항의 차이부터 구해 보세요."
  },
  {
    id: "p_hi_027",
    formulaId: "hi_geo_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "첫째항이 2이고 공비가 3인 등비수열의 셋째항은?",
    choices: ["12", "18", "24", "27"],
    answer: "18",
    unit: "",
    explanation: "등비수열의 일반항은 첫째항에 공비의 거듭제곱을 곱해요. 주어진 첫째항은 2이고 공비는 3이에요. 셋째항이므로 2 곱하기 3의 2제곱을 계산해요. 따라서 18이 답이에요.",
    hint: "첫째항에 공비를 두 번 곱한다는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_028",
    formulaId: "hi_geo_seq",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 2,
    type: "input",
    question: "3, 6, 12로 시작하는 등비수열의 여섯째항은?",
    choices: null,
    answer: "96",
    unit: "",
    explanation: "등비수열에서는 이웃한 항의 비가 일정해요. 주어진 수열의 공비는 6 나누기 3으로 2예요. 일반항에 대입하면 여섯째항은 3 곱하기 2의 5제곱이 돼요. 계산하면 96이 답이에요.",
    hint: "이웃한 두 항의 비부터 구해 보세요."
  },
  {
    id: "p_hi_029",
    formulaId: "hi_arith_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "1부터 10까지의 자연수의 합은?",
    choices: ["45", "50", "55", "60"],
    answer: "55",
    unit: "",
    explanation: "등차수열의 합은 첫째항과 끝항을 이용한 공식으로 구해요. 첫째항은 1이고 끝항은 10이며 항의 개수는 10이에요. 공식에 대입하면 10 곱하기 11 나누기 2가 돼요. 계산하면 55가 답이에요.",
    hint: "첫째항과 끝항을 더한 뒤 항의 개수와 곱해 보세요."
  },
  {
    id: "p_hi_030",
    formulaId: "hi_arith_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 3,
    type: "input",
    question: "첫째항이 3이고 공차가 2인 등차수열의 첫 10개 항의 합은?",
    choices: null,
    answer: "120",
    unit: "",
    explanation: "등차수열의 합 공식은 항의 개수 나누기 2 곱하기 첫째항의 2배 더하기 공차 곱하기 항의 개수 빼기 1이에요. 주어진 값을 대입하면 5 곱하기 6 더하기 18이 돼요. 6 더하기 18은 24예요. 따라서 5 곱하기 24인 120이 답이에요.",
    hint: "첫째항과 공차를 합 공식에 그대로 대입해 보세요."
  },
  {
    id: "p_hi_031",
    formulaId: "hi_geo_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "첫째항이 1이고 공비가 2인 등비수열의 첫 4개 항의 합은?",
    choices: ["13", "15", "17", "31"],
    answer: "15",
    unit: "",
    explanation: "등비수열의 합은 공비를 이용한 공식으로 구해요. 주어진 첫째항은 1이고 공비는 2이며 항의 개수는 4예요. 공식에 대입하면 2의 4제곱 빼기 1을 2 빼기 1로 나눈 값이 돼요. 계산하면 15가 답이에요.",
    hint: "1, 2, 4, 8을 직접 더해도 확인할 수 있어요."
  },
  {
    id: "p_hi_032",
    formulaId: "hi_geo_sum",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 2,
    type: "input",
    question: "첫째항이 3이고 공비가 2인 등비수열의 첫 5개 항의 합은?",
    choices: null,
    answer: "93",
    unit: "",
    explanation: "등비수열의 합 공식을 그대로 이용해요. 주어진 값을 대입하면 3 곱하기 2의 5제곱 빼기 1을 2 빼기 1로 나눈 식이 돼요. 2의 5제곱은 32이므로 32 빼기 1은 31이에요. 따라서 3 곱하기 31인 93이 답이에요.",
    hint: "공비가 2이므로 2의 거듭제곱을 먼저 계산해 보세요."
  },
  {
    id: "p_hi_033",
    formulaId: "hi_sigma",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "시그마 기호로 1부터 5까지 케이를 더한 값은?",
    choices: ["10", "12", "15", "20"],
    answer: "15",
    unit: "",
    explanation: "시그마는 정해진 범위의 식을 모두 더하라는 기호예요. 케이에 1부터 5까지를 차례로 넣어요. 더하면 1 더하기 2 더하기 3 더하기 4 더하기 5가 돼요. 계산하면 15가 답이에요.",
    hint: "1부터 5까지의 수를 직접 모두 더해 보세요."
  },
  {
    id: "p_hi_034",
    formulaId: "hi_sigma",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "sequence",
    level: 2,
    type: "input",
    question: "시그마 기호로 1부터 4까지 2 케이를 더한 값은?",
    choices: null,
    answer: "20",
    unit: "",
    explanation: "시그마 안의 식에 케이 값을 차례로 대입해요. 2 케이에 1부터 4까지를 넣으면 2, 4, 6, 8이 돼요. 네 수를 모두 더하면 20이 돼요. 따라서 답은 20이에요.",
    hint: "2의 배수를 8까지 더한다는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_035",
    formulaId: "hi_infinite_geo",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    level: 2,
    type: "choice",
    question: "첫째항이 1이고 공비가 2분의 1인 무한등비수열의 합은?",
    choices: ["1", "2", "3", "4"],
    answer: "2",
    unit: "",
    explanation: "무한등비급수의 합은 첫째항 나누기 1 빼기 공비로 구해요. 주어진 첫째항은 1이고 공비는 2분의 1이에요. 분모를 계산하면 1 빼기 2분의 1은 2분의 1이 돼요. 따라서 1 나누기 2분의 1인 2가 답이에요.",
    hint: "첫째항을 1 빼기 공비로 나눈다는 공식을 떠올려 보세요."
  },
  {
    id: "p_hi_036",
    formulaId: "hi_infinite_geo",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    level: 3,
    type: "input",
    question: "첫째항이 12이고 공비가 4분의 1인 무한등비수열의 합은?",
    choices: null,
    answer: "16",
    unit: "",
    explanation: "공비의 절댓값이 1보다 작으므로 무한합 공식을 쓸 수 있어요. 주어진 값을 대입하면 12 나누기 1 빼기 4분의 1이 돼요. 분모는 4분의 3이에요. 계산하면 16이 답이에요.",
    hint: "분모의 분수를 먼저 통분해서 정리해 보세요."
  },
  {
    id: "p_hi_037",
    formulaId: "hi_induction",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    level: 1,
    type: "choice",
    question: "수학적 귀납법의 첫 단계에서 확인하는 것은?",
    choices: ["자연수 1일 때 성립 확인", "자연수 100일 때 성립 확인", "모든 자연수 직접 대입", "결론 먼저 증명"],
    answer: "자연수 1일 때 성립 확인",
    unit: "",
    explanation: "수학적 귀납법은 기본 단계와 귀납 단계로 이루어져 있어요. 기본 단계에서는 가장 작은 자연수인 1일 때 명제가 성립함을 보여요. 그다음 1일 때 성립을 발판 삼아 다음 단계로 이어가요. 따라서 첫 단계는 자연수 1일 때 성립 확인이에요.",
    hint: "귀납법은 가장 작은 자연수부터 시작한다는 것을 떠올려 보세요."
  },
  {
    id: "p_hi_038",
    formulaId: "hi_induction",
    schoolLevel: "high",
    gradeLevel: "high2",
    topic: "sequence",
    level: 2,
    type: "input",
    question: "1부터 엔까지의 합 공식이 엔과 같은 3일 때 좌변의 값은?",
    choices: null,
    answer: "6",
    unit: "",
    explanation: "귀납법의 기본 단계에서는 작은 수부터 직접 확인해요. 엔이 3이므로 좌변은 1 더하기 2 더하기 3이 돼요. 차례로 더하면 6이 돼요. 따라서 좌변의 값은 6이에요.",
    hint: "1부터 3까지의 수를 직접 더해 보세요."
  },
  {
    id: "p_hi_039",
    formulaId: "hi_remainder",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 1,
    type: "choice",
    question: "x의 3제곱 더하기 2를 x 빼기 1로 나눈 나머지는?",
    choices: ["1", "2", "3", "4"],
    answer: "3",
    unit: "",
    explanation: "나머지정리에 따르면 나머지는 제수식을 0으로 만드는 값을 대입한 것과 같아요. x 빼기 1이 0이 되는 값은 1이에요. 다항식에 1을 대입하면 1 더하기 2가 돼요. 따라서 나머지는 3이에요.",
    hint: "나누는 식을 0으로 만드는 값을 다항식에 대입해 보세요."
  },
  {
    id: "p_hi_040",
    formulaId: "hi_remainder",
    schoolLevel: "high",
    gradeLevel: "high1",
    topic: "algebra",
    level: 2,
    type: "input",
    question: "x의 3제곱 빼기 2x 더하기 5를 x 더하기 1로 나눈 나머지는?",
    choices: null,
    answer: "6",
    unit: "",
    explanation: "나머지정리를 이용해 제수식을 0으로 만드는 값을 찾아요. x 더하기 1이 0이 되는 값은 -1이에요. 다항식에 -1을 대입하면 -1 더하기 2 더하기 5가 돼요. 계산하면 6이므로 답은 6이에요.",
    hint: "x 더하기 1이 0이 되는 값을 먼저 찾아보세요."
  }
];
